/**
 * Kamus terjemahan Komunitas Catur Indonesia.
 * Struktur bersarang; kunci dipakai oleh t("a.b.c").
 */
export const ID = {
  common: {
    home: "Home",
    id: "ID",
    en: "EN",
    bahasaIndonesia: "Bahasa Indonesia",
    english: "English",
    namaKomunitas: "Komunitas Catur Indonesia",
    selanjutnya: "Selanjutnya",
    daftarAnggota: "Daftar Anggota",
    alamat: "Address",
    surel: "Email",
    pilihBahasa: "Pilih bahasa",
  },
  nav: {
    tentangKami: "Tentang Kami",
    programKami: "Program Kami",
    turnamen: "Turnamen",
    mediaDanInformasi: "Media & Informasi",
    keanggotaan: "Keanggotaan",
    sekilasKomunitas: "Sekilas Komunitas",
    tonggakSejarah: "Tonggak Sejarah",
    visiMisiNilai: "Visi, Misi, & Tata Nilai",
    maknaLogo: "Makna Logo",
    strukturPengurus: "Struktur Pengurus",
    strukturGrupCatur: "Struktur Grup Catur",
    pengurus: "Pengurus",
    strukturOrganisasiCatur: "Struktur Organisasi Catur",
    kelasPelatihan: "Kelas & Pelatihan",
    coachingClinic: "Coaching Clinic",
    simultanBlindfold: "Simultan & Blindfold",
    sekolahCatur: "Sekolah Catur",
    caraBermainCatur: "Cara Bermain Catur",
    turnamenBulanan: "Turnamen Bulanan",
    ligaMusiman: "Liga Musiman",
    turnamenTerbuka: "Turnamen Terbuka",
    ligaAntarKomunitas: "Liga Antar Komunitas",
    beritaKomunitas: "Berita Komunitas",
    galeri: "Galeri",
    buletinBulanan: "Buletin Bulanan",
    pengumuman: "Pengumuman",
    pendaftaranAnggota: "Pendaftaran Anggota",
    syaratKetentuan: "Syarat & Ketentuan",
    kodeEtik: "Kode Etik Komunitas",
    pertanyaanUmum: "Pertanyaan Umum",
    hubungiKami: "Hubungi Kami",
    karir: "Karir",
    beranda: "Beranda",
    peringkat: "Peringkat",
    pengadaan: "Pengadaan",
    keberlanjutan: "Keberlanjutan",
  },
  header: {
    close: "tutup",
    closeSearch: "tutup pencarian",
    searchButton: "tombol pencarian",
    menu: "menu",
    search: "cari",
    expand: "buka {title}",
  },
  search: {
    placeholder: "Ketik kata kunci pencarian",
    enter: "Tekan Enter untuk mencari",
    noResults: "Tidak ditemukan hasil untuk “{query}”.",
  },
  footer: {
    pengumuman: "Pengumuman",
    beritaKomunitas: "Berita Komunitas",
    pendaftaranTurnamen: "Pendaftaran Turnamen",
    pengumumanLink: "Pengumuman",
    jadwalLiga: "Jadwal Liga",
    musyawarahAnggota: "Musyawarah Anggota",
    volunteer: "Volunteer",
    network: "Network",
    chapterSumut: "Chapter Sumatera Utara",
    chapterJakarta: "Chapter DKI Jakarta",
    chapterJabar: "Chapter Jawa Barat",
    chapterJatim: "Chapter Jawa Timur",
    chapterSulsel: "Chapter Sulawesi Selatan",
    akademiCatur: "Akademi Catur",
    tools: "Tools",
    papanInteraktif: "Papan Interaktif",
    pendaftaranAnggota: "Pendaftaran Anggota",
    kodeEtik: "Kode Etik Komunitas",
    keterbukaanInformasi: "Keterbukaan Informasi",
    kontakKami: "Kontak Kami",
    sistemPengaduan: "Sistem Pengaduan",
    alamat: "Address: Sekretariat Komunitas Catur Indonesia, Jl. Gatot Subroto No. 11-13, Medan 20152, Sumatera Utara, Indonesia",
    copyright: "© Copyright Komunitas Catur Indonesia 2025. All Right Reserved.",
    privasi: "Kebijakan Privasi",
    penipuan: "Waspada Penipuan",
  },
  hero: {
    tentangKami: "Tentang Kami",
    deskripsi:
      "Telusuri sejarah perjalanan, visi, dan misi komunitas kami yang menjadi fondasi kegiatan, filosofi logo, serta struktur pengurus yang mendukung pengembangan catur Indonesia.",
  },
  sticky: {
    sekilasKomunitas: "Sekilas Komunitas",
    tonggakSejarah: "Tonggak Sejarah",
    visiMisiNilai: "Visi, Misi, & Tata Nilai",
    maknaLogo: "Makna Logo",
    strukturPengurus: "Struktur Pengurus",
  },
  bagian: {
    selanjutnya: "Selanjutnya",
    dewanPengurus: "Dewan Pengurus dan Dewan Pembina",
  },
  sekilas: {
    judul: "Sekilas Komunitas",
    p1: "Komunitas Catur Indonesia senantiasa memegang teguh komitmen untuk menyediakan wadah bermain dan belajar catur serta mengembangkan pembinaan usia muda dalam rangka mendukung terciptanya kemandirian prestasi catur nasional. Memegang amanah sebagai komunitas catur terverifikasi di Chess.com sejak ditetapkan pada tanggal 10 Desember 2015, komunitas kini memiliki peran sangat strategis yang membawahi lima Divisi yang bergerak di bidang pengembangan catur, yaitu Divisi Turnamen yang menjalankan kompetisi internal dan eksternal, Divisi Pembinaan yang menjalankan kelas dan pelatihan, Divisi Media & Humas yang mengelola publikasi, Divisi Keanggotaan yang mengelola administrasi anggota, serta Divisi Teknologi yang mengelola platform daring komunitas.",
    p2: "Peran penting yang diemban oleh komunitas ini sekaligus menandai tonggak sejarah baru dalam perjalanan komunitas setelah kontribusi nyata yang diberikan selama lebih dari satu dekade menyediakan wadah bertanding yang telah menggerakkan semangat pecatur Indonesia dari berbagai daerah.",
    p3: "Kemampuan komunitas yang mumpuni ini dibangun di atas fondasi yang solid dan sejarah panjang dalam mengawal terwujudnya pembinaan catur nasional. Sejarah mencatat bahwa eksistensi Komunitas Catur Indonesia dibangun sejak sekitar tahun 2014, ketika sekelompok pecatur di Medan mulai berkumpul rutin untuk bertanding catur kilat di sebuah warung kopi. Kemudian kelompok tersebut resmi menjadi komunitas pada tanggal 10 Desember 2015, yang hingga kini diperingati sebagai hari lahir komunitas.",
    p4: "Pada tahun 2018, komunitas resmi membentuk klub di Chess.com sebagai basis pertandingan daring seluruh anggota. Selanjutnya, peran komunitas semakin strategis setelah pada tahun 2020 menginisiasi program kelas catur daring gratis bagi pelajar di tengah masa pandemi.",
    p5: "Berdasarkan kesepakatan Musyawarah Anggota tanggal 18 Juni 2023, komunitas mengubah struktur organisasi menjadi struktur kepengurusan dengan divisi-divisi fungsional. Pada tanggal 10 Desember 2024, komunitas memperbarui identitas visual dengan logo kuda catur berwarna dasar biru, merah, dan hijau yang merefleksikan unsur dinamis dan kepedulian pada pembinaan.",
    p6: "Bahkan setelah evolusi yang dialami selama satu dekade itu, komunitas berkomitmen untuk tetap menggaungkan semangat transformasi yang berkelanjutan guna menyempurnakan langkahnya menjadi komunitas catur terdepan di Indonesia yang didukung oleh organisasi yang semakin lincah, mudah beradaptasi, dan fokus untuk pengembangan pembinaan yang lebih luas.",
    imgAlt: "Suasana kegiatan rutin komunitas di sekretariat Medan",
    imgCaption: "Suasana kegiatan rutin komunitas di sekretariat Medan, 2025.",
  },
  tonggak: {
    judul: "Tonggak Sejarah",
    t1: "Perjalanan 2015-2016",
    p1a: "Sejarah mencatat bahwa eksistensi Komunitas Catur Indonesia dibangun sejak sekitar tahun 2014, ketika sekelompok pecatur Medan berkumpul rutin di sebuah warung kopi untuk bertanding catur kilat. Kemudian kelompok tersebut resmi menjadi komunitas dengan nama Komunitas Catur Indonesia pada 10 Desember 2015, yang hingga kini diperingati sebagai hari lahir komunitas.",
    p1b: "Selama tahun pertama, komunitas memperkokoh eksistensi sebagai satu-satunya komunitas catur terpadu di Kota Medan yang mewadahi pecatur dari berbagai latar belakang, mulai dari pelajar hingga pekerja profesional.",
    t2: "Perjalanan 2016-2017",
    p2a: "Memasuki tahun kedua, komunitas memaksimalkan pertumbuhan kegiatan dan memberikan kontribusi pada pembinaan catur daerah. Pada periode ini, eksistensi komunitas sebagai penggerak catur lokal mulai diakui oleh PERCASI Sumatera Utara. Perkembangan pesat tersebut salah satunya berkat kolaborasi turnamen bersama komunitas catur lain di Pulau Sumatera.",
    p2b: "Pada tahun 2017, komunitas resmi membentuk klub di Chess.com sebagai basis pertandingan daring bagi seluruh anggota, sekaligus menandai dimulainya era pertandingan daring rutin.",
    t3: "Perjalanan 2018-2019",
    p3a: "Pada periode ini, komunitas untuk pertama kalinya menyelenggarakan turnamen terbuka berskala kota dengan standar regulasi internasional. Dalam rentang waktu dua tahun ini, komunitas mampu menambah frekuensi turnamen internal menjadi dua kali dalam satu bulan.",
    p3b: "Di awal 2019, komunitas mulai meletakkan dasar pembinaan usia dini melalui kelas catur gratis bagi pelajar, serta membangun perpustakaan materi latihan digital.",
    t4: "Perjalanan 2020-2021",
    p4a: "Pada masa ini, komunitas menghadapi masa pandemi. Dengan dukungan para pengurus, pembenahan aspek organisasi dan platform daring dilakukan sebagai upaya komunitas untuk tetap aktif. Dalam rentang waktu ini, komunitas mampu menyelenggarakan turnamen daring mingguan yang diikuti anggota dari berbagai kota di Indonesia.",
    p4b: "Komunitas juga menginisiasi program kelas catur daring gratis bagi pelajar di tengah masa pandemi, yang menjadi cikal bakal Akademi Catur Komunitas.",
    t5: "Perjalanan 2022-2023",
    p5a: "Pada periode ini, komunitas berupaya mengembangkan pembinaan catur usia muda. Selama dua tahun terakhir, komunitas melakukan kerja sama dengan sekolah-sekolah di Medan dalam bentuk ekstrakurikuler catur dan lomba antar sekolah.",
    p5b: "Komunitas menunjukkan kesungguhannya dalam menjalankan kegiatan yang berwawasan sportivitas dengan membentuk fungsi baru, yaitu Komite Etik dan Fair Play pada 2022. Komunitas juga mulai menerapkan program penilaian performa anggota untuk meningkatkan keterlibatan seluruh anggota dalam berlatih.",
    t6: "Perjalanan 2024-2025",
    p6a: "Pada periode ini, tepatnya pada tahun 2024, komunitas mengubah struktur organisasi menjadi struktur kepengurusan dengan divisi-divisi fungsional guna mendukung efisiensi kegiatan. Pada 10 Desember 2024, komunitas memperbarui identitas visual dengan logo baru berwarna dasar biru, merah, dan hijau yang merefleksikan unsur dinamis dan kepedulian pada pembinaan.",
    p6b: "Komunitas juga melakukan transformasi pada 20 Juli 2025 melalui perombakan kurikulum latihan yang mengintegrasikan analisis digital dan latihan bersama pecatur bergelar, sebagai bagian dari target pencapaian 5.000 anggota aktif.",
  },
  visimisi: {
    visi: "Visi",
    visiLead: "Menjadi komunitas catur yang mengedepankan sportivitas, prestasi, dan pembinaan.",
    visiP1:
      "Komunitas Catur Indonesia berkomitmen untuk menjadi komunitas catur berskala nasional yang tidak hanya menjalankan kegiatan dengan landasan organisasi yang kuat, tetapi juga berperan strategis dalam mendukung pengembangan catur Indonesia, khususnya dalam memperkuat sportivitas, memastikan ketersediaan wadah bertanding, serta mendorong pembinaan yang berkelanjutan.",
    visiL1: "Sportivitas: memperkuat budaya fair play dan integritas dalam setiap pertandingan.",
    visiL2: "Prestasi: mewujudkan lingkungan kompetitif guna menjamin lahirnya pecatur berprestasi nasional dan internasional.",
    visiL3: "Pembinaan: mendorong pengembangan bakat usia muda sebagai langkah strategis dalam menjaga keberlanjutan regenerasi catur Indonesia.",
    misi: "Misi",
    misiLead:
      "Menyediakan wadah bermain dan belajar catur melalui program inovatif yang memberi nilai tambah untuk anggota dan masyarakat.",
    misiP1:
      "Misi untuk menyediakan wadah bermain dan belajar catur melalui program inovatif yang memberi nilai tambah bagi anggota dan masyarakat mencerminkan komitmen komunitas dalam menghadirkan kegiatan yang andal, berkelanjutan, dan relevan dengan dinamika perkembangan catur nasional dan global. Upaya tersebut dilakukan melalui fokus program pada dual-growth strategy, yaitu Maximizing Competitive Play dan Building Grassroots Development. Pilar Maximizing Competitive Play fokus pada peningkatan frekuensi turnamen internal, penguatan liga musiman, penguatan pertandingan persahabatan antar komunitas, serta pengembangan infrastruktur latihan. Sedangkan pilar Building Grassroots Development fokus pada pengembangan kelas pemula, ekosistem pelatihan daring, program sekolah catur, dan teknologi latihan digital.",
    tataNilai: "Tata Nilai",
    nilaiImgAlt: "Tata nilai komunitas",
    nilaiImgCaption:
      "Nilai-nilai yang dipegang teguh anggota komunitas dalam setiap pertandingan.",
  },
  maknaLogo: {
    judul: "Makna Logo",
    intro: "Makna dari logo Komunitas Catur Indonesia adalah:",
    l1: "Warna biru memiliki arti andal, dapat dipercaya, dan bertanggung jawab",
    l2: "Warna merah memiliki arti keuletan dan ketegasan serta keberanian dalam menghadapi berbagai macam kesulitan",
    l3: "Warna hijau memiliki arti pembinaan yang berwawasan sportivitas dan berkelanjutan",
    l4: "Warna emas memiliki arti prestasi, kehormatan, dan cita-cita menuju puncak",
    simbol: "Simbol grafis memiliki arti:",
    s1: "Bentuk kuda catur menggambarkan aspirasi komunitas untuk senantiasa bergerak maju dengan langkah yang cerdas, gesit, dan terukur",
    s2: "Bintang di puncak emblem melambangkan orientasi prestasi dan semangat meraih yang tertinggi",
    s3: "Papan 2×2 berwarna merah, putih, hijau, dan biru merepresentasikan strategi, keadilan aturan main, serta empat warna identitas komunitas",
    s4: "Alas hijau adalah fondasi pembinaan yang menopang seluruh langkah komunitas",
    caption: "Logo resmi Komunitas Catur Indonesia.",
  },
  struktur: {
    judul: "Struktur Pengurus",
    p1: "Komunitas Catur Indonesia menjalankan kegiatan pembinaan dan pertandingan catur yang terintegrasi mulai dari tingkat pemula hingga tingkat lanjut. Dalam kapasitasnya sebagai komunitas catur terverifikasi di Chess.com, maka secara umum fokus komunitas adalah menjalankan kegiatan pengelolaan turnamen dan pembinaan anggota, mempercepat pengembangan program latihan baru, serta menjalankan program-program kerja tahunan.",
    p2: "Sementara itu, sejumlah kegiatan yang sebelumnya merupakan kegiatan-kegiatan utama komunitas akan dijalankan oleh divisi yang telah terbentuk. Divisi ini menjalankan peran, antara lain mendorong terwujudnya operational excellence melalui pengembangan skala dan sinergi masing-masing program, mempercepat pengembangan program dan kapabilitas existing, serta meningkatkan kemampuan dan fleksibilitas dalam kemitraan dan pendanaan yang lebih menguntungkan komunitas. Berikut pemetaan peran divisi pada Komunitas Catur Indonesia:",
    dewanPembina: "Dewan Pembina",
    dewanPenasihat: "Dewan Penasihat",
    ketuaUmum: "Ketua Umum",
    sekretarisJenderal: "Sekretaris Jenderal",
    bendaharaUmum: "Bendahara Umum",
    divisiTurnamen: "Divisi Turnamen",
    divisiPembinaan: "Divisi Pembinaan",
    divisiMedia: "Divisi Media & Humas",
    divisiKeanggotaan: "Divisi Keanggotaan",
    divisiTeknologi: "Divisi Teknologi",
    caption: "Bagan Struktur Pengurus Komunitas Catur Indonesia.",
    p3: "Melalui pembentukan struktur baru komunitas ini, Komunitas Catur Indonesia diharapkan mampu bergerak lebih lincah (agile), fokus, dan lebih cepat dalam mengembangkan kapabilitas anggotanya yang setara dengan kualitas nasional guna mengakselerasi beragam inovasi di luar kegiatan konvensional komunitas, antara lain dalam bidang catur daring, sekolah catur, serta teknologi analisis digital, sehingga komunitas mampu meraih pertumbuhan jumlah anggota yang lebih besar sebagai fondasi menuju komunitas catur terdepan di Indonesia.",
  },
  keanggotaan: {
    judul: "Keanggotaan",
    deskripsi:
      "Daftar anggota yang disinkronkan otomatis dari klub BLUNDER SKUAD di Chess.com.",
    artikel: "Daftar Anggota",
    intro:
      "Daftar ini menggunakan roster publik klub BLUNDER SKUAD di Chess.com. Setelah bergabung ke klub, akun akan muncul otomatis saat Chess.com memperbarui roster (maksimal sekitar 12 jam). Formulir situs hanya dipakai untuk verifikasi dan administrasi tambahan; bukan sumber daftar anggota.",
    jumlah: "Jumlah anggota: {jumlah}",
    sumber: "Sumber anggota:",
    sumberCatatan: "Roster publik Chess.com diperbarui maksimal setiap 12 jam.",
    memuat: "Memuat data dari Chess.com…",
    kosongKlub: "Belum ada anggota yang terbaca dari klub Chess.com.",
    aktivitasKlub: "Aktivitas klub",
    aktivitas: {
      weekly: "Aktif mingguan",
      monthly: "Aktif bulanan",
      all_time: "Aktif sebelumnya",
    },
    kosong1: "Belum ada anggota terdaftar. Silakan ",
    kosong2: "daftar dengan akun Chess.com",
    kosong3: ".",
    no: "No.",
    foto: "Foto",
    nama: "Nama",
    akunHilang: "akun tidak ditemukan",
    gagal: "gagal memuat",
    panggilan: "Panggilan",
    kota: "Kota",
    klub: "Klub",
    kategoriUmur: "Kategori Umur",
    bergabung: "Bergabung",
    wa: "WhatsApp",
    profilJudul: "Profil Anggota",
    tutup: "Tutup",
    lihatProfil: "Klik untuk melihat profil",
    terkenaBan:
      "Akun ini diblokir dari kegiatan komunitas. Periksa keterangan pengurus atau status Chess.com.",
    tingkatanJudul: "Tingkatan Kelompok Rating",
    tingkatanRentang: "Rentang Rating",
    tingkatanKategori: "Kategori Pemain",
    tingkatanPenjelasan: "Penjelasan Kemampuan",
    tingkatanBuka: "Klik untuk membuka daftar tingkatan rating",
    tingkatanTutup: "Klik untuk melipat daftar tingkatan rating",
    tingkatan: {
      beginner: {
        label: "Beginner (Pemula)",
        deskripsi: "Baru memulai perjalanan catur dan memahami pergerakan dasar buah catur.",
      },
      novice: {
        label: "Novice (Pemula Lanjutan)",
        deskripsi: "Mulai mempelajari dasar taktik, mengamankan perwira, dan meminimalkan blunder.",
      },
      intermediate: {
        label: "Intermediate (Menengah)",
        deskripsi: "Mampu menyusun strategi, memahami taktik 2–3 langkah, dan menguasai pembukaan dasar.",
      },
      advanced: {
        label: "Advanced (Mahir)",
        deskripsi: "Memiliki pemahaman posisi yang konsisten, kalkulasi matang, dan jarang melakukan kesalahan fatal.",
      },
      expert: {
        label: "Expert (Ahli)",
        deskripsi: "Keterampilan tingkat tinggi dengan kalkulasi mendalam, manajemen waktu yang ketat, dan ketahanan mental.",
      },
      master: {
        label: "Master Level (Pakar)",
        deskripsi: "Pemain yang sangat kuat dengan kemampuan komprehensif di level turnamen nasional.",
      },
      elite: {
        label: "Elite / Grandmaster",
        deskripsi: "Kelas tertinggi tempat para pecatur profesional dunia bersaing.",
      },
    },
    nextJudul: "Pendaftaran Anggota",
  },
  verifikasi: {
    judul: "Bukti Kepemilikan Akun",
    penjelasan:
      "Buktikan bahwa akun Chess.com yang Anda tulis benar-benar milik Anda. Ini mencegah orang lain mendaftarkan akun Anda, dan mencegah pendaftaran memakai akun milik pemain lain.",
    tombolLogin: "Masuk dengan Chess.com",
    catatanLogin:
      "Anda akan diarahkan ke chess.com untuk masuk. Kata sandi Anda tidak pernah kami lihat maupun simpan.",
    atau: "Atau tanpa login",
    tombolKode: "Verifikasi lewat kode profil",
    memproses: "Memproses…",
    langkah1: "Buka pengaturan profil Chess.com Anda.",
    langkah2: "Isi kolom Location dengan kode ini:",
    langkah3:
      "Simpan perubahan, lalu klik tombol di bawah. Setelah terverifikasi, kode boleh dihapus kembali.",
    bukaPengaturan: "Buka pengaturan Chess.com",
    sudahPasang: "Saya sudah memasang kode",
    memeriksa: "Memeriksa profil…",
    belumTerbaca:
      "Kode belum terbaca. Pastikan sudah tersimpan, lalu coba lagi beberapa saat.",
    isiUsernameDulu: "Isi username Chess.com Anda terlebih dahulu.",
    berhasil: "Kepemilikan akun terverifikasi:",
    ganti: "Ganti akun",
  },
  pendaftaran: {
    judul: "Pendaftaran Anggota",
    parent: "Keanggotaan",
    deskripsi:
      "Lengkapi data administrasi dan verifikasi akun Chess.com Anda setelah bergabung ke klub BLUNDER SKUAD.",
    artikel: "Lengkapi Data Anggota",
    intro:
      "Daftar anggota situs diambil otomatis dari roster klub BLUNDER SKUAD di Chess.com. Isi formulir ini setelah akun Anda ada di klub untuk verifikasi dan administrasi tambahan. Sistem memastikan satu orang hanya menggunakan satu akun, dan akun yang ditutup Chess.com karena pelanggaran fair play tidak dapat mengikuti kegiatan komunitas.",
    klubWajibJudul: "Bergabung ke klub terlebih dahulu",
    klubWajibIsi:
      "Username harus sudah tercatat sebagai anggota BLUNDER SKUAD di Chess.com. Roster Chess.com dapat membutuhkan hingga 12 jam untuk diperbarui.",
    gabungKlub: "Buka klub BLUNDER SKUAD di Chess.com",
    label: "Username Chess.com",
    placeholder: "contoh: hikaru",
    wajib: "Masukkan username Chess.com.",
    memeriksa: "Memeriksa akun Chess.com…",
    daftar: "Daftar",
    nextJudul: "Daftar Keanggotaan",
    linkDaftar: "daftar keanggotaan",

    privasiJudul: "Data pribadi Anda aman",
    privasiIsi:
      "Nama lengkap, nomor HP/WhatsApp, dan nomor DANA hanya disimpan pada catatan pengurus dan tidak pernah ditampilkan di situs. Yang tampil publik hanya nama panggilan, kota, dan statistik Chess.com Anda. Data ini kami gunakan untuk memverifikasi bahwa satu orang hanya memiliki satu keanggotaan.",

    grupAkun: "Akun Chess.com",
    grupDiri: "Data Diri",
    grupKontak: "Kontak & Pembayaran",

    catatanUsername:
      "Gunakan username atau tautan profil chess.com/member/namaanda yang sudah bergabung di BLUNDER SKUAD.",

    labelNama: "Nama Lengkap",
    phNama: "contoh: Budi Santoso",
    catatanNama: "Sesuai identitas resmi, untuk sertifikat dan hadiah turnamen.",

    labelPanggilan: "Nama Panggilan",
    phPanggilan: "contoh: Budi",
    catatanPanggilan: "Dipakai pengurus untuk administrasi dan turnamen.",

    labelLahir: "Tanggal Lahir",
    catatanLahir: "Dipakai untuk menentukan kategori umur turnamen.",
    kategori: "Kategori",
    tahun: "tahun",

    labelKota: "Kota Asal",
    phKota: "contoh: Medan",
    catatanKota: "Untuk pembagian wilayah pada liga antar-komunitas.",

    labelHp: "Nomor HP / WhatsApp",
    phHp: "contoh: 0812-3456-7890",
    catatanHp: "Nomor aktif WhatsApp, untuk undangan turnamen dan verifikasi.",
    terbaca: "Terbaca",

    labelDana: "Nomor DANA",
    phDana: "kosongkan bila sama dengan nomor HP",
    catatanDana: "Untuk pengiriman hadiah turnamen.",

    labelEmail: "Email",
    phEmail: "contoh: budi@email.com",
    catatanEmail: "Untuk buletin bulanan dan pemberitahuan resmi.",

    labelKlub: "Klub / Komunitas Asal",
    phKlub: "contoh: Klub Catur Medan",
    catatanKlub: "Bila Anda sudah tergabung di klub lain.",

    setuju:
      "Saya menyatakan data di atas benar, bahwa ini satu-satunya akun saya di komunitas, dan saya menyetujui Kode Etik Komunitas — termasuk larangan menggunakan bantuan engine.",

    periksaIsian: "Periksa kembali isian yang ditandai merah.",
    galatUsername: "Username Chess.com wajib diisi.",
    galatNama: "Tulis nama lengkap (minimal dua kata).",
    galatPanggilan: "Nama panggilan wajib diisi.",
    galatHp: "Nomor HP/WhatsApp tidak valid. Contoh: 0812-3456-7890.",
    galatDana: "Nomor DANA tidak valid.",
    galatKota: "Kota asal wajib diisi.",
    galatLahir: "Tanggal lahir wajib diisi.",
    galatLahirAneh: "Tanggal lahir tidak masuk akal.",
    galatEmail: "Format email tidak valid.",
    galatSetuju: "Anda harus menyetujui kode etik komunitas.",
  },
  syarat: {
    judul: "Syarat & Ketentuan",
    deskripsi: "Ketentuan administratif keanggotaan Komunitas Catur Indonesia.",
    artikel: "Ketentuan utama",
    l1: "Berusia sekurang-kurangnya 10 tahun, atau didampingi orang tua bila lebih muda.",
    l2: "Mengisi data yang benar pada formulir pendaftaran.",
    l3: "Menyetujui Kode Etik Komunitas.",
    l4: "Keanggotaan ditinjau ulang bila tidak ada aktivitas selama 18 bulan.",
    l5: "Komunitas berhak menolak atau mencabut keanggotaan jika terjadi pelanggaran berat terhadap kode etik.",
    nextJudul: "Kode Etik Komunitas",
  },
  kodeEtik: {
    judul: "Kode Etik Komunitas",
    deskripsi:
      "Fair play, integritas, dan tata krama yang berlaku di papan, daring, maupun ruang diskusi.",
    artikel: "Kebijakan Komunitas",
    nextJudul: "Pertanyaan Umum",
  },
  pertanyaan: {
    judul: "Pertanyaan Umum",
    deskripsi:
      "Jawaban singkat soal biaya, usia, domisili, dan cara mulai bertanding.",
    artikel: "Pertanyaan yang Sering Diajukan",
    q1a: "Apakah ada iuran wajib?",
    q1b: "Tidak ada iuran bulanan wajib. Beberapa event memungut biaya administrasi. Anggota aktif mendapat potongan.",
    q2a: "Apakah anak-anak boleh gabung?",
    q2b: "Boleh. Di bawah 10 tahun perlu pendamping orang tua atau guru pada kegiatan luring.",
    q3a: "Saya tinggal di luar Medan, bisa?",
    q3b: "Bisa. Kelas daring dan turnamen daring terbuka untuk seluruh Indonesia. Chapter daerah menyusul sesuai minat.",
    q4a: "Bagaimana cara daftar?",
    q4b: "Bergabunglah terlebih dahulu ke klub BLUNDER SKUAD di Chess.com. Nama akan masuk otomatis ke daftar anggota saat roster Chess.com diperbarui (maksimal sekitar 12 jam); formulir Pendaftaran Anggota dipakai untuk verifikasi dan administrasi tambahan.",
    q5a: "Bagaimana ikut turnamen pertama?",
    q5b: "Daftar sebagai anggota, lalu ikuti Turnamen Bulanan. Pemula tetap diterima; grup dapat dipisah berdasarkan kekuatan.",
    nextJudul: "Hubungi Kami",
  },
  turnamen: {
    judul: "Turnamen",
    deskripsi:
      "Kalender pertandingan komunitas: bulanan, liga musiman, terbuka, dan antar komunitas.",
    artikel: "Wadah Bertanding",
    p1: "Turnamen adalah cara komunitas mengukur progres latihan. Semua event memakai kode etik fair play, dan hasilnya dicatat di papan peringkat internal.",
    p2: "Kalender pertandingan komunitas terdiri atas:",
    l1: "Swiss lima ronde setiap bulan untuk semua kekuatan.",
    l2: "tiga musim setahun dengan klasemen yang berjalan.",
    l3: "event terbuka, termasuk yang dilaporkan ke sistem rating bila syarat terpenuhi.",
    l4: "pertandingan persahabatan dan liga antar klub.",
    nextJudul: "Turnamen Bulanan",
  },
  turnamenBulanan: {
    judul: "Turnamen Bulanan",
    deskripsi:
      "Turnamen Swiss lima ronde yang diadakan setiap bulan untuk anggota dan tamu.",
    artikel: "Ketentuan ringkas",
    p1: "Turnamen Bulanan memakai sistem Swiss 5 ronde. Tempo standar adalah 15+10 (kilat panjang). Grup dipisah bila peserta lebih dari 40 orang.",
    l1: "Pendaftaran ditutup H-1 pukul 21.00 WIB.",
    l2: "Anggota aktif mendapat potongan biaya administrasi.",
    l3: "Hasil diumumkan di halaman Pengumuman pada malam yang sama.",
    p2: "Jadwal bulan berjalan diumumkan di kanal anggota dan halaman Pengumuman.",
    nextJudul: "Liga Musiman",
  },
  ligaMusiman: {
    judul: "Liga Musiman",
    deskripsi:
      "Tiga musim kompetisi setahun dengan klasemen yang berjalan, bukan event sekali selesai.",
    artikel: "Musim dan format",
    p1: "Liga Musiman dibagi menjadi Musim I (Januari–April), Musim II (Mei–Agustus), dan Musim III (September–Desember). Setiap pemain bermain minimal enam partai agar masuk klasemen resmi.",
    p2: "Poin dihitung 1 untuk menang, ½ untuk remis, 0 untuk kalah. Tie-break memakai Sonneborn-Berger, kemudian hasil pertemuan langsung.",
    p3: "Juara musim mendapat undangan langsung ke final Turnamen Terbuka akhir tahun.",
    nextJudul: "Turnamen Terbuka",
  },
  turnamenTerbuka: {
    judul: "Turnamen Terbuka",
    deskripsi:
      "Event terbuka untuk umum, termasuk format yang dilaporkan ke sistem rating bila syarat terpenuhi.",
    artikel: "Untuk siapa",
    p1: "Turnamen Terbuka menerima peserta dari luar komunitas. Ini wadah mempertemukan pecatur Medan dengan tamu dari kota lain, sekaligus menguji kesiapan anggota di lapangan yang lebih ramai.",
    p2: "Bila jumlah pecatur berating mencukupi, panitia dapat mengajukan laporan rating sesuai ketentuan federasi. Informasi itu selalu tertulis di prospektus masing-masing event.",
    nextJudul: "Liga Antar Komunitas",
  },
  ligaAntar: {
    judul: "Liga Antar Komunitas",
    deskripsi:
      "Pertandingan tim melawan komunitas dan klub lain di Sumatera maupun secara daring.",
    artikel: "Format tim",
    p1: "Liga Antar Komunitas dimainkan dalam format tim 4 papan + 1 cadangan. Satu klub boleh menurunkan lebih dari satu tim bila kuota memungkinkan.",
    p2: "Undangan ke komunitas mitra dikirim Divisi Turnamen. Komunitas yang ingin menantang dapat menulis ke info@komunitascatur.or.id.",
    nextJudul: "Media & Informasi",
  },
  program: {
    judul: "Program Kami",
    deskripsi:
      "Empat pilar pembinaan Komunitas Catur Indonesia: kelas rutin, coaching clinic, simultan, dan sekolah catur.",
    artikel: "Sekilas Program",
    p1: "Program komunitas disusun agar pecatur dari segala usia memiliki jalur belajar yang jelas. Setiap pilar memiliki tujuan sendiri, tetapi saling menopang: kelas membangun dasar, coaching clinic menajamkan, simultan menumbuhkan nyali bertanding, dan sekolah catur merawat regenerasi.",
    p2: "Pilar program yang dijalankan saat ini adalah sebagai berikut:",
    l1: "kelas rutin pemula hingga mahir, daring dan luring.",
    l2: "sesi singkat bersama pelatih dan pecatur bergelar.",
    l3: "pertunjukan simultan dan catur buta untuk anggota dan publik.",
    l4: "program ekstrakurikuler dan kemitraan dengan sekolah.",
    nextJudul: "Kelas & Pelatihan",
  },
  kelas: {
    judul: "Kelas & Pelatihan",
    deskripsi:
      "Kelas rutin komunitas untuk pemula, menengah, dan mahir — daring maupun di sekretariat Medan.",
    artikel: "Jalur belajar",
    p1: "Kelas & Pelatihan adalah tulang punggung pembinaan komunitas. Materi disusun berjenjang supaya anggota baru tidak kebingungan, dan anggota lama tetap punya tantangan.",
    l1a: "Pemula:",
    l1b: "peraturan, notasi, mat dasar, dan etiket bertanding.",
    l2a: "Menengah:",
    l2b: "struktur pembukaan, rencana tengah permainan, dan akhiran rook-pion.",
    l3a: "Mahir:",
    l3b: "analisis partai sendiri, persiapan lawan, dan latihan perhitungan.",
    p2: "Jadwal daring diumumkan setiap minggu di kanal anggota. Kelas luring diadakan di sekretariat Medan pada akhir pekan. Kuota tiap sesi dibatasi agar pendampingan tetap personal.",
    nextJudul: "Coaching Clinic",
  },
  coaching: {
    judul: "Coaching Clinic",
    deskripsi:
      "Sesi intensif bersama pelatih tamu dan pecatur bergelar untuk membedah partai, pembukaan, dan persiapan turnamen.",
    artikel: "Format sesi",
    p1: "Coaching Clinic bukan kelas semester, melainkan sesi pendek 90–120 menit dengan satu tema. Contoh tema: struktur Isolated Queen Pawn, bertahan lawan serangan sayap raja, atau persiapan pertandingan kilat.",
    p2: "Narasumber diundang dari pelatih internal maupun pecatur bergelar yang sedang berkunjung ke Sumatera Utara. Pendaftaran dibuka di kanal anggota paling lambat tiga hari sebelum sesi.",
    p3: "Rekaman sesi daring disimpan di perpustakaan materi digital komunitas dan hanya dapat diakses anggota aktif.",
    nextJudul: "Simultan & Blindfold",
  },
  simultan: {
    judul: "Simultan & Blindfold",
    deskripsi:
      "Pertunjukan simultan dan catur buta sebagai wadah unjuk nyali sekaligus meramaikan publik catur.",
    artikel: "Dua jenis acara",
    p1: "Simultan mempertemukan satu pecatur kuat dengan banyak papan sekaligus. Peserta dari pemula hingga menengah dapat merasakan tekanan partai sungguhan tanpa harus masuk turnamen resmi.",
    p2: "Blindfold (catur buta) ditampilkan pada hari-hari besar komunitas — misalnya hari lahir 10 Desember — sebagai tontonan edukatif. Pemain yang tampil sudah melalui seleksi internal demi menjaga kualitas dan keselamatan sesi.",
    p3: "Usulan menjadi pemberi simultan dapat diajukan ke Divisi Program paling lambat 21 hari sebelum tanggal yang diinginkan.",
    nextJudul: "Sekolah Catur",
  },
  sekolahCatur: {
    judul: "Sekolah Catur",
    deskripsi:
      "Kemitraan dengan sekolah untuk menumbuhkan catur sebagai kegiatan rutin, bukan sekadar lomba sesaat.",
    artikel: "Cara bermitra",
    p1: "Sekolah Catur adalah program pembinaan usia muda di lingkungan formal. Komunitas menyediakan kurikulum 12 pertemuan, pelatih pendamping, dan perangkat papan untuk masa perkenalan.",
    p2: "Sekolah mitra menyediakan ruang, jadwal tetap, dan guru pendamping. Setelah satu semester, siswa yang menonjol diundang ke kelas komunitas dan turnamen pelajar.",
    p3: "Pengajuan kemitraan dikirim ke info@komunitascatur.or.id dengan subjek “Sekolah Catur — [nama sekolah]”.",
    nextJudul: "Turnamen",
  },
  caraBermain: {
    judul: "Cara Bermain Catur",
    deskripsi:
      "Panduan lengkap mengenal bidak, aturan dasar, taktik, strategi, pembukaan, endgame, hingga pola latihan untuk menembus rating master.",
    lead:
      "Panduan ini disusun bertahap: mulai dari pengenalan bidak dan aturan dasar, kemudian taktik, strategi, pembukaan, endgame, dan pola latihan untuk terus menaikkan rating.",
    labelArtikel: "Panduan Lengkap",
    daftarIsi: "Daftar Isi",
    bab: "Bab",
    gagalMuat:
      "Gagal memuat panduan. Periksa koneksi internet Anda, lalu muat ulang halaman ini.",
    kontenHanyaId:
      "Konten panduan ini hanya tersedia dalam Bahasa Indonesia. Alihkan bahasa ke Bahasa Indonesia untuk membacanya secara lengkap.",
    babBidak: "Bidak & Nilainya",
    babDasar: "Aturan & Dasar Permainan",
    babPemula: "Level Pemula",
    babMenengah: "Level Menengah",
    babStrategi: "Strategi & Posisi",
    babLanjut: "Level Lanjut",
    babMaster: "Level Master",
    babPenutup: "Penutup",
  },
  media: {
    judul: "Media & Informasi",
    deskripsi:
      "Kanal resmi berita, pengumuman, galeri, dan buletin Komunitas Catur Indonesia.",
    artikel: "Satu Sumber Resmi",
    p1: "Semua informasi resmi komunitas hanya dikeluarkan melalui kanal ini dan surel info@komunitascatur.or.id. Waspadai undangan turnamen atau pungutan yang tidak tercantum di halaman Pengumuman.",
    p2: "Kanal yang tersedia adalah sebagai berikut:",
    l1: "laporan kegiatan, wawancara, dan liputan turnamen.",
    l2: "foto kegiatan sekretariat, kelas, dan pertandingan.",
    l3: "ringkasan bulanan untuk anggota dan publik.",
    nextJudul: "Berita Komunitas",
  },
  berita: {
    judul: "Berita Komunitas",
    deskripsi: "Liputan kegiatan, hasil pertandingan, dan cerita anggota.",
    artikel: "Terbaru",
    n1a: "12 Agustus 2026 — Turnamen Bulanan Agustus diikuti 64 pecatur.",
    n1b: "Rekor peserta baru untuk event internal. Grup A dimenangkan pecatur junior dari chapter Medan.",
    n2a: "28 Juli 2026 — Coaching clinic struktur pion bersama pelatih tamu.",
    n2b: "Sesi daring 110 menit membahas Isolated Queen Pawn dan cara merencanakan break di pusat.",
    n3a: "10 Desember 2025 — Hari lahir komunitas ke-10 dirayakan dengan simultan.",
    n3b: "Dua puluh papan simultan dibuka untuk pelajar. Acara ditutup pembaruan identitas visual.",
  },
  pengumuman: {
    judul: "Pengumuman",
    deskripsi:
      "Pemberitahuan resmi: jadwal, pendaftaran, dan perubahan ketentuan.",
    artikel: "Berlaku saat ini",
    p1a: "Pendaftaran Turnamen Bulanan September",
    p1b: " dibuka hingga 31 Agustus 2026 pukul 21.00 WIB.",
    p2a: "Libur sekretariat",
    p2b: " pada 17 Agustus 2026. Kelas luring dialihkan ke sesi daring.",
    p3a: "Pemanggilan tim Liga Antar Komunitas",
    p3b: " diumumkan melalui surel anggota pada 20 Agustus 2026.",
    nextJudul: "Galeri",
  },
  galeri: {
    judul: "Galeri",
    deskripsi: "Foto kegiatan kelas, pertandingan, dan perayaan hari lahir komunitas.",
    artikel: "Dokumentasi",
    p1: "Foto dipilih dari arsip Divisi Media. Untuk pemakaian ulang di luar kanal komunitas, hubungi humas terlebih dahulu.",
    img1Alt: "Kegiatan rutin sekretariat Medan",
    img1Caption: "Suasana kegiatan rutin komunitas di sekretariat Medan, 2025.",
    img2Alt: "Tata nilai komunitas",
    img2Caption:
      "Nilai-nilai yang dipegang teguh anggota komunitas dalam setiap pertandingan.",
    img3Alt: "Arsip kegiatan 2024",
    img3Caption: "Dokumentasi kegiatan komunitas, 2024.",
    nextJudul: "Buletin Bulanan",
  },
  buletin: {
    judul: "Buletin Bulanan",
    deskripsi:
      "Ringkasan resmi kegiatan, hasil pertandingan, dan agenda bulan berikutnya.",
    artikel: "Edisi terbaru",
    p1: "Buletin dikirim ke surel anggota aktif setiap tanggal 5. Publik dapat membaca ringkasannya di halaman ini.",
    b1: "Juli 2026",
    b2: "Juni 2026",
    b3: "Mei 2026",
    e1: "Laporan Liga Musim II dan kurikulum kelas pemula baru.",
    e2: "Hasil simultan pelajar dan pembukaan chapter daring.",
    e3: "Wawancara pelatih tamu dan kalender semester depan.",
  },
  hubungi: {
    judul: "Hubungi Kami",
    deskripsi: "Sekretariat Medan, surel resmi, dan formulir pesan.",
    sekretariat: "Sekretariat",
    alamat: "Address: Sekretariat Komunitas Catur Indonesia, Jl. Gatot Subroto No. 11-13, Medan 20152, Sumatera Utara, Indonesia",
    jam: "Jam kunjung luring: Sabtu 09.00–16.00 WIB, kecuali pada tanggal libur yang diumumkan melalui halaman Pengumuman.",
    kirimPesan: "Kirim Pesan",
    terkirim: "Pesan terkirim. Kami membalas pada hari kerja.",
    nama: "Nama",
    surel: "Surel",
    pesan: "Pesan",
    kirim: "Kirim",
  },
  karir: {
    judul: "Karir",
    deskripsi: "Peluang berkontribusi bersama Komunitas Catur Indonesia.",
    artikel: "Posisi Terbuka",
    l1a: "Volunteer Divisi Media",
    l1b: " — mendokumentasikan kegiatan dan mengelola kanal informasi.",
    l2a: "Asisten Pelatih Sekolah Catur",
    l2b: " — mendampingi sesi kelas luring di chapter Medan.",
    l3a: "Staf Sekretariat (paruh waktu)",
    l3b: " — membantu administrasi anggota dan pendaftaran turnamen.",
    kirim:
      "Kirim lamaran ke info@komunitascatur.or.id dengan subjek sesuai posisi yang dituju.",
    nextJudul: "Hubungi Kami",
  },
  pengadaan: {
    judul: "Pengadaan",
    deskripsi: "Informasi pengadaan barang dan jasa Komunitas Catur Indonesia.",
    artikel: "Pengadaan Barang & Jasa",
    p1: "Halaman ini merupakan kerangka awal halaman pengadaan Komunitas Catur Indonesia.",
    p2: "Konten lengkap mengenai pengadaan barang dan jasa akan ditambahkan kemudian.",
  },
  strukturGrupCatur: {
    judul: "Struktur Grup Catur",
    deskripsi:
      "Susunan grup catur komunitas: pengurus, struktur organisasi, dan keanggotaan.",
  },
  pengurus: {
    judul: "Pengurus",
    deskripsi: "Susunan pengurus Komunitas Catur Indonesia.",
    artikel: "Daftar Pengurus",
    p1: "Pengurus menjalankan roda kegiatan komunitas sesuai keputusan Musyawarah Anggota dan membawahi lima divisi fungsional.",
    l1: "Ketua Umum",
    l2: "Sekretaris Jenderal",
    l3: "Bendahara Umum",
    l4: "Kepala Divisi Turnamen",
    l5: "Kepala Divisi Pembinaan",
    l6: "Kepala Divisi Media & Humas",
    l7: "Kepala Divisi Keanggotaan",
    l8: "Kepala Divisi Teknologi",
  },
  strukturOrganisasiCatur: {
    judul: "Struktur Organisasi Catur",
    deskripsi: "Bagan struktur organisasi Komunitas Catur Indonesia.",
    artikel: "Bagan Organisasi",
    p1: "Berikut bagan struktur organisasi Komunitas Catur Indonesia berdasarkan keputusan Musyawarah Anggota.",
  },
  keberlanjutan: {
    judul: "Keberlanjutan",
    deskripsi: "Aturan, nilai, dan komitmen yang menjaga komunitas tetap sehat.",
    artikel: "Landasan Komunitas",
    l1a: "Syarat & Ketentuan",
    l1b: " — ketentuan umum yang berlaku bagi seluruh anggota.",
    l2a: "Kode Etik Komunitas",
    l2b: " — norma perilaku yang dijunjung bersama.",
    l3a: "Pertanyaan Umum",
    l3b: " — jawaban atas pertanyaan yang sering diajukan.",
    nextJudul: "Syarat & Ketentuan",
  },
  t404: {
    judul: "Halaman tidak ditemukan",
    deskripsi: "Alamat yang Anda tuju tidak ada di situs ini.",
    kembali: "Kembali",
    p1: "Periksa kembali tautan, atau kembali ke ",
    p2: "beranda",
    p3: ".",
  },
};

export const EN = {
  common: {
    home: "Home",
    id: "ID",
    en: "EN",
    bahasaIndonesia: "Bahasa Indonesia",
    english: "English",
    namaKomunitas: "Indonesia Chess Community",
    selanjutnya: "Next",
    daftarAnggota: "Register as Member",
    alamat: "Address",
    surel: "Email",
    pilihBahasa: "Choose language",
  },
  nav: {
    tentangKami: "About Us",
    programKami: "Our Programs",
    turnamen: "Tournaments",
    mediaDanInformasi: "Media & Information",
    keanggotaan: "Membership",
    sekilasKomunitas: "Community Overview",
    tonggakSejarah: "Historical Milestones",
    visiMisiNilai: "Vision, Mission & Values",
    maknaLogo: "Logo Meaning",
    strukturPengurus: "Board Structure",
    strukturGrupCatur: "Chess Group Structure",
    pengurus: "Board",
    strukturOrganisasiCatur: "Organization Structure",
    kelasPelatihan: "Classes & Training",
    coachingClinic: "Coaching Clinic",
    simultanBlindfold: "Simultaneous & Blindfold",
    sekolahCatur: "Chess School",
    caraBermainCatur: "How to Play Chess",
    turnamenBulanan: "Monthly Tournament",
    ligaMusiman: "Seasonal League",
    turnamenTerbuka: "Open Tournament",
    ligaAntarKomunitas: "Inter-Community League",
    beritaKomunitas: "Community News",
    galeri: "Gallery",
    buletinBulanan: "Monthly Bulletin",
    pengumuman: "Announcements",
    pendaftaranAnggota: "Member Registration",
    syaratKetentuan: "Terms & Conditions",
    kodeEtik: "Community Code of Ethics",
    pertanyaanUmum: "Frequently Asked Questions",
    hubungiKami: "Contact Us",
    karir: "Careers",
    beranda: "Home",
    peringkat: "Ratings",
    pengadaan: "Procurement",
    keberlanjutan: "Sustainability",
  },
  header: {
    close: "close",
    closeSearch: "close search",
    searchButton: "search button",
    menu: "menu",
    search: "search",
    expand: "expand {title}",
  },
  search: {
    placeholder: "Type a search keyword",
    enter: "Press Enter to search",
    noResults: "No results found for “{query}”.",
  },
  footer: {
    pengumuman: "Announcements",
    beritaKomunitas: "Community News",
    pendaftaranTurnamen: "Tournament Registration",
    pengumumanLink: "Announcements",
    jadwalLiga: "League Schedule",
    musyawarahAnggota: "Member Assembly",
    volunteer: "Volunteer",
    network: "Network",
    chapterSumut: "North Sumatra Chapter",
    chapterJakarta: "DKI Jakarta Chapter",
    chapterJabar: "West Java Chapter",
    chapterJatim: "East Java Chapter",
    chapterSulsel: "South Sulawesi Chapter",
    akademiCatur: "Chess Academy",
    tools: "Tools",
    papanInteraktif: "Interactive Board",
    pendaftaranAnggota: "Member Registration",
    kodeEtik: "Community Code of Ethics",
    keterbukaanInformasi: "Information Disclosure",
    kontakKami: "Contact Us",
    sistemPengaduan: "Complaint System",
    alamat: "Address: Indonesia Chess Community Secretariat, Jl. Gatot Subroto No. 11-13, Medan 20152, North Sumatra, Indonesia",
    copyright: "© Copyright Indonesia Chess Community 2025. All Rights Reserved.",
    privasi: "Privacy Policy",
    penipuan: "Beware of Scams",
  },
  hero: {
    tentangKami: "About Us",
    deskripsi:
      "Explore the history, vision, and mission of our community that form the foundation of our activities, the logo philosophy, and the board structure supporting the development of chess in Indonesia.",
  },
  sticky: {
    sekilasKomunitas: "Community Overview",
    tonggakSejarah: "Historical Milestones",
    visiMisiNilai: "Vision, Mission & Values",
    maknaLogo: "Logo Meaning",
    strukturPengurus: "Board Structure",
  },
  bagian: {
    selanjutnya: "Next",
    dewanPengurus: "Board of Directors and Board of Trustees",
  },
  sekilas: {
    judul: "Community Overview",
    p1: "The Indonesia Chess Community firmly upholds its commitment to provide a space to play and learn chess and to develop youth coaching in support of building self-reliant national chess achievements. Carrying the mandate as a verified chess community on Chess.com since its founding on December 10, 2015, the community now plays a highly strategic role overseeing five Divisions working in chess development: the Tournament Division running internal and external competitions, the Development Division running classes and training, the Media & PR Division managing publications, the Membership Division managing member administration, and the Technology Division managing the community's online platform.",
    p2: "The important role borne by this community also marks a new milestone in its journey, following the real contributions made over more than a decade of providing a competition platform that has energized chess players from across Indonesia.",
    p3: "This capable community is built on a solid foundation and a long history of guiding the realization of national chess development. Records show that the Indonesia Chess Community's existence dates back to around 2014, when a group of players in Medan began gathering regularly to play blitz chess at a coffee shop. The group was officially established as a community on December 10, 2015, which is still celebrated today as the community's birthday.",
    p4: "In 2018, the community officially formed a club on Chess.com as the basis for online play for all members. Subsequently, the community's role grew more strategic after 2020 when it initiated a free online chess class program for students during the pandemic.",
    p5: "Following the Member Assembly agreement of June 18, 2023, the community restructured its organization into a management structure with functional divisions. On December 10, 2024, the community renewed its visual identity with a knight logo on blue, red, and green bases reflecting dynamism and a commitment to development.",
    p6: "Even after the evolution experienced over that decade, the community is committed to continuing its spirit of sustainable transformation to refine its path toward becoming Indonesia's leading chess community, supported by an organization that is increasingly agile, adaptable, and focused on broader development.",
    imgAlt: "Routine community activities at the Medan secretariat",
    imgCaption: "Routine community activities at the Medan secretariat, 2025.",
  },
  tonggak: {
    judul: "Historical Milestones",
    t1: "The Journey 2015-2016",
    p1a: "Records show that the Indonesia Chess Community's existence dates back to around 2014, when a group of Medan chess players gathered regularly at a coffee shop to play blitz chess. The group was officially established as a community named Komunitas Catur Indonesia on December 10, 2015, which is still celebrated today as the community's birthday.",
    p1b: "During its first year, the community strengthened its existence as the only integrated chess community in Medan, accommodating players from various backgrounds, from students to working professionals.",
    t2: "The Journey 2016-2017",
    p2a: "In its second year, the community maximized the growth of its activities and contributed to regional chess development. During this period, the community's existence as a driver of local chess began to be recognized by PERCASI North Sumatra. This rapid growth was partly thanks to tournament collaboration with other chess communities across Sumatra.",
    p2b: "In 2017, the community officially formed a club on Chess.com as the basis for online play for all members, marking the beginning of an era of regular online matches.",
    t3: "The Journey 2018-2019",
    p3a: "During this period, the community for the first time organized a city-scale open tournament under international regulation standards. Over these two years, the community increased the frequency of internal tournaments to twice a month.",
    p3b: "In early 2019, the community began laying the groundwork for youth development through free chess classes for students, and built a library of digital training materials.",
    t4: "The Journey 2020-2021",
    p4a: "During this time, the community faced the pandemic. With the support of its administrators, organizational and online platform improvements were made to keep the community active. During this period, the community managed to run weekly online tournaments attended by members from various cities across Indonesia.",
    p4b: "The community also initiated a free online chess class program for students amid the pandemic, which became the forerunner of the Community Chess Academy.",
    t5: "The Journey 2022-2023",
    p5a: "During this period, the community sought to develop youth chess coaching. Over these two years, the community collaborated with schools in Medan through chess extracurriculars and inter-school competitions.",
    p5b: "The community demonstrated its commitment to sportsmanship-oriented activities by establishing a new function, the Ethics and Fair Play Committee, in 2022. The community also began implementing a member performance evaluation program to increase member engagement in training.",
    t6: "The Journey 2024-2025",
    p6a: "During this period, specifically in 2024, the community restructured its organization into a management structure with functional divisions to support operational efficiency. On December 10, 2024, the community renewed its visual identity with a new logo on blue, red, and green bases reflecting dynamism and a commitment to development.",
    p6b: "The community also underwent a transformation on July 20, 2025, through an overhaul of its training curriculum integrating digital analysis and training alongside titled players, as part of its target of reaching 5,000 active members.",
  },
  visimisi: {
    visi: "Vision",
    visiLead:
      "To become a chess community that prioritizes sportsmanship, achievement, and development.",
    visiP1:
      "The Indonesia Chess Community is committed to becoming a national-scale chess community that not only carries out its activities on a strong organizational foundation, but also plays a strategic role in supporting the development of Indonesian chess, particularly in strengthening sportsmanship, ensuring the availability of competition platforms, and encouraging sustainable development.",
    visiL1: "Sportsmanship: strengthening a culture of fair play and integrity in every match.",
    visiL2: "Achievement: creating a competitive environment to guarantee the emergence of nationally and internationally successful players.",
    visiL3: "Development: encouraging youth talent development as a strategic step in sustaining the regeneration of Indonesian chess.",
    misi: "Mission",
    misiLead:
      "To provide a place to play and learn chess through innovative programs that add value for members and the wider community.",
    misiP1:
      "The mission to provide a place to play and learn chess through innovative programs that add value for members and the community reflects the community's commitment to delivering reliable, sustainable activities relevant to the dynamics of national and global chess development. These efforts are carried out through a program focus on a dual-growth strategy: Maximizing Competitive Play and Building Grassroots Development. The Maximizing Competitive Play pillar focuses on increasing internal tournament frequency, strengthening seasonal leagues, reinforcing friendly matches between communities, and developing training infrastructure. Meanwhile, the Building Grassroots Development pillar focuses on developing beginner classes, an online training ecosystem, a chess school program, and digital training technology.",
    tataNilai: "Values",
    nilaiImgAlt: "Community values",
    nilaiImgCaption:
      "The values upheld by community members in every match.",
  },
  maknaLogo: {
    judul: "Logo Meaning",
    intro: "The meaning of the Indonesia Chess Community logo is:",
    l1: "Blue represents reliability, trustworthiness, and responsibility",
    l2: "Red represents tenacity, firmness, and courage in facing various difficulties",
    l3: "Green represents development grounded in sportsmanship and sustainability",
    l4: "Gold represents achievement, honor, and the aspiration to reach the top",
    simbol: "The graphic symbol means:",
    s1: "The chess knight shape reflects the community's aspiration to always move forward with smart, agile, and measured steps",
    s2: "The star atop the emblem symbolizes an achievement orientation and the spirit of reaching the highest",
    s3: "The 2×2 board in red, white, green, and blue represents strategy, fair rules of play, and the community's four identity colors",
    s4: "The green base is the foundation of development that supports every step of the community",
    caption: "The official logo of the Indonesia Chess Community.",
  },
  struktur: {
    judul: "Board Structure",
    p1: "The Indonesia Chess Community runs integrated chess development and competition activities from beginner to advanced levels. In its capacity as a verified chess community on Chess.com, the community's general focus is managing tournaments and member development, accelerating the development of new training programs, and carrying out annual work programs.",
    p2: "Meanwhile, a number of activities that were previously core community activities will be run by the established divisions. These divisions play a role, among others, in driving operational excellence through the development of scale and synergy across programs, accelerating the development of existing programs and capabilities, and increasing capacity and flexibility in partnerships and funding that are more beneficial to the community. The following is a mapping of the division roles in the Indonesia Chess Community:",
    dewanPembina: "Board of Trustees",
    dewanPenasihat: "Board of Advisors",
    ketuaUmum: "Chairperson",
    sekretarisJenderal: "Secretary General",
    bendaharaUmum: "Treasurer",
    divisiTurnamen: "Tournament Division",
    divisiPembinaan: "Development Division",
    divisiMedia: "Media & PR Division",
    divisiKeanggotaan: "Membership Division",
    divisiTeknologi: "Technology Division",
    caption: "Organization chart of the Indonesia Chess Community.",
    p3: "Through this new organizational structure, the Indonesia Chess Community is expected to move more agilely, more focused, and faster in developing member capabilities equal to national quality, to accelerate various innovations beyond conventional community activities, including in online chess, chess schools, and digital analysis technology, so that the community can achieve greater membership growth as the foundation toward becoming Indonesia's leading chess community.",
  },
  keanggotaan: {
    judul: "Membership",
    deskripsi:
      "Member list automatically synchronized from the BLUNDER SKUAD club on Chess.com.",
    artikel: "Member List",
    intro:
      "This list uses the public roster of the BLUNDER SKUAD club on Chess.com. After joining the club, an account appears automatically when Chess.com refreshes the roster (up to about 12 hours). The website form is only for verification and additional administration; it is not the source of the member list.",
    jumlah: "Total members: {jumlah}",
    sumber: "Member source:",
    sumberCatatan: "The public Chess.com roster refreshes at most every 12 hours.",
    memuat: "Loading data from Chess.com…",
    kosongKlub: "No members could be read from the Chess.com club yet.",
    aktivitasKlub: "Club activity",
    aktivitas: {
      weekly: "Weekly active",
      monthly: "Monthly active",
      all_time: "Previously active",
    },
    kosong1: "No members registered yet. Please ",
    kosong2: "register with your Chess.com account",
    kosong3: ".",
    no: "No.",
    foto: "Photo",
    nama: "Name",
    akunHilang: "account not found",
    gagal: "failed to load",
    panggilan: "Nickname",
    kota: "City",
    klub: "Club",
    kategoriUmur: "Age Category",
    bergabung: "Joined",
    wa: "WhatsApp",
    profilJudul: "Member Profile",
    tutup: "Close",
    lihatProfil: "Click to view profile",
    terkenaBan:
      "This account is barred from community activities. Check the committee note or Chess.com status.",
    tingkatanJudul: "Rating Group Levels",
    tingkatanRentang: "Rating Range",
    tingkatanKategori: "Player Category",
    tingkatanPenjelasan: "Ability Description",
    tingkatanBuka: "Click to open the rating levels",
    tingkatanTutup: "Click to collapse the rating levels",
    tingkatan: {
      beginner: {
        label: "Beginner",
        deskripsi: "Just starting the chess journey and learning the basic movement of the pieces.",
      },
      novice: {
        label: "Novice",
        deskripsi: "Starting to learn basic tactics, protect pieces, and reduce blunders.",
      },
      intermediate: {
        label: "Intermediate",
        deskripsi: "Able to build plans, calculate two to three moves, and understand basic openings.",
      },
      advanced: {
        label: "Advanced",
        deskripsi: "Shows consistent positional understanding, mature calculation, and rarely makes fatal errors.",
      },
      expert: {
        label: "Expert",
        deskripsi: "High-level skill with deep calculation, strict time management, and mental resilience.",
      },
      master: {
        label: "Master Level",
        deskripsi: "A very strong player with comprehensive ability at national tournament level.",
      },
      elite: {
        label: "Elite / Grandmaster",
        deskripsi: "The highest class, where professional chess players compete at the world level.",
      },
    },
    nextJudul: "Member Registration",
  },
  verifikasi: {
    judul: "Account Ownership Proof",
    penjelasan:
      "Prove that the Chess.com account you entered really belongs to you. This prevents other people from registering your account, and prevents anyone registering with someone else's account.",
    tombolLogin: "Sign in with Chess.com",
    catatanLogin:
      "You will be redirected to chess.com to sign in. We never see or store your password.",
    atau: "Or without signing in",
    tombolKode: "Verify via profile code",
    memproses: "Processing…",
    langkah1: "Open your Chess.com profile settings.",
    langkah2: "Set the Location field to this code:",
    langkah3:
      "Save your changes, then click the button below. Once verified, you may remove the code again.",
    bukaPengaturan: "Open Chess.com settings",
    sudahPasang: "I have added the code",
    memeriksa: "Checking profile…",
    belumTerbaca:
      "The code was not found yet. Make sure it is saved, then try again shortly.",
    isiUsernameDulu: "Please enter your Chess.com username first.",
    berhasil: "Account ownership verified:",
    ganti: "Change account",
  },
  pendaftaran: {
    judul: "Member Registration",
    parent: "Membership",
    deskripsi:
      "Complete your administrative details and verify your Chess.com account after joining the BLUNDER SKUAD club.",
    artikel: "Complete Member Details",
    intro:
      "The site's member list is automatically taken from the BLUNDER SKUAD club roster on Chess.com. Complete this form after your account is in the club for verification and additional administration. The system ensures one person uses one account, and accounts closed by Chess.com for fair play violations cannot take part in community activities.",
    klubWajibJudul: "Join the club first",
    klubWajibIsi:
      "Your username must already be a BLUNDER SKUAD member on Chess.com. The Chess.com roster can take up to 12 hours to refresh.",
    gabungKlub: "Open the BLUNDER SKUAD club on Chess.com",
    label: "Chess.com Username",
    placeholder: "e.g.: hikaru",
    wajib: "Enter your Chess.com username.",
    memeriksa: "Checking Chess.com account…",
    daftar: "Register",
    nextJudul: "Membership List",
    linkDaftar: "membership list",

    privasiJudul: "Your personal data is safe",
    privasiIsi:
      "Your full name, phone/WhatsApp number, and DANA number are stored only in the committee's records and are never shown on the site. Only your nickname, city, and Chess.com statistics are public. We use this data to verify that each person holds only one membership.",

    grupAkun: "Chess.com Account",
    grupDiri: "Personal Details",
    grupKontak: "Contact & Payment",

    catatanUsername:
      "Use the username or chess.com/member/yourname profile link that has joined BLUNDER SKUAD.",

    labelNama: "Full Name",
    phNama: "e.g.: Budi Santoso",
    catatanNama: "As per official ID, for certificates and tournament prizes.",

    labelPanggilan: "Nickname",
    phPanggilan: "e.g.: Budi",
    catatanPanggilan: "Used by the committee for administration and tournaments.",

    labelLahir: "Date of Birth",
    catatanLahir: "Used to determine your tournament age category.",
    kategori: "Category",
    tahun: "years old",

    labelKota: "City of Origin",
    phKota: "e.g.: Medan",
    catatanKota: "For regional grouping in the inter-community league.",

    labelHp: "Phone / WhatsApp Number",
    phHp: "e.g.: 0812-3456-7890",
    catatanHp:
      "An active WhatsApp number, for tournament invitations and verification.",
    terbaca: "Read as",

    labelDana: "DANA Number",
    phDana: "leave blank if same as phone number",
    catatanDana: "For sending tournament prizes.",

    labelEmail: "Email",
    phEmail: "e.g.: budi@email.com",
    catatanEmail: "For the monthly bulletin and official announcements.",

    labelKlub: "Club / Home Community",
    phKlub: "e.g.: Medan Chess Club",
    catatanKlub: "If you already belong to another club.",

    setuju:
      "I declare that the data above is correct, that this is my only account in the community, and I agree to the Community Code of Ethics — including the prohibition on using engine assistance.",

    periksaIsian: "Please review the fields marked in red.",
    galatUsername: "Chess.com username is required.",
    galatNama: "Enter your full name (at least two words).",
    galatPanggilan: "Nickname is required.",
    galatHp: "Invalid phone/WhatsApp number. Example: 0812-3456-7890.",
    galatDana: "Invalid DANA number.",
    galatKota: "City of origin is required.",
    galatLahir: "Date of birth is required.",
    galatLahirAneh: "That date of birth is not plausible.",
    galatEmail: "Invalid email format.",
    galatSetuju: "You must agree to the community code of ethics.",
  },
  syarat: {
    judul: "Terms & Conditions",
    deskripsi:
      "Administrative requirements for Indonesia Chess Community membership.",
    artikel: "Key Provisions",
    l1: "Be at least 10 years old, or accompanied by a parent if younger.",
    l2: "Provide accurate data on the registration form.",
    l3: "Agree to the Community Code of Ethics.",
    l4: "Membership is reviewed if there is no activity for 18 months.",
    l5: "The community reserves the right to reject or revoke membership in the event of serious violations of the code of ethics.",
    nextJudul: "Community Code of Ethics",
  },
  kodeEtik: {
    judul: "Community Code of Ethics",
    deskripsi:
      "Fair play, integrity, and etiquette that apply at the board, online, and in discussion spaces.",
    artikel: "Community Policy",
    nextJudul: "Frequently Asked Questions",
  },
  pertanyaan: {
    judul: "Frequently Asked Questions",
    deskripsi:
      "Short answers about fees, age, location, and how to start competing.",
    artikel: "Frequently Asked Questions",
    q1a: "Is there a mandatory fee?",
    q1b: "There is no mandatory monthly fee. Some events charge an administrative fee. Active members receive a discount.",
    q2a: "Can children join?",
    q2b: "Yes. Under 10 years old requires a parent or teacher companion at offline activities.",
    q3a: "I live outside Medan, can I join?",
    q3b: "Yes. Online classes and online tournaments are open to all of Indonesia. Regional chapters will follow based on interest.",
    q4a: "How do I register?",
    q4b: "First join the BLUNDER SKUAD club on Chess.com. Your name is automatically added to the member list when Chess.com refreshes its roster (up to about 12 hours); the Member Registration form is for verification and additional administration.",
    q5a: "How do I join my first tournament?",
    q5b: "Register as a member, then join the Monthly Tournament. Beginners are still accepted; groups can be separated by strength.",
    nextJudul: "Contact Us",
  },
  turnamen: {
    judul: "Tournaments",
    deskripsi:
      "Community competition calendar: monthly, seasonal league, open, and inter-community.",
    artikel: "Competition Platform",
    p1: "Tournaments are how the community measures training progress. All events follow the fair play code of ethics, and results are recorded on the internal leaderboard.",
    p2: "The community competition calendar consists of:",
    l1: "a five-round Swiss tournament every month for all strengths.",
    l2: "three seasons a year with a running standings table.",
    l3: "open events, including those reported to the rating system when requirements are met.",
    l4: "friendly matches and inter-club leagues.",
    nextJudul: "Monthly Tournament",
  },
  turnamenBulanan: {
    judul: "Monthly Tournament",
    deskripsi:
      "A five-round Swiss tournament held every month for members and guests.",
    artikel: "Brief Rules",
    p1: "The Monthly Tournament uses a 5-round Swiss system. The standard time control is 15+10 (long blitz). Groups are split if there are more than 40 participants.",
    l1: "Registration closes the day before at 9:00 PM WIB.",
    l2: "Active members receive a discount on the administrative fee.",
    l3: "Results are announced on the Announcements page the same evening.",
    p2: "The current month's schedule is announced on the member channel and the Announcements page.",
    nextJudul: "Seasonal League",
  },
  ligaMusiman: {
    judul: "Seasonal League",
    deskripsi:
      "Three competition seasons a year with a running standings table, not a one-off event.",
    artikel: "Seasons and Format",
    p1: "The Seasonal League is divided into Season I (January–April), Season II (May–August), and Season III (September–December). Each player plays a minimum of six games to enter the official standings.",
    p2: "Points are counted as 1 for a win, ½ for a draw, and 0 for a loss. Tie-breaks use Sonneborn-Berger, then head-to-head results.",
    p3: "Season champions receive a direct invitation to the Open Tournament final at year's end.",
    nextJudul: "Open Tournament",
  },
  turnamenTerbuka: {
    judul: "Open Tournament",
    deskripsi:
      "Open events for the general public, including formats reported to the rating system when requirements are met.",
    artikel: "Who It's For",
    p1: "The Open Tournament accepts participants from outside the community. It is a platform to bring Medan chess players together with guests from other cities, while testing members' readiness on a busier stage.",
    p2: "When the number of rated players is sufficient, the organizers may submit a rating report in accordance with federation regulations. This information is always stated in each event's prospectus.",
    nextJudul: "Inter-Community League",
  },
  ligaAntar: {
    judul: "Inter-Community League",
    deskripsi:
      "Team matches against other communities and clubs in Sumatra and online.",
    artikel: "Team Format",
    p1: "The Inter-Community League is played in a team format of 4 boards + 1 reserve. A club may field more than one team when the quota allows.",
    p2: "Invitations to partner communities are sent by the Tournament Division. Communities wishing to issue a challenge can write to info@komunitascatur.or.id.",
    nextJudul: "Media & Information",
  },
  program: {
    judul: "Our Programs",
    deskripsi:
      "The four pillars of Indonesia Chess Community development: regular classes, coaching clinics, simulcasts, and chess school.",
    artikel: "Program Overview",
    p1: "Community programs are designed so players of all ages have a clear learning path. Each pillar has its own goal but supports the others: classes build foundations, coaching clinics sharpen skills, simulcasts build competitive courage, and the chess school nurtures regeneration.",
    p2: "The program pillars currently in operation are as follows:",
    l1: "regular classes from beginner to advanced, online and offline.",
    l2: "short sessions with coaches and titled players.",
    l3: "simultaneous and blindfold exhibitions for members and the public.",
    l4: "extracurricular programs and partnerships with schools.",
    nextJudul: "Classes & Training",
  },
  kelas: {
    judul: "Classes & Training",
    deskripsi:
      "Regular community classes for beginner, intermediate, and advanced players — online and at the Medan secretariat.",
    artikel: "Learning Path",
    p1: "Classes & Training is the backbone of community development. Materials are arranged in levels so new members are not confused, and long-time members still have challenges.",
    l1a: "Beginner:",
    l1b: "rules, notation, basic mates, and competition etiquette.",
    l2a: "Intermediate:",
    l2b: "opening structures, middlegame planning, and rook-pawn endgames.",
    l3a: "Advanced:",
    l3b: "own game analysis, opponent preparation, and calculation training.",
    p2: "The online schedule is announced weekly on the member channel. Offline classes are held at the Medan secretariat on weekends. Each session's quota is limited to keep coaching personal.",
    nextJudul: "Coaching Clinic",
  },
  coaching: {
    judul: "Coaching Clinic",
    deskripsi:
      "Intensive sessions with guest coaches and titled players to analyze games, openings, and tournament preparation.",
    artikel: "Session Format",
    p1: "A Coaching Clinic is not a semester course, but a short 90–120 minute session with a single theme. Example themes: Isolated Queen Pawn structures, defending against kingside attacks, or blitz match preparation.",
    p2: "Speakers are invited from internal coaches as well as titled players visiting North Sumatra. Registration opens on the member channel no later than three days before the session.",
    p3: "Recordings of online sessions are kept in the community's digital material library and are only accessible to active members.",
    nextJudul: "Simultaneous & Blindfold",
  },
  simultan: {
    judul: "Simultaneous & Blindfold",
    deskripsi:
      "Simultaneous and blindfold exhibitions as a stage to show courage and enliven the chess public.",
    artikel: "Two Types of Events",
    p1: "A simul pits one strong player against many boards at once. Participants from beginner to intermediate can feel the pressure of a real match without entering an official tournament.",
    p2: "Blindfold is featured on major community days — such as the December 10 anniversary — as an educational show. Featured players have passed internal selection to maintain session quality and safety.",
    p3: "Proposals to become a simul giver can be submitted to the Program Division no later than 21 days before the desired date.",
    nextJudul: "Chess School",
  },
  sekolahCatur: {
    judul: "Chess School",
    deskripsi:
      "Partnerships with schools to grow chess as a regular activity, not just a one-off competition.",
    artikel: "How to Partner",
    p1: "The Chess School is a youth development program in a formal environment. The community provides a 12-session curriculum, accompanying coaches, and board equipment for the introductory period.",
    p2: "Partner schools provide the space, a fixed schedule, and accompanying teachers. After one semester, outstanding students are invited to community classes and student tournaments.",
    p3: "Partnership applications are sent to info@komunitascatur.or.id with the subject “Chess School — [school name]”.",
    nextJudul: "Tournaments",
  },
  caraBermain: {
    judul: "How to Play Chess",
    deskripsi:
      "A complete guide to the pieces, basic rules, tactics, strategy, openings, endgames, and training routines for reaching master-level rating.",
    lead:
      "This guide is arranged step by step: from the pieces and basic rules, through tactics, strategy, openings, and endgames, to training routines for steadily improving your rating.",
    labelArtikel: "Complete Guide",
    daftarIsi: "Table of Contents",
    bab: "Chapter",
    gagalMuat:
      "Failed to load the guide. Check your internet connection, then reload this page.",
    kontenHanyaId:
      "This guide is currently only available in Indonesian. Switch the language to Bahasa Indonesia to read it in full.",
    babBidak: "Pieces & Their Values",
    babDasar: "Rules & Fundamentals",
    babPemula: "Beginner Level",
    babMenengah: "Intermediate Level",
    babStrategi: "Strategy & Positional Play",
    babLanjut: "Advanced Level",
    babMaster: "Master Level",
    babPenutup: "Closing",
  },
  media: {
    judul: "Media & Information",
    deskripsi:
      "The official channels for Indonesia Chess Community news, announcements, gallery, and bulletin.",
    artikel: "One Official Source",
    p1: "All official community information is released only through this channel and the email info@komunitascatur.or.id. Beware of tournament invitations or collections not listed on the Announcements page.",
    p2: "The available channels are as follows:",
    l1: "activity reports, interviews, and tournament coverage.",
    l2: "photos of secretariat, class, and match activities.",
    l3: "monthly summaries for members and the public.",
    nextJudul: "Community News",
  },
  berita: {
    judul: "Community News",
    deskripsi: "Coverage of activities, match results, and member stories.",
    artikel: "Latest",
    n1a: "August 12, 2026 — August Monthly Tournament followed by 64 players.",
    n1b: "A new participation record for an internal event. Group A was won by a junior player from the Medan chapter.",
    n2a: "July 28, 2026 — Pawn structure coaching clinic with a guest coach.",
    n2b: "A 110-minute online session covering the Isolated Queen Pawn and how to plan a central break.",
    n3a: "December 10, 2025 — The community's 10th anniversary celebrated with a simul.",
    n3b: "Twenty simul boards were opened to students. The event closed with the visual identity renewal.",
  },
  pengumuman: {
    judul: "Announcements",
    deskripsi:
      "Official notices: schedules, registration, and changes to terms.",
    artikel: "Currently in Effect",
    p1a: "Registration for the September Monthly Tournament",
    p1b: " is open until August 31, 2026 at 9:00 PM WIB.",
    p2a: "Secretariat holiday",
    p2b: " on August 17, 2026. Offline classes are moved to online sessions.",
    p3a: "Inter-Community League team call-ups",
    p3b: " will be announced via member email on August 20, 2026.",
    nextJudul: "Gallery",
  },
  galeri: {
    judul: "Gallery",
    deskripsi: "Photos of classes, matches, and community anniversary celebrations.",
    artikel: "Documentation",
    p1: "Photos are selected from the Media Division archive. For reuse outside the community channels, contact public relations first.",
    img1Alt: "Routine Medan secretariat activities",
    img1Caption: "Routine community activities at the Medan secretariat, 2025.",
    img2Alt: "Community values",
    img2Caption: "The values upheld by community members in every match.",
    img3Alt: "2024 activity archive",
    img3Caption: "Documentation of community activities, 2024.",
    nextJudul: "Monthly Bulletin",
  },
  buletin: {
    judul: "Monthly Bulletin",
    deskripsi:
      "Official summary of activities, match results, and next month's agenda.",
    artikel: "Latest Edition",
    p1: "The bulletin is sent to active members' email every month on the 5th. The public can read its summary on this page.",
    b1: "July 2026",
    b2: "June 2026",
    b3: "May 2026",
    e1: "Season II League report and the new beginner class curriculum.",
    e2: "Student simul results and the launch of the online chapter.",
    e3: "Interview with the guest coach and next semester's calendar.",
  },
  hubungi: {
    judul: "Contact Us",
    deskripsi: "Medan secretariat, official email, and message form.",
    sekretariat: "Secretariat",
    alamat: "Address: Indonesia Chess Community Secretariat, Jl. Gatot Subroto No. 11-13, Medan 20152, North Sumatra, Indonesia",
    jam: "Offline visiting hours: Saturday 9:00 AM–4:00 PM WIB, except on holidays announced on the Announcements page.",
    kirimPesan: "Send a Message",
    terkirim: "Message sent. We reply on business days.",
    nama: "Name",
    surel: "Email",
    pesan: "Message",
    kirim: "Send",
  },
  karir: {
    judul: "Careers",
    deskripsi: "Opportunities to contribute with the Indonesian Chess Community.",
    artikel: "Open Positions",
    l1a: "Media Division Volunteer",
    l1b: " — document activities and manage information channels.",
    l2a: "Chess School Assistant Coach",
    l2b: " — assist offline classes at the Medan chapter.",
    l3a: "Secretariat Staff (part-time)",
    l3b: " — help with member administration and tournament registration.",
    kirim:
      "Send your application to info@komunitascatur.or.id with the position as the subject.",
    nextJudul: "Contact Us",
  },
  pengadaan: {
    judul: "Procurement",
    deskripsi: "Goods and services procurement information for the Indonesian Chess Community.",
    artikel: "Goods & Services Procurement",
    p1: "This page is the initial framework for the Indonesian Chess Community's procurement page.",
    p2: "Complete content on the procurement of goods and services will be added later.",
  },
  strukturGrupCatur: {
    judul: "Chess Group Structure",
    deskripsi:
      "The community's chess group structure: board, organization, and membership.",
  },
  pengurus: {
    judul: "Board",
    deskripsi: "The board of the Indonesian Chess Community.",
    artikel: "Board Members",
    p1: "The board runs the community's activities according to Member Assembly decisions and oversees five functional divisions.",
    l1: "Chairman",
    l2: "Secretary General",
    l3: "Treasurer",
    l4: "Head of Tournament Division",
    l5: "Head of Development Division",
    l6: "Head of Media & PR Division",
    l7: "Head of Membership Division",
    l8: "Head of Technology Division",
  },
  strukturOrganisasiCatur: {
    judul: "Organization Structure",
    deskripsi: "The organizational structure chart of the Indonesian Chess Community.",
    artikel: "Organization Chart",
    p1: "The following is the organizational structure chart based on the Member Assembly decision.",
  },
  keberlanjutan: {
    judul: "Sustainability",
    deskripsi: "Rules, values, and commitments that keep the community healthy.",
    artikel: "Community Foundation",
    l1a: "Terms & Conditions",
    l1b: " — general terms applicable to all members.",
    l2a: "Community Code of Ethics",
    l2b: " — behavior norms upheld together.",
    l3a: "Frequently Asked Questions",
    l3b: " — answers to commonly asked questions.",
    nextJudul: "Terms & Conditions",
  },
  t404: {
    judul: "Page Not Found",
    deskripsi: "The address you are looking for does not exist on this site.",
    kembali: "Go Back",
    p1: "Check the link again, or return to the ",
    p2: "home page",
    p3: ".",
  },
};
