/**
 * Kamus terjemahan Komunitas Catur Indonesia.
 * Struktur bersarang; kunci dipakai oleh t("a.b.c").
 */
export const ID = {
  common: {
    home: "Beranda",
    id: "ID",
    en: "EN",
    bahasaIndonesia: "Bahasa Indonesia",
    english: "English",
    namaKomunitas: "Komunitas Catur Indonesia",
    selanjutnya: "Selanjutnya",
    selengkapnya: "Selengkapnya",
    daftarAnggota: "Daftar Anggota",
    alamat: "Address",
    surel: "Email",
    pilihBahasa: "Pilih bahasa",
    memuat: "Memuat…",
  },
  nav: {
    tentangKami: "Tentang Kami",
    programKami: "Program Kami",
    turnamen: "Turnamen",
    mediaDanInformasi: "Media & Informasi",
    keanggotaan: "Keanggotaan",
    sekilasKomunitas: "Sekilas Komunitas",
    tonggakSejarah: "Tonggak Sejarah",
    visiMisiNilai: "Visi, Misi, & Tata Nilai",
    maknaLogo: "Makna Logo",
    strukturPengurus: "Struktur Pengurus",
    strukturGrupCatur: "Struktur Grup Catur",
    pengurus: "Pengurus",
    strukturOrganisasiCatur: "Struktur Organisasi Catur",
    caraBermainCatur: "Cara Bermain Catur",
    tekaTeki: "Teka-teki Catur",
    pembukaan: "Pembukaan",
    turnamenBulanan: "Turnamen Bulanan",
    ligaMusiman: "Liga Musiman",
    turnamenTerbuka: "Turnamen Terbuka",
    ligaAntarKomunitas: "Liga Antar Komunitas",
    beritaKomunitas: "Berita Komunitas",
    galeri: "Galeri",
    pengumuman: "Pengumuman",
    pendaftaranAnggota: "Pendaftaran Anggota",
    syaratKetentuan: "Syarat & Ketentuan",
    kodeEtik: "Kode Etik Komunitas",
    pertanyaanUmum: "Pertanyaan Umum",
    hubungiKami: "Hubungi Kami",
    karir: "Karir",
    beranda: "Beranda",
    peringkat: "Peringkat",
    pengadaan: "Pengadaan",
    keberlanjutan: "Keberlanjutan",
  },
  header: {
    close: "tutup",
    closeSearch: "tutup pencarian",
    searchButton: "tombol pencarian",
    menu: "menu",
    search: "cari",
    expand: "buka {title}",
  },
  search: {
    placeholder: "Ketik kata kunci pencarian",
    enter: "Tekan Enter untuk mencari",
    noResults: "Tidak ditemukan hasil untuk “{query}”.",
  },
  footer: {
    pengumuman: "Pengumuman",
    beritaKomunitas: "Berita Komunitas",
    pendaftaranTurnamen: "Pendaftaran Turnamen",
    pengumumanLink: "Pengumuman",
    jadwalLiga: "Jadwal Liga",
    musyawarahAnggota: "Musyawarah Anggota",
    volunteer: "Relawan",
    tools: "Tools",
    programCatur: "Program Catur",
    pendaftaranAnggota: "Pendaftaran Anggota",
    kodeEtik: "Kode Etik Komunitas",
    keterbukaanInformasi: "Keterbukaan Informasi",
    kontakKami: "Kontak Kami",
    sistemPengaduan: "Sistem Pengaduan",
    alamat: "Address: Sekretariat Komunitas Catur Indonesia, Jl. Gatot Subroto No. 11-13, Medan 20152, Sumatera Utara, Indonesia",
    copyright: "© 2026 BLUNDER SKUAD Corporate Chess League. All Rights Reserved.",
  },
  hero: {
    tentangKami: "Tentang Kami",
    deskripsi:
      "Telusuri sejarah perjalanan, visi, dan misi komunitas kami yang menjadi fondasi kegiatan, filosofi logo, serta struktur pengurus yang mendukung pengembangan catur Indonesia.",
  },
  sticky: {
    sekilasKomunitas: "Sekilas Komunitas",
    tonggakSejarah: "Tonggak Sejarah",
    visiMisiNilai: "Visi, Misi, & Tata Nilai",
    maknaLogo: "Makna Logo",
    strukturPengurus: "Struktur Pengurus",
  },
  bagian: {
    selanjutnya: "Selanjutnya",
    dewanPengurus: "Dewan Pengurus dan Dewan Pembina",
  },
  sekilas: {
    judul: "Sekilas Komunitas",
    p1: "Komunitas Catur Indonesia senantiasa memegang teguh komitmen untuk menyediakan wadah bermain dan belajar catur serta mengembangkan pembinaan usia muda dalam rangka mendukung terciptanya kemandirian prestasi catur nasional. Memegang amanah sebagai komunitas catur terverifikasi di Chess.com sejak ditetapkan pada tanggal 10 Desember 2015, komunitas kini memiliki peran sangat strategis yang membawahi lima Divisi yang bergerak di bidang pengembangan catur, yaitu Divisi Turnamen yang menjalankan kompetisi internal dan eksternal, Divisi Pembinaan yang menjalankan kelas dan pelatihan, Divisi Media & Humas yang mengelola publikasi, Divisi Keanggotaan yang mengelola administrasi anggota, serta Divisi Teknologi yang mengelola platform daring komunitas.",
    p2: "Peran penting yang diemban oleh komunitas ini sekaligus menandai tonggak sejarah baru dalam perjalanan komunitas setelah kontribusi nyata yang diberikan selama lebih dari satu dekade menyediakan wadah bertanding yang telah menggerakkan semangat pecatur Indonesia dari berbagai daerah.",
    p3: "Kemampuan komunitas yang mumpuni ini dibangun di atas fondasi yang solid dan sejarah panjang dalam mengawal terwujudnya pembinaan catur nasional. Sejarah mencatat bahwa eksistensi Komunitas Catur Indonesia dibangun sejak sekitar tahun 2014, ketika sekelompok pecatur di Medan mulai berkumpul rutin untuk bertanding catur kilat di sebuah warung kopi. Kemudian kelompok tersebut resmi menjadi komunitas pada tanggal 10 Desember 2015, yang hingga kini diperingati sebagai hari lahir komunitas.",
    p4: "Pada tahun 2018, komunitas resmi membentuk klub di Chess.com sebagai basis pertandingan daring seluruh anggota. Selanjutnya, peran komunitas semakin strategis setelah pada tahun 2020 menginisiasi program kelas catur daring gratis bagi pelajar di tengah masa pandemi.",
    p5: "Berdasarkan kesepakatan Musyawarah Anggota tanggal 18 Juni 2023, komunitas mengubah struktur organisasi menjadi struktur kepengurusan dengan divisi-divisi fungsional. Pada tanggal 10 Desember 2024, komunitas memperbarui identitas visual dengan logo kuda catur berwarna dasar biru, merah, dan hijau yang merefleksikan unsur dinamis dan kepedulian pada pembinaan.",
    p6: "Bahkan setelah evolusi yang dialami selama satu dekade itu, komunitas berkomitmen untuk tetap menggaungkan semangat transformasi yang berkelanjutan guna menyempurnakan langkahnya menjadi komunitas catur terdepan di Indonesia yang didukung oleh organisasi yang semakin lincah, mudah beradaptasi, dan fokus untuk pengembangan pembinaan yang lebih luas.",
    imgAlt: "Suasana kegiatan rutin komunitas di sekretariat Medan",
    imgCaption: "Suasana kegiatan rutin komunitas di sekretariat Medan, 2025.",
  },
  tonggak: {
    judul: "Tonggak Sejarah",
    t1: "Perjalanan 2015-2016",
    p1a: "Sejarah mencatat bahwa eksistensi Komunitas Catur Indonesia dibangun sejak sekitar tahun 2014, ketika sekelompok pecatur Medan berkumpul rutin di sebuah warung kopi untuk bertanding catur kilat. Kemudian kelompok tersebut resmi menjadi komunitas dengan nama Komunitas Catur Indonesia pada 10 Desember 2015, yang hingga kini diperingati sebagai hari lahir komunitas.",
    p1b: "Selama tahun pertama, komunitas memperkokoh eksistensi sebagai satu-satunya komunitas catur terpadu di Kota Medan yang mewadahi pecatur dari berbagai latar belakang, mulai dari pelajar hingga pekerja profesional.",
    t2: "Perjalanan 2016-2017",
    p2a: "Memasuki tahun kedua, komunitas memaksimalkan pertumbuhan kegiatan dan memberikan kontribusi pada pembinaan catur daerah. Pada periode ini, eksistensi komunitas sebagai penggerak catur lokal mulai diakui oleh PERCASI Sumatera Utara. Perkembangan pesat tersebut salah satunya berkat kolaborasi turnamen bersama komunitas catur lain di Pulau Sumatera.",
    p2b: "Pada tahun 2017, komunitas resmi membentuk klub di Chess.com sebagai basis pertandingan daring bagi seluruh anggota, sekaligus menandai dimulainya era pertandingan daring rutin.",
    t3: "Perjalanan 2018-2019",
    p3a: "Pada periode ini, komunitas untuk pertama kalinya menyelenggarakan turnamen terbuka berskala kota dengan standar regulasi internasional. Dalam rentang waktu dua tahun ini, komunitas mampu menambah frekuensi turnamen internal menjadi dua kali dalam satu bulan.",
    p3b: "Di awal 2019, komunitas mulai meletakkan dasar pembinaan usia dini melalui kelas catur gratis bagi pelajar, serta membangun perpustakaan materi latihan digital.",
    t4: "Perjalanan 2020-2021",
    p4a: "Pada masa ini, komunitas menghadapi masa pandemi. Dengan dukungan para pengurus, pembenahan aspek organisasi dan platform daring dilakukan sebagai upaya komunitas untuk tetap aktif. Dalam rentang waktu ini, komunitas mampu menyelenggarakan turnamen daring mingguan yang diikuti anggota dari berbagai kota di Indonesia.",
    p4b: "Komunitas juga menginisiasi program kelas catur daring gratis bagi pelajar di tengah masa pandemi, yang menjadi cikal bakal Akademi Catur Komunitas.",
    t5: "Perjalanan 2022-2023",
    p5a: "Pada periode ini, komunitas berupaya mengembangkan pembinaan catur usia muda. Selama dua tahun terakhir, komunitas melakukan kerja sama dengan sekolah-sekolah di Medan dalam bentuk ekstrakurikuler catur dan lomba antar sekolah.",
    p5b: "Komunitas menunjukkan kesungguhannya dalam menjalankan kegiatan yang berwawasan sportivitas dengan membentuk fungsi baru, yaitu Komite Etik dan Fair Play pada 2022. Komunitas juga mulai menerapkan program penilaian performa anggota untuk meningkatkan keterlibatan seluruh anggota dalam berlatih.",
    t6: "Perjalanan 2024-2025",
    p6a: "Pada periode ini, tepatnya pada tahun 2024, komunitas mengubah struktur organisasi menjadi struktur kepengurusan dengan divisi-divisi fungsional guna mendukung efisiensi kegiatan. Pada 10 Desember 2024, komunitas memperbarui identitas visual dengan logo baru berwarna dasar biru, merah, dan hijau yang merefleksikan unsur dinamis dan kepedulian pada pembinaan.",
    p6b: "Komunitas juga melakukan transformasi pada 20 Juli 2025 melalui perombakan kurikulum latihan yang mengintegrasikan analisis digital dan latihan bersama pecatur bergelar, sebagai bagian dari target pencapaian 5.000 anggota aktif.",
  },
  visimisi: {
    visi: "Visi",
    visiLead: "Menjadi komunitas catur yang mengedepankan sportivitas, prestasi, dan pembinaan.",
    visiP1:
      "Komunitas Catur Indonesia berkomitmen untuk menjadi komunitas catur berskala nasional yang tidak hanya menjalankan kegiatan dengan landasan organisasi yang kuat, tetapi juga berperan strategis dalam mendukung pengembangan catur Indonesia, khususnya dalam memperkuat sportivitas, memastikan ketersediaan wadah bertanding, serta mendorong pembinaan yang berkelanjutan.",
    visiL1: "Sportivitas: memperkuat budaya fair play dan integritas dalam setiap pertandingan.",
    visiL2: "Prestasi: mewujudkan lingkungan kompetitif guna menjamin lahirnya pecatur berprestasi nasional dan internasional.",
    visiL3: "Pembinaan: mendorong pengembangan bakat usia muda sebagai langkah strategis dalam menjaga keberlanjutan regenerasi catur Indonesia.",
    misi: "Misi",
    misiLead:
      "Menyediakan wadah bermain dan belajar catur melalui program inovatif yang memberi nilai tambah untuk anggota dan masyarakat.",
    misiP1:
      "Misi untuk menyediakan wadah bermain dan belajar catur melalui program inovatif yang memberi nilai tambah bagi anggota dan masyarakat mencerminkan komitmen komunitas dalam menghadirkan kegiatan yang andal, berkelanjutan, dan relevan dengan dinamika perkembangan catur nasional dan global. Upaya tersebut dilakukan melalui fokus program pada dual-growth strategy, yaitu Maximizing Competitive Play dan Building Grassroots Development. Pilar Maximizing Competitive Play fokus pada peningkatan frekuensi turnamen internal, penguatan liga musiman, penguatan pertandingan persahabatan antar komunitas, serta pengembangan infrastruktur latihan. Sedangkan pilar Building Grassroots Development fokus pada pengembangan kelas pemula, ekosistem pelatihan daring, program sekolah catur, dan teknologi latihan digital.",
    tataNilai: "Tata Nilai",
    nilaiImgAlt: "Tata nilai komunitas",
    nilaiImgCaption:
      "Nilai-nilai yang dipegang teguh anggota komunitas dalam setiap pertandingan.",
  },
  maknaLogo: {
    judul: "Makna Logo",
    intro: "Makna dari logo Komunitas Catur Indonesia adalah:",
    l1: "Warna biru memiliki arti andal, dapat dipercaya, dan bertanggung jawab",
    l2: "Warna merah memiliki arti keuletan dan ketegasan serta keberanian dalam menghadapi berbagai macam kesulitan",
    l3: "Warna hijau memiliki arti pembinaan yang berwawasan sportivitas dan berkelanjutan",
    l4: "Warna emas memiliki arti prestasi, kehormatan, dan cita-cita menuju puncak",
    simbol: "Simbol grafis memiliki arti:",
    s1: "Bentuk kuda catur menggambarkan aspirasi komunitas untuk senantiasa bergerak maju dengan langkah yang cerdas, gesit, dan terukur",
    s2: "Bintang di puncak emblem melambangkan orientasi prestasi dan semangat meraih yang tertinggi",
    s3: "Papan 2×2 berwarna merah, putih, hijau, dan biru merepresentasikan strategi, keadilan aturan main, serta empat warna identitas komunitas",
    s4: "Alas hijau adalah fondasi pembinaan yang menopang seluruh langkah komunitas",
    caption: "Logo resmi Komunitas Catur Indonesia.",
  },
  struktur: {
    judul: "Struktur Pengurus",
    p1: "Komunitas Catur Indonesia menjalankan kegiatan pembinaan dan pertandingan catur yang terintegrasi mulai dari tingkat pemula hingga tingkat lanjut. Dalam kapasitasnya sebagai komunitas catur terverifikasi di Chess.com, maka secara umum fokus komunitas adalah menjalankan kegiatan pengelolaan turnamen dan pembinaan anggota, mempercepat pengembangan program latihan baru, serta menjalankan program-program kerja tahunan.",
    p2: "Sementara itu, sejumlah kegiatan yang sebelumnya merupakan kegiatan-kegiatan utama komunitas akan dijalankan oleh divisi yang telah terbentuk. Divisi ini menjalankan peran, antara lain mendorong terwujudnya operational excellence melalui pengembangan skala dan sinergi masing-masing program, mempercepat pengembangan program dan kapabilitas existing, serta meningkatkan kemampuan dan fleksibilitas dalam kemitraan dan pendanaan yang lebih menguntungkan komunitas. Berikut pemetaan peran divisi pada Komunitas Catur Indonesia:",
    dewanPembina: "Dewan Pembina",
    dewanPenasihat: "Dewan Penasihat",
    ketuaUmum: "Ketua Umum",
    sekretarisJenderal: "Sekretaris Jenderal",
    bendaharaUmum: "Bendahara Umum",
    divisiTurnamen: "Divisi Turnamen",
    divisiPembinaan: "Divisi Pembinaan",
    divisiMedia: "Divisi Media & Humas",
    divisiKeanggotaan: "Divisi Keanggotaan",
    divisiTeknologi: "Divisi Teknologi",
    caption: "Bagan Struktur Pengurus Komunitas Catur Indonesia.",
    p3: "Melalui pembentukan struktur baru komunitas ini, Komunitas Catur Indonesia diharapkan mampu bergerak lebih lincah (agile), fokus, dan lebih cepat dalam mengembangkan kapabilitas anggotanya yang setara dengan kualitas nasional guna mengakselerasi beragam inovasi di luar kegiatan konvensional komunitas, antara lain dalam bidang catur daring, sekolah catur, serta teknologi analisis digital, sehingga komunitas mampu meraih pertumbuhan jumlah anggota yang lebih besar sebagai fondasi menuju komunitas catur terdepan di Indonesia.",
  },
  keanggotaan: {
    judul: "Keanggotaan",
    deskripsi:
      "Daftar anggota yang disinkronkan otomatis dari klub BLUNDER SKUAD di Chess.com.",
    artikel: "Daftar Anggota",
    intro:
      "Daftar ini menggunakan roster publik klub BLUNDER SKUAD di Chess.com. Anggota yang sudah bergabung di Chess.com tetap perlu melengkapi pendaftaran data diri di situs ini. Data tersebut membantu pengurus mengenali pemain, memeriksa riwayat larangan, dan mencegah pemain yang terkena ban kembali memakai akun baru.",
    jumlah: "Jumlah anggota: {jumlah}",
    dataBelumLengkap: "Belum melengkapi data diri di website",
    dataBelumLengkapPenjelasan:
      "Akun ini sudah bergabung di BLUNDER SKUAD pada Chess.com, tetapi belum melengkapi data diri di website komunitas. Data diri disimpan secara privat agar pengurus dapat mengenali pemain dan mencocokkan identitas bila akun terkena ban.",
    tandaTanyaJudul: "{jumlah} anggota belum melengkapi data website",
    tandaTanyaPenjelasan:
      "Tanda tanya di samping nama berarti player sudah menjadi anggota BLUNDER SKUAD di Chess.com, tetapi belum mendaftar ulang di website. Pendaftaran ulang diperlukan untuk menyimpan data identitas secara aman, membantu pemeriksaan turnamen, dan mencegah pemain terlarang kembali dengan akun baru.",
    lengkapiData: "Lengkapi data diri di website",
    sumber: "Sumber anggota:",
    sumberCatatan: "Roster publik Chess.com diperbarui maksimal setiap 12 jam.",
    memuat: "Memuat data dari Chess.com…",
    kosongKlub: "Belum ada anggota yang terbaca dari klub Chess.com.",
    aktivitasKlub: "Aktivitas klub",
    aktivitas: {
      weekly: "Aktif mingguan",
      monthly: "Aktif bulanan",
      all_time: "Aktif sebelumnya",
    },
    kosong1: "Belum ada anggota terdaftar. Silakan ",
    kosong2: "daftar dengan akun Chess.com",
    kosong3: ".",
    no: "No.",
    foto: "Foto",
    nama: "Nama",
    akunHilang: "akun tidak ditemukan",
    gagal: "gagal memuat",
    panggilan: "Panggilan",
    kota: "Kota",
    klub: "Klub",
    kategoriUmur: "Kategori Umur",
    bergabung: "Bergabung",
    wa: "WhatsApp",
    profilJudul: "Profil Anggota",
    tutup: "Tutup",
    lihatProfil: "Klik untuk melihat profil",
    terkenaBan:
      "Akun ini diblokir dari kegiatan komunitas. Periksa keterangan pengurus atau status Chess.com.",
    tingkatanJudul: "Tingkatan Kelompok Rating",
    tingkatanRentang: "Rentang Rating",
    tingkatanKategori: "Kategori Pemain",
    tingkatanPenjelasan: "Penjelasan Kemampuan",
    tingkatanBuka: "Klik untuk membuka daftar tingkatan rating",
    tingkatanTutup: "Klik untuk melipat daftar tingkatan rating",
    tingkatan: {
      beginner: {
        label: "Beginner (Pemula)",
        deskripsi: "Baru memulai perjalanan catur dan memahami pergerakan dasar buah catur.",
      },
      novice: {
        label: "Novice (Pemula Lanjutan)",
        deskripsi: "Mulai mempelajari dasar taktik, mengamankan perwira, dan meminimalkan blunder.",
      },
      intermediate: {
        label: "Intermediate (Menengah)",
        deskripsi: "Mampu menyusun strategi, memahami taktik 2–3 langkah, dan menguasai pembukaan dasar.",
      },
      advanced: {
        label: "Advanced (Mahir)",
        deskripsi: "Memiliki pemahaman posisi yang konsisten, kalkulasi matang, dan jarang melakukan kesalahan fatal.",
      },
      expert: {
        label: "Expert (Ahli)",
        deskripsi: "Keterampilan tingkat tinggi dengan kalkulasi mendalam, manajemen waktu yang ketat, dan ketahanan mental.",
      },
      master: {
        label: "Master Level (Pakar)",
        deskripsi: "Pemain yang sangat kuat dengan kemampuan komprehensif di level turnamen nasional.",
      },
      elite: {
        label: "Elite / Grandmaster",
        deskripsi: "Kelas tertinggi tempat para pecatur profesional dunia bersaing.",
      },
    },
    nextJudul: "Pendaftaran Anggota",
  },
  verifikasi: {
    judul: "Bukti Kepemilikan Akun",
    penjelasan:
      "Buktikan bahwa akun Chess.com yang Anda tulis benar-benar milik Anda. Ini mencegah orang lain mendaftarkan akun Anda, dan mencegah pendaftaran memakai akun milik pemain lain.",
    tombolLogin: "Masuk dengan Chess.com",
    catatanLogin:
      "Anda akan diarahkan ke chess.com untuk masuk. Kata sandi Anda tidak pernah kami lihat maupun simpan.",
    atau: "Atau tanpa login",
    tombolKode: "Verifikasi lewat kode profil",
    memproses: "Memproses…",
    langkah1: "Buka pengaturan profil Chess.com Anda.",
    langkah2: "Isi kolom Location dengan kode ini:",
    langkah3:
      "Simpan perubahan, lalu klik tombol di bawah. Setelah terverifikasi, kode boleh dihapus kembali.",
    bukaPengaturan: "Buka pengaturan Chess.com",
    sudahPasang: "Saya sudah memasang kode",
    memeriksa: "Memeriksa profil…",
    belumTerbaca:
      "Kode belum terbaca. Pastikan sudah tersimpan, lalu coba lagi beberapa saat.",
    isiUsernameDulu: "Isi username Chess.com Anda terlebih dahulu.",
    berhasil: "Kepemilikan akun terverifikasi:",
    ganti: "Ganti akun",
  },
  pendaftaran: {
    judul: "Pendaftaran Anggota",
    parent: "Keanggotaan",
    deskripsi:
      "Lengkapi data administrasi dan verifikasi akun Chess.com Anda setelah bergabung ke klub BLUNDER SKUAD.",
    artikel: "Lengkapi Data Anggota",
    intro:
      "Daftar anggota situs diambil otomatis dari roster klub BLUNDER SKUAD di Chess.com. Isi formulir ini setelah akun Anda ada di klub untuk verifikasi dan administrasi tambahan. Sistem memastikan satu orang hanya menggunakan satu akun, dan akun yang ditutup Chess.com karena pelanggaran fair play tidak dapat mengikuti kegiatan komunitas.",
    klubWajibJudul: "Bergabung ke klub terlebih dahulu",
    klubWajibIsi:
      "Username harus sudah tercatat sebagai anggota BLUNDER SKUAD di Chess.com. Roster Chess.com dapat membutuhkan hingga 12 jam untuk diperbarui.",
    gabungKlub: "Buka klub BLUNDER SKUAD di Chess.com",
    label: "Username Chess.com",
    placeholder: "contoh: hikaru",
    wajib: "Masukkan username Chess.com.",
    memeriksa: "Memeriksa akun Chess.com…",
    daftar: "Daftar",
    nextJudul: "Daftar Keanggotaan",
    linkDaftar: "daftar keanggotaan",

    privasiJudul: "Data pribadi Anda aman",
    privasiIsi:
      "Nama lengkap, nomor HP/WhatsApp, dan nomor DANA hanya disimpan pada catatan pengurus dan tidak pernah ditampilkan di situs. Yang tampil publik hanya nama panggilan, kota, dan statistik Chess.com Anda. Data ini kami gunakan untuk memverifikasi bahwa satu orang hanya memiliki satu keanggotaan.",

    grupAkun: "Akun Chess.com",
    grupDiri: "Data Diri",
    grupKontak: "Kontak & Pembayaran",

    catatanUsername:
      "Gunakan username atau tautan profil chess.com/member/namaanda yang sudah bergabung di BLUNDER SKUAD.",

    labelNama: "Nama Lengkap",
    phNama: "contoh: Budi Santoso",
    catatanNama: "Sesuai identitas resmi, untuk sertifikat dan hadiah turnamen.",

    labelPanggilan: "Nama Panggilan",
    phPanggilan: "contoh: Budi",
    catatanPanggilan: "Dipakai pengurus untuk administrasi dan turnamen.",

    labelLahir: "Tanggal Lahir",
    catatanLahir: "Dipakai untuk menentukan kategori umur turnamen.",
    kategori: "Kategori",
    tahun: "tahun",

    labelKota: "Kota Asal",
    phKota: "contoh: Medan",
    catatanKota: "Untuk pembagian wilayah pada liga antar-komunitas.",

    labelHp: "Nomor HP / WhatsApp",
    phHp: "contoh: 0812-3456-7890",
    catatanHp: "Nomor aktif WhatsApp, untuk undangan turnamen dan verifikasi.",
    terbaca: "Terbaca",

    labelDana: "Nomor DANA",
    phDana: "kosongkan bila sama dengan nomor HP",
    catatanDana: "Untuk pengiriman hadiah turnamen.",

    labelEmail: "Email",
    phEmail: "contoh: budi@email.com",
    catatanEmail: "Untuk pemberitahuan resmi dari pengurus.",

    labelKlub: "Klub / Komunitas Asal",
    phKlub: "contoh: Klub Catur Medan",
    catatanKlub: "Bila Anda sudah tergabung di klub lain.",

    setuju:
      "Saya menyatakan data di atas benar, bahwa ini satu-satunya akun saya di komunitas, dan saya menyetujui Kode Etik Komunitas — termasuk larangan menggunakan bantuan engine.",

    periksaIsian: "Periksa kembali isian yang ditandai merah.",
    galatUsername: "Username Chess.com wajib diisi.",
    galatNama: "Tulis nama lengkap (minimal dua kata).",
    galatPanggilan: "Nama panggilan wajib diisi.",
    galatHp: "Nomor HP/WhatsApp tidak valid. Contoh: 0812-3456-7890.",
    galatDana: "Nomor DANA tidak valid.",
    galatKota: "Kota asal wajib diisi.",
    galatLahir: "Tanggal lahir wajib diisi.",
    galatLahirAneh: "Tanggal lahir tidak masuk akal.",
    galatEmail: "Format email tidak valid.",
    galatSetuju: "Anda harus menyetujui kode etik komunitas.",
  },
  syarat: {
    judul: "Syarat & Ketentuan",
    deskripsi:
      "Pedoman operasional dan ketentuan keanggotaan komunitas catur Blunder Skuad.",
    nextJudul: "Kode Etik Komunitas",
  },
  kodeEtik: {
    judul: "Kode Etik Komunitas",
    deskripsi:
      "Fair play, integritas, dan tata krama yang berlaku di papan, daring, maupun ruang diskusi.",
    artikel: "Kebijakan Komunitas",
    nextJudul: "Pertanyaan Umum",
  },
  pertanyaan: {
    judul: "Pertanyaan Umum",
    deskripsi:
      "Panduan praktis keanggotaan, platform bermain, format turnamen, dan kebijakan komunitas Blunder Skuad.",
    artikel: "Pertanyaan yang Sering Diajukan",
    nextJudul: "Hubungi Kami",
  },
  turnamen: {
    judul: "Turnamen",
    deskripsi:
      "Kalender pertandingan komunitas: bulanan, liga musiman, terbuka, dan antar komunitas.",
    nextJudul: "Turnamen Bulanan",
  },
  turnamenBulanan: {
    judul: "Turnamen Bulanan",
    deskripsi:
      "Turnamen Swiss lima ronde yang diadakan setiap bulan untuk anggota dan tamu.",
    artikel: "Ketentuan ringkas",
    p1: "Turnamen Bulanan memakai sistem Swiss 5 ronde. Tempo standar adalah 15+10 (kilat panjang). Grup dipisah bila peserta lebih dari 40 orang.",
    l1: "Pendaftaran ditutup H-1 pukul 21.00 WIB.",
    l2: "Anggota aktif mendapat potongan biaya administrasi.",
    l3: "Hasil diumumkan di halaman Pengumuman pada malam yang sama.",
    p2: "Jadwal bulan berjalan diumumkan di kanal anggota dan halaman Pengumuman.",
    nextJudul: "Liga Musiman",
  },
  ligaMusiman: {
    judul: "Liga Musiman",
    deskripsi:
      "Tiga musim kompetisi setahun dengan klasemen yang berjalan, bukan event sekali selesai.",
    artikel: "Musim dan format",
    p1: "Liga Musiman dibagi menjadi Musim I (Januari–April), Musim II (Mei–Agustus), dan Musim III (September–Desember). Setiap pemain bermain minimal enam partai agar masuk klasemen resmi.",
    p2: "Poin dihitung 1 untuk menang, ½ untuk remis, 0 untuk kalah. Tie-break memakai Sonneborn-Berger, kemudian hasil pertemuan langsung.",
    p3: "Juara musim mendapat undangan langsung ke final Turnamen Terbuka akhir tahun.",
    nextJudul: "Turnamen Terbuka",
  },
  turnamenTerbuka: {
    judul: "Turnamen Terbuka",
    deskripsi:
      "Event terbuka untuk umum, termasuk format yang dilaporkan ke sistem rating bila syarat terpenuhi.",
    artikel: "Untuk siapa",
    p1: "Turnamen Terbuka menerima peserta dari luar komunitas. Ini wadah mempertemukan pecatur Medan dengan tamu dari kota lain, sekaligus menguji kesiapan anggota di lapangan yang lebih ramai.",
    p2: "Bila jumlah pecatur berating mencukupi, panitia dapat mengajukan laporan rating sesuai ketentuan federasi. Informasi itu selalu tertulis di prospektus masing-masing event.",
    nextJudul: "Liga Antar Komunitas",
  },
  ligaAntar: {
    judul: "Liga Antar Komunitas",
    deskripsi:
      "Pertandingan tim melawan komunitas dan klub lain di Sumatera maupun secara daring.",
    artikel: "Format tim",
    p1: "Liga Antar Komunitas dimainkan dalam format tim 4 papan + 1 cadangan. Satu klub boleh menurunkan lebih dari satu tim bila kuota memungkinkan.",
    p2: "Undangan ke komunitas mitra dikirim Divisi Turnamen. Komunitas yang ingin menantang dapat menulis ke info@komunitascatur.or.id.",
    nextJudul: "Media & Informasi",
  },
  program: {
    judul: "Program Kami",
    deskripsi:
      "Program pembinaan Komunitas Catur Indonesia: dari kelas rutin, sesi pelatihan, hingga panduan belajar catur.",
    artikel: "Sekilas Program",
    p1: "Komunitas Catur Indonesia menghadirkan rangkaian program pembinaan yang dirancang agar setiap anggota memiliki jalur berkembang yang jelas — dari yang baru mengenal papan hingga yang mengejar gelar. Seluruh kegiatan berlangsung rutin, baik secara luring di sekretariat Medan maupun daring melalui klub BLUNDER SKUAD di Chess.com, sehingga anggota di kota mana pun tetap dapat ikut serta.",
    p2: "Keenam program di bawah ini saling melengkapi: dimulai dari kelas berjenjang untuk membangun dasar, pendampingan personal, pembinaan usia dini, sarana belajar mandiri, hingga ajang unjuk kebolehan dan latihan taktik. Jadwal, pendaftaran, dan perubahan ketentuan selalu diumumkan melalui halaman Pengumuman dan kanal anggota; informasi resmi hanya berasal dari kanal tersebut dan surel info@komunitascatur.or.id.",
    programJudul: "Program Unggulan",
    kartu: {
      kelas: {
        judul: "Kelas & Pelatihan Berjenjang",
        deskripsi:
          "Setiap pecatur memulai dari bidak terkecil. Kelas berjenjang memandu anggota dari pengenalan gerak bidak, dasar pembukaan, hingga pola akhir permainan — menyesuaikan tingkat kemampuan masing-masing.",
      },
      clinic: {
        judul: "Coaching Clinic",
        deskripsi:
          "Bimbingan intensif bersama pelatih dan pecatur bergelar. Partai anggota dibedah satu per satu untuk menemukan kelemahan, memperbaiki cara berpikir, dan melompatkan kekuatan bermain ke tingkat berikutnya.",
      },
      sekolah: {
        judul: "Sekolah Catur",
        deskripsi:
          "Kemitraan dengan sekolah untuk mengenalkan catur sejak dini sebagai sarana melatih fokus, kesabaran, dan cara berpikir strategis. Kurikulum disusun ramah anak namun tetap terarah.",
      },
      panduan: {
        judul: "Panduan Belajar Mandiri",
        deskripsi:
          "Fondasi yang kokoh dapat dipelajari kapan saja. Halaman Cara Bermain Catur menyajikan panduan runtut dari pengenalan bidak hingga pola latihan tingkat lanjut.",
      },
      simultan: {
        judul: "Simultan & Catur Buta",
        deskripsi:
          "Puncak unjuk kebolehan para pecatur andalan. Pertunjukan simultan dan catur buta digelar pada hari-hari besar komunitas untuk menguji ketangguhan sekaligus menghibur anggota.",
      },
      tekaTeki: {
        judul: "Teka-teki Taktik",
        deskripsi:
          "Ribuan soal skakmat siap mengasah naluri taktik harian. Latihan singkat yang konsisten jauh lebih membangun daripada teori panjang tanpa praktik.",
      },
    },
    h1: "Panduan dan Latihan Mandiri",
    p3a: "Bagi anggota yang ingin belajar atau mengulang dasar-dasar permainan, situs ini menyediakan halaman",
    p3b: "sebagai panduan runtut dari pengenalan bidak hingga pola latihan tingkat lanjut, serta halaman",
    p3c: "dengan 4.462 soal skakmat untuk latihan taktik harian.",
  },
  tipsTekaTeki: {
    judul: "Teka-teki & Tips",
    deskripsi:
      "Sekilas tentang teka-teki: data langkah berdasarkan rating dan analisis posisi, sebelum masuk ke papan taktik.",
    artikel: "Latih Dirimu dengan Maia sebagai Pelatihmu",
    paragraf1:
      "Maia menyusun teka-teki berdasarkan pemahamannya tentang cara jutaan pemain meningkatkan kemampuan. Dengan teka-teki Maia, kamu dapat mengukur kemampuanmu, fokus pada kelemahan pemahamanmu, dan mengubah ide-ide yang sulit ditemukan menjadi kebiasaan.",
    paragraf2:
      "Setiap teka-teki dilengkapi data yang menunjukkan bagaimana pemain dengan rating berbeda menyikapi posisi tersebut, sehingga latihanmu lebih terarah dan efektif.",
    mulai: "Mulai Teka-teki",
    demoJudul: "Teka-teki Taktis",
    demoLevel: "Menengah",
    demoTantangan: "Temukan langkah terbaik dalam posisi taktis ini",
    grafikJudul: "Langkah Berdasarkan Rating",
    grafikSumbuY: "Probabilitas Maia",
    analisisJudul: "Analisis Posisi",
    analisisBag1:
      "Waspada, posisi ini sangat berbahaya! Sangat mudah terjebak dengan kesalahan yang menggiurkan seperti {x}.",
    analisisBag2:
      "Hanya {x} yang memberikan keunggulan, dan sulit ditemukan oleh pemain manusia.",
    langkahTerbaik: "Langkah Terbaik",
    kesalahanUmum: "Kesalahan Umum",
    kesalahanLain: "Kesalahan Lain",
    kontenHanyaId:
      "Konten contoh di bawah ini hanya tersedia dalam Bahasa Indonesia. Alihkan bahasa ke Bahasa Indonesia untuk membacanya secara lengkap.",
  },
  bukuPembukaan: {
    judul: "Pembukaan",
    deskripsi:
      "Sekilas tentang buku pembukaan: nama pembukaan dan kode ECO muncul otomatis saat langkah dimainkan di papan bebas.",
    artikel: "Opening Book: Kenali Nama Pembukaanmu",
    paragraf1:
      "Mainkan langkah di papan bebas dan buku pembukaan akan langsung mengenali nama pembukaan beserta kode ECO-nya — mulai dari Ruy Lopez, Sicilian Najdorf, hingga Queen's Gambit.",
    paragraf2:
      "Lengkap dengan saran langkah berikutnya dan katalog lebih dari 3.300 nama pembukaan dari data lichess (lisensi CC0).",
    buka: "Buka Opening Book",
    demoJudul: "Buku Pembukaan",
    demoTantangan: "Nama pembukaan muncul otomatis saat posisinya dikenali",
    infoTeks:
      "Setelah {x}, buku pembukaan langsung mengenali posisi ini sebagai {label}.",
    kontenHanyaId:
      "Konten contoh di bawah ini hanya tersedia dalam Bahasa Indonesia. Alihkan bahasa ke Bahasa Indonesia untuk membacanya secara lengkap.",
  },

  caraBermain: {
    judul: "Cara Bermain Catur",
    deskripsi:
      "Panduan lengkap mengenal bidak, aturan dasar, taktik, strategi, pembukaan, endgame, hingga pola latihan untuk menembus rating master.",
    lead:
      "Panduan ini disusun bertahap: mulai dari pengenalan bidak dan aturan dasar, kemudian taktik, strategi, pembukaan, endgame, dan pola latihan untuk terus menaikkan rating.",
    labelArtikel: "Panduan Lengkap",
    daftarIsi: "Daftar Isi",
    bab: "Bab",
    gagalMuat:
      "Gagal memuat panduan. Periksa koneksi internet Anda, lalu muat ulang halaman ini.",
    kontenHanyaId:
      "Konten panduan ini hanya tersedia dalam Bahasa Indonesia. Alihkan bahasa ke Bahasa Indonesia untuk membacanya secara lengkap.",
    babBidak: "Bidak & Nilainya",
    babDasar: "Aturan & Dasar Permainan",
    babPemula: "Level Pemula",
    babMenengah: "Level Menengah",
    babStrategi: "Strategi & Posisi",
    babLanjut: "Level Lanjut",
    babMaster: "Level Master",
    babPenutup: "Penutup",
    babMalas:
      "Bab ini dimuat saat Anda membukanya agar halaman tetap cepat.",
    memuatBab: "Memuat bab…",
    muatBab: "Muat bab ini",
  },
  media: {
    judul: "Media & Informasi",
    deskripsi:
      "Kanal resmi berita, pengumuman, dan galeri Komunitas Catur Indonesia.",
    artikel: "Satu Sumber Resmi",
    p1: "Semua informasi resmi komunitas hanya dikeluarkan melalui kanal ini dan surel info@komunitascatur.or.id. Waspadai undangan turnamen atau pungutan yang tidak tercantum di halaman Pengumuman.",
    p2: "Kanal yang tersedia adalah sebagai berikut:",
    l1: "laporan kegiatan, wawancara, dan liputan turnamen.",
    l2: "foto kegiatan sekretariat, kelas, dan pertandingan.",
    nextJudul: "Berita Komunitas",
  },
  berita: {
    judul: "Berita Komunitas",
    deskripsi: "Liputan kegiatan, hasil pertandingan, dan cerita anggota.",
    artikel: "Terbaru",
    n1a: "12 Agustus 2026 — Turnamen Bulanan Agustus diikuti 64 pecatur.",
    n1b: "Rekor peserta baru untuk event internal. Grup A dimenangkan pecatur junior dari chapter Medan.",
    n2a: "28 Juli 2026 — Coaching clinic struktur pion bersama pelatih tamu.",
    n2b: "Sesi daring 110 menit membahas Isolated Queen Pawn dan cara merencanakan break di pusat.",
    n3a: "10 Desember 2025 — Hari lahir komunitas ke-10 dirayakan dengan simultan.",
    n3b: "Dua puluh papan simultan dibuka untuk pelajar. Acara ditutup pembaruan identitas visual.",
  },
  pengumuman: {
    judul: "Pengumuman",
    deskripsi:
      "Pemberitahuan resmi: jadwal, pendaftaran, dan perubahan ketentuan.",
    artikel: "Berlaku saat ini",
    p1a: "Pendaftaran Turnamen Bulanan September",
    p1b: " dibuka hingga 31 Agustus 2026 pukul 21.00 WIB.",
    p2a: "Libur sekretariat",
    p2b: " pada 17 Agustus 2026. Kelas luring dialihkan ke sesi daring.",
    p3a: "Pemanggilan tim Liga Antar Komunitas",
    p3b: " diumumkan melalui surel anggota pada 20 Agustus 2026.",
    nextJudul: "Galeri",
  },
  galeri: {
    judul: "Galeri",
    deskripsi: "Foto kegiatan kelas, pertandingan, dan perayaan hari lahir komunitas.",
    artikel: "Dokumentasi",
    p1: "Foto dipilih dari arsip Divisi Media. Untuk pemakaian ulang di luar kanal komunitas, hubungi humas terlebih dahulu.",
    img1Alt: "Kegiatan rutin sekretariat Medan",
    img1Caption: "Suasana kegiatan rutin komunitas di sekretariat Medan, 2025.",
    img2Alt: "Tata nilai komunitas",
    img2Caption:
      "Nilai-nilai yang dipegang teguh anggota komunitas dalam setiap pertandingan.",
    img3Alt: "Arsip kegiatan 2024",
    img3Caption: "Dokumentasi kegiatan komunitas, 2024.",
  },
  hubungi: {
    judul: "Hubungi Kami",
    deskripsi: "Sekretariat Medan, surel resmi, dan formulir pesan.",
    sekretariat: "Sekretariat",
    alamat: "Address: Sekretariat Komunitas Catur Indonesia, Jl. Gatot Subroto No. 11-13, Medan 20152, Sumatera Utara, Indonesia",
    jam: "Jam kunjung luring: Sabtu 09.00–16.00 WIB, kecuali pada tanggal libur yang diumumkan melalui halaman Pengumuman.",
    kirimPesan: "Kirim Pesan",
    terkirim: "Pesan terkirim. Kami membalas pada hari kerja.",
    nama: "Nama",
    surel: "Surel",
    pesan: "Pesan",
    kirim: "Kirim",
  },
  karir: {
    judul: "Karir",
    deskripsi: "Peluang berkontribusi bersama Komunitas Catur Indonesia.",
    artikel: "Posisi Terbuka",
    l1a: "Volunteer Divisi Media",
    l1b: " — mendokumentasikan kegiatan dan mengelola kanal informasi.",
    l2a: "Asisten Pelatih Sekolah Catur",
    l2b: " — mendampingi sesi kelas luring di chapter Medan.",
    l3a: "Staf Sekretariat (paruh waktu)",
    l3b: " — membantu administrasi anggota dan pendaftaran turnamen.",
    kirim:
      "Kirim lamaran ke info@komunitascatur.or.id dengan subjek sesuai posisi yang dituju.",
    nextJudul: "Hubungi Kami",
  },
  pengadaan: {
    judul: "Pengadaan",
    deskripsi: "Informasi pengadaan barang dan jasa Komunitas Catur Indonesia.",
    artikel: "Pengadaan Barang & Jasa",
    p1: "Halaman ini merupakan kerangka awal halaman pengadaan Komunitas Catur Indonesia.",
    p2: "Konten lengkap mengenai pengadaan barang dan jasa akan ditambahkan kemudian.",
  },
  strukturGrupCatur: {
    judul: "Struktur Grup Catur",
    deskripsi:
      "Susunan grup catur komunitas: pengurus, struktur organisasi, dan keanggotaan.",
  },
  pengurus: {
    judul: "Pengurus",
    deskripsi: "Susunan pengurus Komunitas Catur Indonesia.",
    peran: {
      "super-admins": "Admin Utama",
      admins: "Admin",
      "event-coordinators": "Koordinator Acara",
    },
    artikel: "Pengurus BLUNDER SKUAD",
    p1: "Temui para pengurus yang mengelola klub, mendampingi anggota, dan mengoordinasikan kegiatan BLUNDER SKUAD di Chess.com.",
    bergabung: "Bergabung",
    rating: "Rating",
    belumDinilai: "Belum dinilai",
    bukaProfil: "Buka profil Chess.com",
    sumber: "Sumber data:",
    diperbarui: "diperbarui 17 Agustus 2026",
  },
  strukturOrganisasiCatur: {
    judul: "Struktur Organisasi Catur",
    deskripsi: "Bagan struktur organisasi Komunitas Catur Indonesia.",
    artikel: "Struktur Organisasi BLUNDER SKUAD",
    p1: "Struktur organisasi menggambarkan hubungan peran pengurus hingga anggota klub. Susunan pengurus mengikuti data publik BLUNDER SKUAD di Chess.com, sedangkan jumlah anggota disinkronkan dari roster klub.",
    klub: "Klub Catur",
    anggota: "Anggota Klub",
    orang: "anggota",
    roster: "Roster BLUNDER SKUAD",
    caption: "Admin Utama memimpin pengelolaan klub, didukung oleh Admin dan Koordinator Acara dalam melayani seluruh anggota BLUNDER SKUAD.",
  },
  keberlanjutan: {
    judul: "Keberlanjutan",
    deskripsi: "Aturan, nilai, dan komitmen yang menjaga komunitas tetap sehat.",
    artikel: "Landasan Komunitas",
    nextJudul: "Syarat & Ketentuan",
  },
  tekaTeki: {
    judul: "Teka-teki Catur",
    deskripsi:
      "Latih naluri taktismu dengan 5.486 soal skakmat dari partai nyata di basis data puzzle Lichess. Temukan skakmat dalam 1, 2, atau 3 langkah — ada petunjuk bila kamu buntu.",
    memuat: "Memuat teka-teki…",
    gagalMuat:
      "Gagal memuat data teka-teki. Periksa koneksi internet Anda, lalu muat ulang halaman ini.",
    caraMain:
      "Klik atau seret bidak milikmu ke petak tujuan. Cari langkah yang berujung skakmat — lawan akan membalas otomatis sesuai pertahanan terbaiknya.",
    caraTanda:
      "Tanda bantu analisis: klik kanan petak untuk menandainya dengan warna kuning; tahan klik kanan lalu seret untuk menggambar panah oranye; klik kanan pada petak yang sudah bertanda (atau klik kiri satu kali pada petak kosong) untuk menghapus semua tanda. Tahan Shift/Ctrl/Alt saat menandai untuk warna merah/hijau/biru.",
    hapusSemuaTanda: "Hapus Semua Tanda",
    soal: "Soal #{n} dari {total}",
    skakmat1: "Skakmat dalam 1 Langkah",
    skakmat2: "Skakmat dalam 2 Langkah",
    skakmat3: "Skakmat dalam 3 Langkah",
    mudah: "Mudah",
    menengah: "Menengah",
    sulit: "Sulit",
    giliranPutih: "Putih melangkah",
    giliranHitam: "Hitam melangkah",
    promosiJudul: "Promosi Bidak",
    promosiPutih: "Putih promosi ke…",
    promosiHitam: "Hitam promosi ke…",
    promosiMenteri: "Menteri (Ratu)",
    promosiBenteng: "Benteng",
    promosiGajah: "Gajah",
    promosiKuda: "Kuda",
    promosiBatal: "Batal",
    petunjuk: "Petunjuk",
    lewati: "Lewati",
    selanjutnya: "Selanjutnya",
    acak: "Acak",
    sebelumnya: "Sebelumnya",
    berikutnya: "Berikutnya",
    salah: "Belum tepat, coba lagi!",
    benar: "Bagus! Langkah tepat.",
    terpecahkan: "Checkmate.",
    sudahTerpecahkan: "Sudah pernah kamu pecahkan",
    totalTerpecahkan: "Terpecahkan: {n}",
    langsungKe: "Langsung ke Soal",
    buka: "Buka",
    rentangNomor: "Nomor 1 sampai {total}",
    nomorTidakValid: "Masukkan nomor antara 1 dan {total}.",
    pengaturan: "Pengaturan",
    tidakAdaSoal:
      "Tidak ada soal yang cocok dengan kombinasi Level, Langkah, Tema, dan Giliran saat ini. Longgarkan salah satu saringan di Pengaturan.",
    lanjutOtomatis: "Lanjut otomatis",
    otomatisNyalakan: "Aktifkan lanjut otomatis",
    otomatisMatikan: "Nonaktifkan lanjut otomatis",
    labelSoal: "Soal",
    labelLevel: "Level",
    labelLangkah: "Langkah",
    labelTema: "Tema",
    labelGiliran: "Giliran",
    labelBidak: "Bidak",
    semuaLevel: "Semua",
    sangatMudah: "Sangat mudah",
    normal: "Normal",
    sangatSulit: "Sangat sulit",
    semua: "Semua",
    langkahSatu: "1 langkah",
    langkahDua: "2 langkah",
    langkahTiga: "3 langkah",
    semuaTema: "Semua",
    temaGrupSkakmat: "Pola Skakmat",
    temaGrupTaktik: "Motif Taktik",
    temaGrupKarakteristik: "Karakteristik",
    tema: {
      backRankMate: "Skakmat punggung",
      smotheredMate: "Skakmat sempit",
      promotion: "Promosi",
      sacrifice: "Pengorbanan",
      attraction: "Attraksi (umpan)",
      deflection: "Defleksi",
      pin: "Pengikat (pin)",
      fork: "Tusukan (fork)",
      discoveredAttack: "Serangan terbuka",
      doubleCheck: "Skak ganda",
      hangingPiece: "Bidak menggantung",
      exposedKing: "Raja terekspos",
      endgame: "Endgame",
      middlegame: "Middlegame",
      opening: "Pembukaan",
      master: "Partai master",
      kingsideAttack: "Serangan sayap raja",
      queensideAttack: "Serangan sayap menteri",
    },
    semuaGiliran: "Semua",
    hanyaPutih: "Hanya putih",
    hanyaHitam: "Hanya hitam",
    lanjutOtomatis: "Muat teka-teki berikutnya secara otomatis setelah setiap percobaan",
    syzygyJudul: "Tablebase Syzygy",
    syzygyDidukung: "Didukung oleh Lichess",
    engineDeskripsi:
      "Perhatian: menyalakan Stockfish menampilkan evaluasi dan langkah terbaik posisi ini — bisa membocorkan jawaban teka-teki. Paling pas untuk membedah posisi setelah Anda mencoba sendiri.",
    syzygyGagal:
      "Posisi ini tidak bisa dianalisis tablebase (maksimal 7 bidak).",
    syzygyMenganalisis: "Menganalisis posisi…",
    syzygyDetail: "Detail di Lichess ↗",
    syzygyCatatan: "Hasil optimal dari sisi yang giliran sekarang.",
    syzygyKat: {
      win: "Menang",
      "cursed-win": "Menang terkutuk",
      draw: "Seri",
      "blessed-loss": "Kalah berkat",
      loss: "Kalah",
      unknown: "Tidak diketahui",
    },
    warnaPutih: "putih",
    warnaHitam: "hitam",
    namaBidak: {
      p: "bidak",
      n: "kuda",
      b: "gajah",
      r: "benteng",
      q: "menteri",
      k: "raja",
    },
    ariaPetakKosong: "petak {sq}, kosong",
    ariaPetakBidak: "petak {sq}, {bidak} {warna}",
    ingatPosisi:
      "Ingat posisi terakhir saya — lanjutkan dari sini saat saya kembali",
    posisiTersimpan: "Posisi tersimpan: soal #{n}",
    ingatNonaktif: "Posisi tidak disimpan.",
    sumber:
      'Soal diambil dari basis data puzzle Lichess (partai nyata, lisensi CC0 domain publik), hasil karya <a href="https://delta-polder-indonesia.github.io/BintangToba/index.html" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:text-blue-800 underline">Bintang Toba (2026)</a>.',
    selanjutnyaJudul: "Pelajari Cara Bermain Catur",
  },
  papan: {
    judul: "Penjelajah Pembukaan Catur",
    remah: "Pembukaan",
    penjelajah: "Penjelajah Pembukaan",
    penjelajahDeskripsi:
      "Telusuri variasi pembukaan langkah demi langkah dan lihat statistik setiap kelanjutan.",
    deskripsi:
      "Papan catur bebas untuk menganalisis dan mempelajari pembukaan. Mainkan langkah, dan nama pembukaan beserta kode ECO-nya muncul otomatis.",
    memuat: "Memuat buku pembukaan…",
    gagalMuat:
      "Gagal memuat data pembukaan. Periksa koneksi internet Anda, lalu muat ulang halaman ini.",
    setBidak: "Set Bidak",
    flip: "Balik",
    undo: "Undo",
    reset: "Reset",
    salinPgn: "Salin PGN",
    tersalin: "PGN tersalin!",
    pembukaan: "Pembukaan",
    variasi: "variasi",
    petunjukAwal:
      "Mulai bermain — nama pembukaan muncul saat posisinya dikenali.",
    belumAdaNama: "Belum ada nama pembukaan untuk posisi ini.",
    diLuarBuku: "Di luar buku pembukaan",
    langkahBerikutnya: "Langkah berikutnya",
    katalog: "Katalog Pembukaan",
    pilihPembukaan: "Pilih pembukaan…",
    cariPembukaan: "Cari nama atau kode ECO…",
    statistik: "Statistik",
    partai: "partai",
    ratingRata: "rating rata-rata",
    menangPutih: "Putih menang",
    menangHitam: "Hitam menang",
    seri: "Seri",
    tidakAdaHasil: "Tidak ditemukan pembukaan untuk “{q}”.",
    menampilkan: "Menampilkan {n} dari {total}",
    riwayat: "Riwayat Langkah",
    kosong: "Belum ada langkah.",
    keAwal: "Ke awal",
    mundur: "Mundur",
    maju: "Maju",
    keAkhir: "Ke akhir",
    pengaturan: "Pengaturan",
    resetPapan: "Reset papan",
    pengaturanPapan: "Pengaturan Papan",
    warnaPapan: "Warna papan",
    posisiFen: "Posisi FEN",
    daftarLangkahPgn: "Daftar Langkah (PGN)",
    posisiAwal: "Posisi awal",
    salin: "Salin",
    tersalinSingkat: "Tersalin",
    tutup: "Tutup",
    daftarLangkah: "Daftar Langkah",
    basisData: "Basis Data Penjelajah Pembukaan",
    kolomLangkah: "Langkah Berikutnya",
    kolomJumlah: "Jumlah Partai",
    kolomPersen: "Persentase Kemenangan",
    kolomPutihSeriHitam: "Putih / Seri / Hitam",
    warnaBiru: "Biru",
    warnaCokelat: "Cokelat",
    warnaOranye: "Oranye",
    warnaHijau: "Hijau",
    warnaAbu: "Abu-abu",
    warnaBiruMuda: "Biru muda",
    warnaBiruTua: "Biru tua",
    warnaKayu: "Kayu",
    warnaMarmerCokelat: "Marmer cokelat",
    warnaMarmerHijau: "Marmer hijau",
    engine: "Analisis Engine",
    engineDeskripsi:
      "Nyalakan Stockfish — berjalan penuh di peramban Anda (unduhan sekali ±7 MB) — untuk menilai posisi dan melihat barisan langkah terbaiknya.",
    engineNyalakan: "Nyalakan",
    engineMatikan: "Matikan",
    engineMemuat: "Memuat engine… (sekali saja, ±7 MB)",
    engineMenganalisis: "Menganalisis…",
    engineGagal: "Gagal memuat engine. Periksa koneksi internet, lalu coba lagi.",
    engineCobaLagi: "Coba lagi",
    engineCepat: "Cepat",
    engineSeimbang: "Seimbang",
    engineDalam: "Dalam",
    engineKedalaman: "Durasi analisis",
    engineKedalamanN: "Kedalaman {n}",
    engineSkor: "Evaluasi:",
    engineMate: "skakmat terdeteksi",
    engineBarisan: "Barisan langkah terbaik",
    engineMainkan: "Mainkan",
    engineSelesai: "Posisi sudah selesai (skakmat/seri) — tidak ada yang perlu dianalisis.",
    enginePanah: "Panah biru di papan = saran langkah engine.",
    warnaMetal: "Metal",
    sumber:
      'Data pembukaan diambil dari lichess-org/chess-openings (lisensi CC0, domain publik), hasil karya <a href="https://delta-polder-indonesia.github.io/BintangToba/index.html" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:text-blue-800 underline">Bintang Toba (2025)</a>.',
  },
  t404: {
    judul: "Halaman tidak ditemukan",
    deskripsi: "Alamat yang Anda tuju tidak ada di situs ini.",
    kembali: "Kembali",
    p1: "Periksa kembali tautan, atau kembali ke ",
    p2: "beranda",
    p3: ".",
  },
  landing: {
    sekilasLabel: "Sekilas Blunder Skuad",
    sekilasDesk:
      "Selama lebih dari satu dekade, kami menyediakan wadah bermain dan belajar bagi pecatur dari seluruh penjuru negeri.",
    ketuaPengurus: "Ketua dan Pengurus",
    pustakaLabel: "Perpustakaan",
    pustakaJudul: "E-Book Catur",
    pustakaDesk:
      "Materi belajar yang ditulis dan dikurasi anggota, dari fundamental opening sampai endgame teoretis. Semua gratis diunduh.",
    kartu1Judul: "Program Sekolah Catur",
    kartu1Desk: "Jelajahi program pendidikan dan pelatihan catur yang kami sediakan untuk seluruh kalangan.",
    kartu2Judul: "Turnamen Berkala",
    kartu2Desk: "Ikuti kompetisi catur rutin yang kami adakan untuk mengasah kemampuan dan sportivitas.",
    kartu3Judul: "Komunitas dan Relasi",
    kartu3Desk: "Bergabung dengan jaringan pecatur dari berbagai daerah di seluruh Indonesia.",
    kartu4Judul: "Panduan Bermain Catur",
    kartu4Desk: "Pelajari strategi, taktik, dan tips bermain catur dari dasar hingga tingkat lanjut.",
    sebelumnya: "Sebelumnya",
    selanjutnya: "Selanjutnya",
    keberlanjutanDesk:
      "Komunitas Catur Indonesia berkomitmen membangun ekosistem catur yang berkelanjutan melalui pendidikan, pembinaan bakat, dan penguatan jejaring pecatur di seluruh Indonesia. Kami percaya bahwa konsistensi dalam program dan kebersamaan adalah kunci kemajuan catur nasional.",
    harapanJudul: "Harapan dan Terima Kasih",
    harapanP1:
      "Komunitas Catur Indonesia hadir dari keyakinan sederhana: setiap orang yang duduk di depan papan catur membawa potensi untuk bertumbuh. Dari pemula yang baru mengenal pergerakan bidak hingga pecatur berpengalaman yang rutin menempuh turnamen, kami ingin memastikan tidak ada yang berjalan sendirian.",
    harapanP2:
      "Kepada seluruh anggota, pengurus, relawan, dan mitra yang telah memberikan waktu, tenaga, dan dukungan — terima kasih. Setiap turnamen yang berjalan lancar, setiap kelas yang penuh semangat, dan setiap langkah kecil kemajuan anggota adalah buah kerja sama kita bersama.",
    harapanP3:
      "Ke depan, semoga komunitas ini semakin terbuka dan semakin jauh menjangkau pecatur di berbagai daerah — terus menjadi rumah bagi siapa pun yang ingin bermain, belajar, dan bertumbuh bersama catur.",
    harapanTtd: "Salam hangat, Pengurus Komunitas Catur Indonesia",
    sorotanJudul: "Sorotan Kegiatan",
    sorotanDeskripsi:
      "Rangkaian kegiatan yang menopang pembinaan dan prestasi catur komunitas.",
    sorotan1Judul: "Turnamen Rutin Setiap Bulan",
    sorotan1Isi:
      "Turnamen Bulanan, Liga Musiman, dan Liga Antar Komunitas menjaga jam terbang bertanding anggota tetap tinggi sepanjang tahun.",
    sorotan2Judul: "Pembinaan Berjenjang",
    sorotan2Isi:
      "Kelas dasar, coaching clinic bersama pelatih tamu, dan sekolah catur untuk pelajar membangun fondasi taktik dan strategi.",
    sorotan3Judul: "Media & Dokumentasi Terbuka",
    sorotan3Isi:
      "Berita, pengumuman, dan galeri kegiatan dipublikasikan berkala agar anggota dan masyarakat mengikuti perkembangan komunitas.",
    ajakanJudul: "Siap Bergabung dengan Komunitas Catur Indonesia?",
    ajakanDeskripsi:
      "Lengkapi data diri Anda dan mulai ikuti turnamen, kelas, serta kegiatan komunitas.",
    ajakanTombol: "Daftar Sekarang",
  },
};

