/** English dictionary. Loaded on demand by the browser. */
export const EN = {
  common: {
    home: "Home",
    id: "ID",
    en: "EN",
    bahasaIndonesia: "Bahasa Indonesia",
    english: "English",
    namaKomunitas: "Indonesia Chess Community",
    judulBeranda: "Blunder Skuad | Komunitas Catur Indonesia",
    selanjutnya: "Next",
    selengkapnya: "Learn More",
    tutup: "Close",
    daftarAnggota: "Register as Member",
    alamat: "Address",
    surel: "Email",
    pilihBahasa: "Choose language",
    memuat: "Loading…",
  },
  nav: {
    analisa: "Game analysis",
    tentangKami: "About Us",
    programKami: "Our Programs",
    turnamen: "Tournaments",
    mediaDanInformasi: "Media & Information",
    keanggotaan: "Membership",
    sekilasKomunitas: "Community Overview",
    tonggakSejarah: "Historical Milestones",
    visiMisiNilai: "Vision, Mission & Values",
    maknaLogo: "Logo Meaning",
    strukturPengurus: "Board Structure",
    strukturGrupCatur: "Chess Group Structure",
    pengurus: "Board",
    strukturOrganisasiCatur: "Organization Structure",
    caraBermainCatur: "How to Play Chess",
    tekaTeki: "Chess Puzzles",
    pembukaan: "Openings",
    eBookPanduan: "E-Books & Guides",
    turnamenBulanan: "Monthly Tournament",
    ligaMusiman: "Seasonal League",
    turnamenTerbuka: "Open Tournament",
    ligaAntarKomunitas: "Inter-Community League",
    beritaKomunitas: "Community News",
    galeri: "Gallery",
    pengumuman: "Announcements",
    pendaftaranAnggota: "Member Registration",
    syaratKetentuan: "Terms & Conditions",
    kodeEtik: "Community Code of Ethics",
    pertanyaanUmum: "Frequently Asked Questions",
    hubungiKami: "Contact Us",
    karir: "Careers",
    beranda: "Home",
    peringkat: "Ratings",
    pengadaan: "Procurement",
    keberlanjutan: "Sustainability",
  },
  header: {
    close: "close",
    closeSearch: "close search",
    searchButton: "search button",
    menu: "menu",
    search: "search",
    expand: "expand {title}",
  },
  search: {
    placeholder: "Type a search keyword",
    enter: "Press Enter to search",
    noResults: "No results found for “{query}”.",
  },
  footer: {
    pengumuman: "Announcements",
    beritaKomunitas: "Community News",
    pendaftaranTurnamen: "Tournament Registration",
    pengumumanLink: "Announcements",
    jadwalLiga: "League Schedule",
    musyawarahAnggota: "Member Assembly",
    volunteer: "Volunteer",
    tools: "Tools",
    programCatur: "Chess Programs",
    pendaftaranAnggota: "Member Registration",
    kodeEtik: "Community Code of Ethics",
    keterbukaanInformasi: "Information Disclosure",
    kontakKami: "Contact Us",
    sistemPengaduan: "Complaint System",
    alamat: "Address: Indonesia Chess Community Secretariat, Jl. Gatot Subroto No. 11-13, Medan 20152, North Sumatra, Indonesia",
    copyright: "© 2026 BLUNDER SKUAD Corporate Chess League. All Rights Reserved.",
  },
  hero: {
    tentangKami: "About Us",
    deskripsi:
      "Explore the history, vision, and mission of our community that form the foundation of our activities, the logo philosophy, and the board structure supporting the development of chess in Indonesia.",
  },
  sticky: {
    sekilasKomunitas: "Community Overview",
    tonggakSejarah: "Historical Milestones",
    visiMisiNilai: "Vision, Mission & Values",
    maknaLogo: "Logo Meaning",
    strukturPengurus: "Board Structure",
  },
  bagian: {
    selanjutnya: "Next",
    dewanPengurus: "Board of Directors and Board of Trustees",
  },
  sekilas: {
    judul: "Community Overview",
    p1: "The Indonesia Chess Community firmly upholds its commitment to provide a space to play and learn chess and to develop youth coaching in support of building self-reliant national chess achievements. Carrying the mandate as a verified chess community on Chess.com since its founding on December 10, 2015, the community now plays a highly strategic role overseeing five Divisions working in chess development: the Tournament Division running internal and external competitions, the Development Division running classes and training, the Media & PR Division managing publications, the Membership Division managing member administration, and the Technology Division managing the community's online platform.",
    p2: "The important role borne by this community also marks a new milestone in its journey, following the real contributions made over more than a decade of providing a competition platform that has energized chess players from across Indonesia.",
    p3: "This capable community is built on a solid foundation and a long history of guiding the realization of national chess development. Records show that the Indonesia Chess Community's existence dates back to around 2014, when a group of players in Medan began gathering regularly to play blitz chess at a coffee shop. The group was officially established as a community on December 10, 2015, which is still celebrated today as the community's birthday.",
    p4: "In 2018, the community officially formed a club on Chess.com as the basis for online play for all members. Subsequently, the community's role grew more strategic after 2020 when it initiated a free online chess class program for students during the pandemic.",
    p5: "Following the Member Assembly agreement of June 18, 2023, the community restructured its organization into a management structure with functional divisions. On December 10, 2024, the community renewed its visual identity with a knight logo on blue, red, and green bases reflecting dynamism and a commitment to development.",
    p6: "Even after the evolution experienced over that decade, the community is committed to continuing its spirit of sustainable transformation to refine its path toward becoming Indonesia's leading chess community, supported by an organization that is increasingly agile, adaptable, and focused on broader development.",
    imgAlt: "Routine community activities at the Medan secretariat",
    imgCaption: "Routine community activities at the Medan secretariat, 2025.",
  },
  tonggak: {
    judul: "Historical Milestones",
    t1: "The Journey 2015-2016",
    p1a: "Records show that the Indonesia Chess Community's existence dates back to around 2014, when a group of Medan chess players gathered regularly at a coffee shop to play blitz chess. The group was officially established as a community named Komunitas Catur Indonesia on December 10, 2015, which is still celebrated today as the community's birthday.",
    p1b: "During its first year, the community strengthened its existence as the only integrated chess community in Medan, accommodating players from various backgrounds, from students to working professionals.",
    t2: "The Journey 2016-2017",
    p2a: "In its second year, the community maximized the growth of its activities and contributed to regional chess development. During this period, the community's existence as a driver of local chess began to be recognized by PERCASI North Sumatra. This rapid growth was partly thanks to tournament collaboration with other chess communities across Sumatra.",
    p2b: "In 2017, the community officially formed a club on Chess.com as the basis for online play for all members, marking the beginning of an era of regular online matches.",
    t3: "The Journey 2018-2019",
    p3a: "During this period, the community for the first time organized a city-scale open tournament under international regulation standards. Over these two years, the community increased the frequency of internal tournaments to twice a month.",
    p3b: "In early 2019, the community began laying the groundwork for youth development through free chess classes for students, and built a library of digital training materials.",
    t4: "The Journey 2020-2021",
    p4a: "During this time, the community faced the pandemic. With the support of its administrators, organizational and online platform improvements were made to keep the community active. During this period, the community managed to run weekly online tournaments attended by members from various cities across Indonesia.",
    p4b: "The community also initiated a free online chess class program for students amid the pandemic, which became the forerunner of the Community Chess Academy.",
    t5: "The Journey 2022-2023",
    p5a: "During this period, the community sought to develop youth chess coaching. Over these two years, the community collaborated with schools in Medan through chess extracurriculars and inter-school competitions.",
    p5b: "The community demonstrated its commitment to sportsmanship-oriented activities by establishing a new function, the Ethics and Fair Play Committee, in 2022. The community also began implementing a member performance evaluation program to increase member engagement in training.",
    t6: "The Journey 2024-2025",
    p6a: "During this period, specifically in 2024, the community restructured its organization into a management structure with functional divisions to support operational efficiency. On December 10, 2024, the community renewed its visual identity with a new logo on blue, red, and green bases reflecting dynamism and a commitment to development.",
    p6b: "The community also underwent a transformation on July 20, 2025, through an overhaul of its training curriculum integrating digital analysis and training alongside titled players, as part of its target of reaching 5,000 active members.",
  },
  visimisi: {
    visi: "Vision",
    visiLead:
      "To become a chess community that prioritizes sportsmanship, achievement, and development.",
    visiP1:
      "The Indonesia Chess Community is committed to becoming a national-scale chess community that not only carries out its activities on a strong organizational foundation, but also plays a strategic role in supporting the development of Indonesian chess, particularly in strengthening sportsmanship, ensuring the availability of competition platforms, and encouraging sustainable development.",
    visiL1: "Sportsmanship: strengthening a culture of fair play and integrity in every match.",
    visiL2: "Achievement: creating a competitive environment to guarantee the emergence of nationally and internationally successful players.",
    visiL3: "Development: encouraging youth talent development as a strategic step in sustaining the regeneration of Indonesian chess.",
    misi: "Mission",
    misiLead:
      "To provide a place to play and learn chess through innovative programs that add value for members and the wider community.",
    misiP1:
      "The mission to provide a place to play and learn chess through innovative programs that add value for members and the community reflects the community's commitment to delivering reliable, sustainable activities relevant to the dynamics of national and global chess development. These efforts are carried out through a program focus on a dual-growth strategy: Maximizing Competitive Play and Building Grassroots Development. The Maximizing Competitive Play pillar focuses on increasing internal tournament frequency, strengthening seasonal leagues, reinforcing friendly matches between communities, and developing training infrastructure. Meanwhile, the Building Grassroots Development pillar focuses on developing beginner classes, an online training ecosystem, a chess school program, and digital training technology.",
    tataNilai: "Values",
    nilaiImgAlt: "Community values",
    nilaiImgCaption:
      "The values upheld by community members in every match.",
  },
  maknaLogo: {
    judul: "Logo Meaning",
    intro: "The meaning of the Indonesia Chess Community logo is:",
    l1: "Blue represents reliability, trustworthiness, and responsibility",
    l2: "Red represents tenacity, firmness, and courage in facing various difficulties",
    l3: "Green represents development grounded in sportsmanship and sustainability",
    l4: "Gold represents achievement, honor, and the aspiration to reach the top",
    simbol: "The graphic symbol means:",
    s1: "The chess knight shape reflects the community's aspiration to always move forward with smart, agile, and measured steps",
    s2: "The star atop the emblem symbolizes an achievement orientation and the spirit of reaching the highest",
    s3: "The 2×2 board in red, white, green, and blue represents strategy, fair rules of play, and the community's four identity colors",
    s4: "The green base is the foundation of development that supports every step of the community",
    caption: "The official logo of the Indonesia Chess Community.",
  },
  struktur: {
    judul: "Board Structure",
    p1: "The Indonesia Chess Community runs integrated chess development and competition activities from beginner to advanced levels. In its capacity as a verified chess community on Chess.com, the community's general focus is managing tournaments and member development, accelerating the development of new training programs, and carrying out annual work programs.",
    p2: "Meanwhile, a number of activities that were previously core community activities will be run by the established divisions. These divisions play a role, among others, in driving operational excellence through the development of scale and synergy across programs, accelerating the development of existing programs and capabilities, and increasing capacity and flexibility in partnerships and funding that are more beneficial to the community. The following is a mapping of the division roles in the Indonesia Chess Community:",
    dewanPembina: "Board of Trustees",
    dewanPenasihat: "Board of Advisors",
    ketuaUmum: "Chairperson",
    sekretarisJenderal: "Secretary General",
    bendaharaUmum: "Treasurer",
    divisiTurnamen: "Tournament Division",
    divisiPembinaan: "Development Division",
    divisiMedia: "Media & PR Division",
    divisiKeanggotaan: "Membership Division",
    divisiTeknologi: "Technology Division",
    caption: "Organization chart of the Indonesia Chess Community.",
    p3: "Through this new organizational structure, the Indonesia Chess Community is expected to move more agilely, more focused, and faster in developing member capabilities equal to national quality, to accelerate various innovations beyond conventional community activities, including in online chess, chess schools, and digital analysis technology, so that the community can achieve greater membership growth as the foundation toward becoming Indonesia's leading chess community.",
  },
  keanggotaan: {
    judul: "Membership",
    deskripsi:
      "Member list automatically synchronized from the BLUNDER SKUAD club on Chess.com.",
    artikel: "Member List",
    intro:
      "This list uses the public BLUNDER SKUAD roster on Chess.com. Members who have joined on Chess.com must still complete their personal-data registration on this website. This helps staff identify players, review ban history, and prevent banned players from returning with new accounts.",
    jumlah: "Total members: {jumlah}",
    dataBelumLengkap: "Website personal data is incomplete",
    dataBelumLengkapPenjelasan:
      "This account has joined BLUNDER SKUAD on Chess.com but has not completed its personal data on the community website. Personal data is kept private so staff can identify the player and match their identity if the account is banned.",
    tandaTanyaJudul: "{jumlah} members have not completed their website data",
    tandaTanyaPenjelasan:
      "A question mark beside a name means the player is already a BLUNDER SKUAD member on Chess.com but has not re-registered on the website. Re-registration securely records identity data, supports tournament checks, and helps prevent banned players from returning with a new account.",
    lengkapiData: "Complete personal data on the website",
    sumber: "Member source:",
    sumberCatatan: "The public Chess.com roster refreshes at most every 12 hours.",
    memuat: "Loading data from Chess.com…",
    menyegarkan: "Refreshing the member list from Chess.com…",
    kosongKlub: "No members could be read from the Chess.com club yet.",
    aktivitasKlub: "Club activity",
    aktivitas: {
      weekly: "Weekly active",
      monthly: "Monthly active",
      all_time: "Previously active",
    },
    kosong1: "No members registered yet. Please ",
    kosong2: "register with your Chess.com account",
    kosong3: ".",
    no: "No.",
    foto: "Photo",
    nama: "Name",
    akunHilang: "account not found",
    gagal: "failed to load",
    panggilan: "Nickname",
    kota: "City",
    klub: "Club",
    kategoriUmur: "Age Category",
    bergabung: "Joined",
    wa: "WhatsApp",
    profilJudul: "Member Profile",
    tutup: "Close",
    lihatProfil: "Click to view profile",
    terkenaBan:
      "This account is barred from community activities. Check the committee note or Chess.com status.",
    tingkatanJudul: "Rating Group Levels",
    tingkatanRentang: "Rating Range",
    tingkatanKategori: "Player Category",
    tingkatanPenjelasan: "Ability Description",
    tingkatanBuka: "Click to open the rating levels",
    tingkatanTutup: "Click to collapse the rating levels",
    tingkatan: {
      beginner: {
        label: "Beginner",
        deskripsi: "Just starting the chess journey and learning the basic movement of the pieces.",
      },
      novice: {
        label: "Novice",
        deskripsi: "Starting to learn basic tactics, protect pieces, and reduce blunders.",
      },
      intermediate: {
        label: "Intermediate",
        deskripsi: "Able to build plans, calculate two to three moves, and understand basic openings.",
      },
      advanced: {
        label: "Advanced",
        deskripsi: "Shows consistent positional understanding, mature calculation, and rarely makes fatal errors.",
      },
      expert: {
        label: "Expert",
        deskripsi: "High-level skill with deep calculation, strict time management, and mental resilience.",
      },
      master: {
        label: "Master Level",
        deskripsi: "A very strong player with comprehensive ability at national tournament level.",
      },
      elite: {
        label: "Elite / Grandmaster",
        deskripsi: "The highest class, where professional chess players compete at the world level.",
      },
    },
    nextJudul: "Member Registration",
  },
  verifikasi: {
    judul: "Account Ownership Proof",
    penjelasan:
      "Prove that the Chess.com account you entered really belongs to you. This prevents other people from registering your account, and prevents anyone registering with someone else's account.",
    tombolLogin: "Sign in with Chess.com",
    catatanLogin:
      "You will be redirected to chess.com to sign in. We never see or store your password.",
    atau: "Or without signing in",
    tombolKode: "Verify via profile code",
    memproses: "Processing…",
    langkah1: "Open your Chess.com profile settings.",
    langkah2: "Set the Location field to this code:",
    langkah3:
      "Save your changes, then click the button below. Once verified, you may remove the code again.",
    bukaPengaturan: "Open Chess.com settings",
    sudahPasang: "I have added the code",
    memeriksa: "Checking profile…",
    belumTerbaca:
      "The code was not found yet. Make sure it is saved, then try again shortly.",
    isiUsernameDulu: "Please enter your Chess.com username first.",
    berhasil: "Account ownership verified:",
    ganti: "Change account",
  },
  pendaftaran: {
    judul: "Member Registration",
    parent: "Membership",
    deskripsi:
      "Complete your administrative details and verify your Chess.com account after joining the BLUNDER SKUAD club.",
    artikel: "Complete Member Details",
    intro:
      "The site's member list is automatically taken from the BLUNDER SKUAD club roster on Chess.com. Complete this form after your account is in the club for verification and additional administration. The system ensures one person uses one account, and accounts closed by Chess.com for fair play violations cannot take part in community activities.",
    klubWajibJudul: "Join the club first",
    klubWajibIsi:
      "Your username must already be a BLUNDER SKUAD member on Chess.com. The Chess.com roster can take up to 12 hours to refresh.",
    gabungKlub: "Open the BLUNDER SKUAD club on Chess.com",
    label: "Chess.com Username",
    placeholder: "e.g.: hikaru",
    wajib: "Enter your Chess.com username.",
    memeriksa: "Checking Chess.com account…",
    daftar: "Register",
    nextJudul: "Membership List",
    linkDaftar: "membership list",

    privasiJudul: "Your personal data is safe",
    privasiIsi:
      "Your full name, phone/WhatsApp number, and DANA number are stored only in the committee's records and are never shown on the site. Only your nickname, city, and Chess.com statistics are public. We use this data to verify that each person holds only one membership.",

    grupAkun: "Chess.com Account",
    grupDiri: "Personal Details",
    grupKontak: "Contact & Payment",

    catatanUsername:
      "Use the username or chess.com/member/yourname profile link that has joined BLUNDER SKUAD.",

    labelNama: "Full Name",
    phNama: "e.g.: Budi Santoso",
    catatanNama: "As per official ID, for certificates and tournament prizes.",

    labelPanggilan: "Nickname",
    phPanggilan: "e.g.: Budi",
    catatanPanggilan: "Used by the committee for administration and tournaments.",

    labelLahir: "Date of Birth",
    catatanLahir: "Used to determine your tournament age category.",
    kategori: "Category",
    tahun: "years old",

    labelKota: "City of Origin",
    phKota: "e.g.: Medan",
    catatanKota: "For regional grouping in the inter-community league.",

    labelHp: "Phone / WhatsApp Number",
    phHp: "e.g.: 0812-3456-7890",
    catatanHp:
      "An active WhatsApp number, for tournament invitations and verification.",
    terbaca: "Read as",

    labelDana: "DANA Number",
    phDana: "leave blank if same as phone number",
    catatanDana: "For sending tournament prizes.",

    labelEmail: "Email",
    phEmail: "e.g.: budi@email.com",
    catatanEmail: "For official announcements from the staff.",

    labelKlub: "Club / Home Community",
    phKlub: "e.g.: Medan Chess Club",
    catatanKlub: "If you already belong to another club.",

    setuju:
      "I declare that the data above is correct, that this is my only account in the community, and I agree to the Community Code of Ethics — including the prohibition on using engine assistance.",

    periksaIsian: "Please review the fields marked in red.",
    galatUsername: "Chess.com username is required.",
    galatNama: "Enter your full name (at least two words).",
    galatPanggilan: "Nickname is required.",
    galatHp: "Invalid phone/WhatsApp number. Example: 0812-3456-7890.",
    galatDana: "Invalid DANA number.",
    galatKota: "City of origin is required.",
    galatLahir: "Date of birth is required.",
    galatLahirAneh: "That date of birth is not plausible.",
    galatEmail: "Invalid email format.",
    galatSetuju: "You must agree to the community code of ethics.",
  },
  syarat: {
    judul: "Terms & Conditions",
    deskripsi:
      "Operational guidelines and membership terms of the Blunder Skuad chess community.",
    nextJudul: "Community Code of Ethics",
  },
  kodeEtik: {
    judul: "Community Code of Ethics",
    deskripsi:
      "Fair play, integrity, and etiquette that apply at the board, online, and in discussion spaces.",
    artikel: "Community Policy",
    nextJudul: "Frequently Asked Questions",
  },
  pertanyaan: {
    judul: "Frequently Asked Questions",
    deskripsi:
      "A practical guide to membership, playing platforms, tournament formats, and Blunder Skuad community policies.",
    artikel: "Frequently Asked Questions",
    nextJudul: "Contact Us",
  },
  turnamen: {
    judul: "Tournaments",
    deskripsi:
      "Community competition calendar: monthly, seasonal league, open, and inter-community.",
    nextJudul: "Monthly Tournament",
  },
  turnamenBulanan: {
    judul: "Monthly Tournament",
    deskripsi:
      "A five-round Swiss tournament held every month for members and guests.",
    artikel: "Brief Rules",
    p1: "The Monthly Tournament uses a 5-round Swiss system. The standard time control is 15+10 (long blitz). Groups are split if there are more than 40 participants.",
    l1: "Registration closes the day before at 9:00 PM WIB.",
    l2: "Active members receive a discount on the administrative fee.",
    l3: "Results are announced on the Announcements page the same evening.",
    p2: "The current month's schedule is announced on the member channel and the Announcements page.",
    nextJudul: "Seasonal League",
  },
  ligaMusiman: {
    judul: "Seasonal League",
    deskripsi:
      "Three competition seasons a year with a running standings table, not a one-off event.",
    artikel: "Seasons and Format",
    p1: "The Seasonal League is divided into Season I (January–April), Season II (May–August), and Season III (September–December). Each player plays a minimum of six games to enter the official standings.",
    p2: "Points are counted as 1 for a win, ½ for a draw, and 0 for a loss. Tie-breaks use Sonneborn-Berger, then head-to-head results.",
    p3: "Season champions receive a direct invitation to the Open Tournament final at year's end.",
    nextJudul: "Open Tournament",
  },
  turnamenTerbuka: {
    judul: "Open Tournament",
    deskripsi:
      "Open events for the general public, including formats reported to the rating system when requirements are met.",
    artikel: "Who It's For",
    p1: "The Open Tournament accepts participants from outside the community. It is a platform to bring Medan chess players together with guests from other cities, while testing members' readiness on a busier stage.",
    p2: "When the number of rated players is sufficient, the organizers may submit a rating report in accordance with federation regulations. This information is always stated in each event's prospectus.",
    nextJudul: "Inter-Community League",
  },
  ligaAntar: {
    judul: "Inter-Community League",
    deskripsi:
      "Team matches against other communities and clubs in Sumatra and online.",
    artikel: "Team Format",
    p1: "The Inter-Community League is played in a team format of 4 boards + 1 reserve. A club may field more than one team when the quota allows.",
    p2: "Invitations to partner communities are sent by the Tournament Division. Communities wishing to issue a challenge can write to info@komunitascatur.or.id.",
    nextJudul: "Media & Information",
  },
  program: {
    judul: "Our Programs",
    deskripsi:
      "Development programs of the Indonesia Chess Community: from regular classes and training sessions to the chess learning guide.",
    artikel: "Program Overview",
    p1: "The Indonesia Chess Community offers a range of development programs designed so that every member has a clear path to grow — from those just learning the board to those chasing titles. All activities run regularly, both offline at the Medan secretariat and online through the BLUNDER SKUAD club on Chess.com, so members in any city can take part.",
    p2: "The six programs below complement one another: starting with tiered classes to build the fundamentals, personal mentoring, early-age coaching, self-study resources, and finally a stage to show one's skill and sharpen tactics. Schedules, registrations, and changes to the terms are always announced on the Announcements page and in the member channel; official information comes only from those channels and the email info@komunitascatur.or.id.",
    programJudul: "Featured Programs",
    kartu: {
      kelas: {
        judul: "Tiered Classes & Training",
        deskripsi:
          "Every player starts with the smallest piece. Tiered classes guide members from learning how the pieces move, the basics of openings, to endgame patterns — adapted to each player's level.",
      },
      clinic: {
        judul: "Coaching Clinic",
        deskripsi:
          "Intensive mentoring with coaches and titled players. Members' games are analyzed one by one to find weaknesses, sharpen thinking, and leap to the next level of strength.",
      },
      sekolah: {
        judul: "Chess School",
        deskripsi:
          "Partnerships with schools to introduce chess early as a way to train focus, patience, and strategic thinking. The curriculum is child-friendly yet structured.",
      },
      panduan: {
        judul: "Self-Study Guide",
        deskripsi:
          "A solid foundation you can learn anytime. The How to Play Chess page offers a step-by-step guide from the pieces to advanced training patterns.",
      },
      simultan: {
        judul: "Simultaneous & Blindfold",
        deskripsi:
          "The showcase of our best players. Simultaneous and blindfold exhibitions are held on the community's major days to test their strength while entertaining members.",
      },
      tekaTeki: {
        judul: "Tactics Puzzles",
        deskripsi:
          "Thousands of checkmate puzzles to sharpen your daily tactical instincts. Short, consistent practice builds far more than long theory without application.",
      },
    },
    h1: "Self-Study Guide and Practice",
    p3a: "For members who want to learn or revisit the fundamentals, the site provides the",
    p3b: "page as a complete guide from the pieces to advanced training routines, and the",
    p3c: "page with 4,462 checkmate puzzles for daily tactics practice.",
  },
  bermainCatur: {
    judul: "Play Chess Online",
    slogan: "Learn, Play, and Grow Together",
    p1: "Chess combines classic strategy with modern thinking habits. Here, everyone — from players who are new to the board to experienced ones — can play and grow at their own pace.",
    p2: "Pick your skill level to start right away, or explore the community's coaching programs. Everything is free for members.",
    mainkan: "Play now",
    daftar: "Register",
    popupJudul: "Play Chess Online",
    popupTanya: "What is your chess skill level?",
    popupBantuan:
      "Pick one level to begin. Your progress is automatically recorded once you become a member.",
    tingkatBaruJudul: "New to Chess",
    tingkatBaruIsi:
      "A step-by-step introduction to the board, piece moves, and the rules.",
    tingkatPemulaJudul: "Beginner",
    tingkatPemulaIsi:
      "Light tactics puzzles to build safe, careful thinking habits.",
    tingkatMenengahJudul: "Intermediate",
    tingkatMenengahIsi:
      "Opening and middle-game practice to build neater plans.",
    tingkatMahirJudul: "Advanced",
    tingkatMahirIsi:
      "Analysis board and high-level puzzles to sharpen calculation through the endgame.",
    f1Judul: "Why play chess with the Indonesia Chess Community?",
    f1P:
      "A community is more than a place to compete — it is a space to learn and grow together. Here is what you can expect:",
    f1Item1Judul: "Free chess for all ages",
    f1Item1Isi: "play and learn without charge, from children to seniors.",
    f1Item2Judul: "Practice that adapts to your level",
    f1Item2Isi:
      "tiered classes and coaching clinics follow each player's skill.",
    f1Item3Judul: "Become a stronger player",
    f1Item3Isi:
      "games, analysis, and feedback build critical thinking habits.",
    f1Item4Judul: "Strategy built step by step",
    f1Item4Isi:
      "from piece moves to deep endgame patterns, all the way up.",
    f1Item5Judul: "Play online against members or the engine",
    f1Item5Isi:
      "light practice games are available every day in the club and on the community board.",
    f2Judul: "Sharpen skills and strategic thinking",
    f2P: "Every game trains your ability to read a position, build a plan, and make decisions. Regular, gradual practice grows those skills quietly — from simple thinking into ever-deeper strategy.",
    f3Judul: "Technology for personal practice",
    f3P: "The interactive board and puzzle bank on this site bring training that adapts to your needs. Feedback from the engine helps you understand every mistake and improve the next move.",
    f4Judul: "Building community together",
    f4P1:
      "By joining, you become part of a network of players across many cities. Sharing strategies, reminding each other of schedules, and competing healthily bring the community closer.",
    f4P2:
      "The community also opens room to collaborate with schools and other clubs so chess becomes better known and easier for everyone to access.",
    f5Judul: "Chess for everyday life",
    f5P: "The habits trained on the board — patience, analysis, and decision-making — are useful beyond the game. Many members feel the benefit when facing challenges at work or school.",
    f6Judul: "A space to grow together",
    f6P1:
      "We provide a clear path to improve: start at the bottom, rise to a higher league, and compete on ever-bigger stages.",
    f6P2:
      "Training programs, tournaments, and shared spaces are constantly renewed so the community stays alive and useful for every member.",
    f6P3: "Start today and see how far your chess journey takes you.",
  },
  tipsTekaTeki: {
    judul: "Chess Puzzles & Tips",
    deskripsi:
      "A look at the puzzles: moves-by-rating data and position analysis, before you enter the tactics board.",
    artikel: "Chess Puzzle Training",
    paragraf1:
      "Maia builds its puzzles from an understanding of how millions of players improve. With Maia puzzles, you can measure your skill, focus on the gaps in your understanding, and turn hard-to-find ideas into habits.",
    paragraf2:
      "Every puzzle comes with data showing how players of different ratings respond to the position, so your training stays focused and effective.",
    mulai: "Start Your Training Session",
    demoJudul: "Tactical Puzzle",
    demoLevel: "Intermediate",
    demoTantangan: "Find the best move in this tactical position",
    grafikJudul: "Moves by Rating",
    grafikSumbuY: "Bintang Toba Probability",
    analisisJudul: "Position Analysis",
    analisisBag1:
      "Careful — this position is very dangerous! It is easy to fall for tempting mistakes like {x}.",
    analisisBag2:
      "Only {x} grants an advantage, and it is hard for human players to find.",
    langkahTerbaik: "Best Move",
    kesalahanUmum: "Common Mistake",
    kesalahanLain: "Other Mistakes",
    kontenHanyaId:
      "The example content below is only available in Indonesian. Switch the language to Bahasa Indonesia to read it in full.",
  },
  bukuPembukaan: {
    judul: "Openings",
    deskripsi:
      "A look at the opening book: the opening name and its ECO code appear automatically as moves are played on the free board.",
    artikel: "Opening Book: Know Your Openings",
    paragraf1:
      "Play moves on the free board and the opening book instantly recognizes the opening name along with its ECO code — from the Ruy Lopez and the Sicilian Najdorf to the Queen's Gambit.",
    paragraf2:
      "Complete with suggested next moves and a catalog of more than 3,300 opening names from lichess data (CC0 license).",
    buka: "Open the Opening Book",
    demoJudul: "Opening Book",
    demoTantangan: "The opening name appears automatically once the position is recognized",
    infoTeks:
      "After {x}, the opening book instantly recognizes this position as {label}.",
    kontenHanyaId:
      "The example content below is only available in Indonesian. Switch the language to Bahasa Indonesia to read it in full.",
  },

  caraBermain: {
    judul: "How to Play Chess",
    deskripsi:
      "A complete guide to the pieces, basic rules, tactics, strategy, openings, endgames, and training routines for reaching master-level rating.",
    lead:
      "This guide is arranged step by step: from the pieces and basic rules, through tactics, strategy, openings, and endgames, to training routines for steadily improving your rating.",
    labelArtikel: "Complete Guide",
    daftarIsi: "Table of Contents",
    bab: "Chapter",
    gagalMuat:
      "Failed to load the guide. Check your internet connection, then reload this page.",
    kontenHanyaId:
      "This guide is currently only available in Indonesian. Switch the language to Bahasa Indonesia to read it in full.",
    babBidak: "Pieces & Their Values",
    babDasar: "Rules & Fundamentals",
    babPemula: "Beginner Level",
    babMenengah: "Intermediate Level",
    babStrategi: "Strategy & Positional Play",
    babLanjut: "Advanced Level",
    babMaster: "Master Level",
    babPenutup: "Closing",
    babMalas:
      "This chapter loads when you open it to keep the page fast.",
    memuatBab: "Loading chapter…",
    muatBab: "Load this chapter",
  },
  media: {
    judul: "Media & Information",
    deskripsi:
      "The official channels for Indonesia Chess Community news, announcements, and gallery.",
    artikel: "One Official Source",
    p1: "All official community information is released only through this channel and the email info@komunitascatur.or.id. Beware of tournament invitations or collections not listed on the Announcements page.",
    p2: "The available channels are as follows:",
    l1: "activity reports, interviews, and tournament coverage.",
    l2: "photos of secretariat, class, and match activities.",
    nextJudul: "Community News",
  },
  berita: {
    judul: "Community News",
    deskripsi: "Coverage of activities, match results, and member stories.",
    artikel: "Latest",
    n1a: "August 12, 2026 — August Monthly Tournament followed by 64 players.",
    n1b: "A new participation record for an internal event. Group A was won by a junior player from the Medan chapter.",
    n2a: "July 28, 2026 — Pawn structure coaching clinic with a guest coach.",
    n2b: "A 110-minute online session covering the Isolated Queen Pawn and how to plan a central break.",
    n3a: "December 10, 2025 — The community's 10th anniversary celebrated with a simul.",
    n3b: "Twenty simul boards were opened to students. The event closed with the visual identity renewal.",
  },
  pengumuman: {
    judul: "Announcements",
    deskripsi:
      "Official notices: schedules, registration, and changes to terms.",
    artikel: "Currently in Effect",
    p1a: "Registration for the September Monthly Tournament",
    p1b: " is open until August 31, 2026 at 9:00 PM WIB.",
    p2a: "Secretariat holiday",
    p2b: " on August 17, 2026. Offline classes are moved to online sessions.",
    p3a: "Inter-Community League team call-ups",
    p3b: " will be announced via member email on August 20, 2026.",
    nextJudul: "Gallery",
  },
  galeri: {
    judul: "Gallery",
    deskripsi: "Photos of classes, matches, and community anniversary celebrations.",
    artikel: "Documentation",
    p1: "Photos are selected from the Media Division archive. For reuse outside the community channels, contact public relations first.",
    img1Alt: "Routine Medan secretariat activities",
    img1Caption: "Routine community activities at the Medan secretariat, 2025.",
    img2Alt: "Community values",
    img2Caption: "The values upheld by community members in every match.",
    img3Alt: "2024 activity archive",
    img3Caption: "Documentation of community activities, 2024.",
  },
  hubungi: {
    judul: "Contact Us",
    deskripsi: "Medan secretariat, official email, and message form.",
    sekretariat: "Secretariat",
    alamat: "Address: Indonesia Chess Community Secretariat, Jl. Gatot Subroto No. 11-13, Medan 20152, North Sumatra, Indonesia",
    jam: "Offline visiting hours: Saturday 9:00 AM–4:00 PM WIB, except on holidays announced on the Announcements page.",
    kirimPesan: "Send a Message",
    terkirim: "Message sent. We reply on business days.",
    nama: "Name",
    surel: "Email",
    pesan: "Message",
    kirim: "Send",
  },
  karir: {
    judul: "Careers",
    deskripsi: "Opportunities to contribute with the Indonesian Chess Community.",
    artikel: "Open Positions",
    l1a: "Media Division Volunteer",
    l1b: " — document activities and manage information channels.",
    l2a: "Chess School Assistant Coach",
    l2b: " — assist offline classes at the Medan chapter.",
    l3a: "Secretariat Staff (part-time)",
    l3b: " — help with member administration and tournament registration.",
    kirim:
      "Send your application to info@komunitascatur.or.id with the position as the subject.",
    nextJudul: "Contact Us",
  },
  pengadaan: {
    judul: "Procurement",
    deskripsi: "Goods and services procurement information for the Indonesian Chess Community.",
    artikel: "Goods & Services Procurement",
    p1: "This page is the initial framework for the Indonesian Chess Community's procurement page.",
    p2: "Complete content on the procurement of goods and services will be added later.",
  },
  strukturGrupCatur: {
    judul: "Chess Group Structure",
    deskripsi:
      "The community's chess group structure: board, organization, and membership.",
  },
  pengurus: {
    judul: "Board",
    deskripsi: "The board of the Indonesian Chess Community.",
    peran: {
      "super-admins": "Super Admins",
      admins: "Admins",
      "event-coordinators": "Event Coordinators",
    },
    artikel: "BLUNDER SKUAD Staff",
    p1: "Meet the staff who manage the club, support its members, and coordinate BLUNDER SKUAD activities on Chess.com.",
    bergabung: "Joined",
    rating: "Rating",
    belumDinilai: "Unrated",
    bukaProfil: "Open Chess.com profile",
    sumber: "Data source:",
    diperbarui: "updated August 17, 2026",
  },
  strukturOrganisasiCatur: {
    judul: "Organization Structure",
    deskripsi: "The organizational structure chart of the Indonesian Chess Community.",
    artikel: "BLUNDER SKUAD Organization Structure",
    p1: "The organization structure shows the relationship between club staff and members. Staff assignments follow the public BLUNDER SKUAD data on Chess.com, while the member count is synchronized from the club roster.",
    klub: "Chess Club",
    anggota: "Club Members",
    orang: "members",
    roster: "BLUNDER SKUAD roster",
    caption: "Super Admins lead the club management, supported by Admins and Event Coordinators in serving all BLUNDER SKUAD members.",
  },
  keberlanjutan: {
    judul: "Sustainability",
    deskripsi: "Rules, values, and commitments that keep the community healthy.",
    artikel: "Community Foundation",
    nextJudul: "Terms & Conditions",
  },
  tekaTeki: {
    judul: "Chess Puzzles",
    deskripsi:
      "Train your tactical instinct with 5,486 checkmate puzzles from real games in the Lichess puzzle database. Find checkmate in 1, 2, or 3 moves — hints are available when you get stuck.",
    memuat: "Loading puzzles…",
    gagalMuat:
      "Failed to load the puzzle data. Check your internet connection, then reload this page.",
    caraMain:
      "Click or drag one of your pieces to a destination square. Find the move that leads to checkmate — the opponent will reply automatically with its best defense.",
    caraTanda:
      "Analysis marks: right-click a square to mark it yellow; hold right-click and drag to draw an orange arrow; right-click a marked square (or left-click once on an empty square) to clear all marks. Hold Shift/Ctrl/Alt while marking for red/green/blue.",
    hapusSemuaTanda: "Clear All Marks",
    soal: "Puzzle #{n} of {total}",
    skakmat1: "Mate in One",
    skakmat2: "Mate in Two",
    skakmat3: "Mate in Three",
    mudah: "Easy",
    menengah: "Intermediate",
    sulit: "Hard",
    giliranPutih: "White to move",
    giliranHitam: "Black to move",
    promosiJudul: "Pawn Promotion",
    promosiPutih: "White promotes to…",
    promosiHitam: "Black promotes to…",
    promosiMenteri: "Queen",
    promosiBenteng: "Rook",
    promosiGajah: "Bishop",
    promosiKuda: "Knight",
    promosiBatal: "Cancel",
    petunjuk: "Hint",
    lewati: "Skip",
    selanjutnya: "Next",
    acak: "Random",
    sebelumnya: "Previous",
    berikutnya: "Next",
    salah: "Not quite — try again!",
    benar: "Nice! Correct move.",
    terpecahkan: "Checkmate.",
    sudahTerpecahkan: "Already solved",
    totalTerpecahkan: "Solved: {n}",
    langsungKe: "Jump to Puzzle",
    buka: "Open",
    rentangNomor: "Numbers 1 through {total}",
    nomorTidakValid: "Enter a number between 1 and {total}.",
    pengaturan: "Settings",
    tidakAdaSoal:
      "No puzzles match the current Level, Moves, Theme, and Side combination. Loosen one of the filters in Settings.",
    lanjutOtomatis: "Auto-advance",
    otomatisNyalakan: "Enable auto-advance",
    otomatisMatikan: "Disable auto-advance",
    labelSoal: "Puzzle",
    labelLevel: "Level",
    labelLangkah: "Moves",
    labelTema: "Theme",
    labelGiliran: "Side to move",
    labelBidak: "Pieces",
    semuaLevel: "All",
    sangatMudah: "Very easy",
    normal: "Medium",
    sangatSulit: "Very hard",
    semua: "All",
    langkahSatu: "1 move",
    langkahDua: "2 moves",
    langkahTiga: "3 moves",
    semuaTema: "All",
    temaGrupSkakmat: "Checkmate Patterns",
    temaGrupTaktik: "Tactical Motifs",
    temaGrupKarakteristik: "Characteristics",
    tema: {
      backRankMate: "Back-rank mate",
      smotheredMate: "Smothered mate",
      promotion: "Promotion",
      sacrifice: "Sacrifice",
      attraction: "Attraction (decoy)",
      deflection: "Deflection",
      pin: "Pin",
      fork: "Fork",
      discoveredAttack: "Discovered attack",
      doubleCheck: "Double check",
      hangingPiece: "Hanging piece",
      exposedKing: "Exposed king",
      endgame: "Endgame",
      middlegame: "Middlegame",
      opening: "Opening",
      master: "Master games",
      kingsideAttack: "Kingside attack",
      queensideAttack: "Queenside attack",
    },
    semuaGiliran: "All",
    hanyaPutih: "White only",
    hanyaHitam: "Black only",
    lanjutOtomatis: "Automatically load the next puzzle after each attempt",
    syzygyJudul: "Syzygy Tablebase",
    syzygyDidukung: "Powered by Lichess",
    engineDeskripsi:
      "Heads-up: turning on Stockfish reveals the evaluation and the best move for this position — it may spoil the puzzle. Best used to dissect the position after you've tried it yourself.",
    syzygyGagal:
      "This position cannot be analyzed by the tablebase (maximum 7 pieces).",
    syzygyMenganalisis: "Analyzing position…",
    syzygyDetail: "Details on Lichess ↗",
    syzygyCatatan: "Optimal result for the side to move.",
    syzygyKat: {
      win: "Win",
      "cursed-win": "Cursed win",
      draw: "Draw",
      "blessed-loss": "Blessed loss",
      loss: "Loss",
      unknown: "Unknown",
    },
    warnaPutih: "white",
    warnaHitam: "black",
    namaBidak: {
      p: "pawn",
      n: "knight",
      b: "bishop",
      r: "rook",
      q: "queen",
      k: "king",
    },
    ariaPetakKosong: "square {sq}, empty",
    ariaPetakBidak: "square {sq}, {warna} {bidak}",
    ingatPosisi:
      "Remember my last position — resume here when I return",
    posisiTersimpan: "Saved position: puzzle #{n}",
    ingatNonaktif: "Position is not being saved.",
    sumber:
      'Puzzles come from the Lichess puzzle database (real games, CC0 public domain), curated by <a href="https://delta-polder-indonesia.github.io/BintangToba/index.html" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:text-blue-800 underline">Bintang Toba (2026)</a>.',
    selanjutnyaJudul: "Learn How to Play Chess",
  },
  papan: {
    judul: "Chess Opening Explorer",
    remah: "Opening",
    penjelajah: "Opening Explorer",
    penjelajahDeskripsi:
      "Explore opening variations move by move and see the statistics for each continuation.",
    deskripsi:
      "A free chess board for analyzing and studying openings. Play moves and the opening name with its ECO code appears automatically.",
    memuat: "Loading opening book…",
    gagalMuat:
      "Failed to load the opening data. Check your internet connection, then reload this page.",
    setBidak: "Piece Set",
    flip: "Flip",
    undo: "Undo",
    reset: "Reset",
    salinPgn: "Copy PGN",
    tersalin: "PGN copied!",
    pembukaan: "Opening",
    variasi: "variations",
    petunjukAwal: "Start playing — the opening name appears once the position is known.",
    belumAdaNama: "No named opening for this position.",
    diLuarBuku: "Out of opening book",
    langkahBerikutnya: "Next moves",
    katalog: "Opening Catalog",
    pilihPembukaan: "Choose an opening…",
    cariPembukaan: "Search name or ECO code…",
    statistik: "Statistics",
    artikelJudul: "About This Opening",
    artikelMemuat: "Loading Wikibooks summary…",
    artikelKosong: "No Wikibooks summary for this opening yet.",
    artikelSelengkapnya: "Show more",
    artikelRingkas: "Show less",
    artikelBaca: "Read on Wikibooks",
    artikelOtomatis: "auto-translated",
    partai: "games",
    ratingRata: "avg rating",
    menangPutih: "White wins",
    menangHitam: "Black wins",
    seri: "Draws",
    tidakAdaHasil: "No openings found for “{q}”.",
    menampilkan: "Showing {n} of {total}",
    riwayat: "Move History",
    kosong: "No moves yet.",
    keAwal: "To start",
    mundur: "Back",
    maju: "Forward",
    keAkhir: "To end",
    pengaturan: "Settings",
    resetPapan: "Reset board",
    pengaturanPapan: "Board Settings",
    warnaPapan: "Board color",
    posisiFen: "FEN Position",
    daftarLangkahPgn: "Move List (PGN)",
    posisiAwal: "Starting position",
    salin: "Copy",
    tersalinSingkat: "Copied",
    tutup: "Close",
    daftarLangkah: "Moves List",
    basisData: "Opening Explorer Database",
    kolomLangkah: "Next Move",
    kolomJumlah: "# of Games",
    kolomPersen: "Winning percentage",
    kolomPutihSeriHitam: "White / Draw / Black",
    warnaBiru: "Blue",
    warnaCokelat: "Brown",
    warnaOranye: "Orange",
    warnaHijau: "Green",
    warnaAbu: "Grey",
    warnaBiruMuda: "Light blue",
    warnaBiruTua: "Dark blue",
    warnaKayu: "Wood",
    warnaMarmerCokelat: "Marble brown",
    warnaMarmerHijau: "Marble green",
    engine: "Engine Analysis",
    engineDeskripsi:
      "Turn on Stockfish — it runs entirely in your browser (one-time ~7 MB download) — to evaluate the position and see its best line.",
    engineNyalakan: "Turn on",
    engineMatikan: "Turn off",
    engineMemuat: "Loading engine… (one-time, ~7 MB)",
    engineMenganalisis: "Analyzing…",
    engineGagal: "Failed to load the engine. Check your internet connection, then try again.",
    engineCobaLagi: "Try again",
    engineCepat: "Fast",
    engineSeimbang: "Balanced",
    engineDalam: "Deep",
    engineKedalaman: "Analysis duration",
    engineKedalamanN: "Depth {n}",
    engineSkor: "Evaluation:",
    engineMate: "mate detected",
    engineBarisan: "Best line",
    engineMainkan: "Play",
    engineSelesai: "The game is over (checkmate/draw) — nothing left to analyze.",
    enginePanah: "The blue arrow on the board is the engine's suggestion.",
    warnaMetal: "Metal",
    sumber:
      'Opening data taken from lichess-org/chess-openings (CC0, public domain), work by <a href="https://delta-polder-indonesia.github.io/BintangToba/index.html" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:text-blue-800 underline">Bintang Toba (2025)</a>.',
  },
  t404: {
    judul: "Page Not Found",
    deskripsi: "The address you are looking for does not exist on this site.",
    kembali: "Go Back",
    p1: "Check the link again, or return to the ",
    p2: "home page",
    p3: ".",
  },
  landing: {
    sekilasLabel: "Blunder Skuad at a Glance",
    sekilasDesk:
      "For more than a decade, we have provided a place to play and learn for chess players from every corner of the country.",
    ketuaPengurus: "Chairman & Management",
    pustakaLabel: "Library",
    pustakaJudul: "Chess E-Books",
    pustakaDesk:
      "Learning materials written and curated by members, from opening fundamentals to theoretical endgames — all free to download.",
    kartu1Judul: "Chess School Program",
    kartu1Desk: "Explore the chess education and training programs we provide for everyone.",
    kartu2Judul: "Regular Tournaments",
    kartu2Desk: "Join our regular chess competitions to sharpen your skills and sportsmanship.",
    kartu3Judul: "Community & Networking",
    kartu3Desk: "Join a network of chess players from various regions across Indonesia.",
    kartu4Judul: "Chess Playing Guide",
    kartu4Desk: "Learn chess strategies, tactics, and tips from the basics to the advanced level.",
    sebelumnya: "Previous",
    selanjutnya: "Next",
    keberlanjutanDesk:
      "Indonesia Chess Community is committed to building a sustainable chess ecosystem through education, talent development, and a stronger network of players across Indonesia. We believe that consistency in programs and togetherness are the keys to advancing national chess.",
    harapanJudul: "Hope and Gratitude",
    harapanPembuka:
      "To all members, chess players, and friends of the community whom we respect and are proud of,",
    harapanP1:
      "As the community continues to grow, we would like to express our gratitude for the contributions and dedication given to building the national chess ecosystem — working hand in hand to bring regular tournaments, coaching classes, and room to grow for chess players from many regions.",
    harapanP2:
      "Our thanks also go to all members and the wider public for their support of the community. We exist for the benefit of many, and we remain committed to providing a place to play, learn, and grow for chess players across Indonesia.",
    harapanP3:
      "We also thank all partners and fellow chess communities who have collaborated with us in running competitions and taking part in advancing Indonesian chess.",
    harapanTutup1: "Thank you.",
    harapanTutup2: "Indonesia Chess Community,",
    harapanTutup3: "Play, Learn, and Grow Together",
    harapanNama: "The Blunder Skuad Committee",
    harapanJabatan: "Indonesia Chess Community",
    harapanAltFoto: "Illustration of a representative of Indonesia Chess Community",
    sorotanJudul: "Activity Highlights",
    sorotanDeskripsi:
      "A series of activities that support the community's chess development and achievements.",
    sorotan1Judul: "Regular Monthly Tournaments",
    sorotan1Isi:
      "Monthly Tournaments, Seasonal League, and Inter-Community League keep members' competitive flying hours high throughout the year.",
    sorotan2Judul: "Chess Puzzles",
    sorotan2Isi:
      "Regular chess puzzle practice sharpens calculation, tactics, and the ability to read positions for every player.",
    sorotan3Judul: "Opening Explorer",
    sorotan3Isi:
      "Explore an interactive chess opening library — browse opening variations move by move and learn opponent plans.",
    ajakanJudul: "Ready to Join the Indonesia Chess Community?",
    ajakanDeskripsi:
      "Complete your personal data and start joining tournaments, classes, and community activities.",
    ajakanTombol: "Register Now",
  },

  analisa: {
    remah: "Breadcrumb",
    judul: "Game Analysis",
    tagline: "Break down every move of your games with a local Stockfish",
    deskripsi:
      "Paste a PGN from Chess.com or Lichess, pull your game list by username, or start from a single FEN. Every move is labelled — brilliant, best, good, inaccuracy, blunder — with the engine's suggestion, an evaluation chart, and an accuracy summary for both players.",
    privasi: "All analysis runs in your browser — your games are never sent to a server.",
    basisDataJudul: "Chess Openings Database",
    basisDataIsi:
      "Enter an opening move on the board below to see its name and get statistics from human Grandmaster games for every move. Our database contains about 26 million moves from the latest chess Grandmaster games, giving you an idea of anything strong human chess players have played.",
    petunjuk:
      "Board shortcuts: left/right steps through the game, up/down jump to the first and last move, space plays automatically, Tab switches panel.",
    metaJudul: "Free Chess Game Analysis",
    metaDeskripsi:
      "Free PGN and FEN analysis with a local Stockfish engine: per-move labels, evaluation chart, player accuracy, and a practice board. Your games are never uploaded.",
    bukaAplikasi: "Open the analyzer",
    status: {
      judul: "Engine",
      mati: "Engine not loaded yet",
      memuat: "Downloading Stockfish (about 7 MB, only once)…",
      siap: "Stockfish is ready",
      gagal: "Engine failed to load",
      muat: "Load the engine now",
      cobaLagi: "Try again",
      tanpaWasm: "This browser has no WebAssembly support, so analysis cannot run.",
      peringatanWasm: "WebAssembly not supported",
      peringatanWasmIsi: "Engine analysis cannot run. Please update your browser.",
      peringatanLama: "The engine is taking a long time to load",
      peringatanLamaIsi: "If the app looks stuck, reload this page.",
    },
    kedalaman: {
      judul: "Analysis depth",
      cepat: "Quick",
      sedang: "Standard",
      dalam: "Deep",
      maksimal: "Maximum",
      petunjuk:
        "The engine on this site runs on a single thread, so high depth costs minutes on long games.",
    },
    mesin: {
      judul: "Chess engine",
      petunjuk: "Engines are served from this site's own files and run entirely on your device.",
    },
    tab: {
      analisa: "Analyze game",
      analisaBaru: "Analyze a new game",
      pilihPartai: "Choose game",
      ringkasan: "Summary",
      langkah: "Moves",
    },
    form: {
      judul: "Game format",
      tipe: "Analysis type",
      tempelPgn: "Paste your game PGN here",
      tempelFen: "Paste a FEN position here (leave empty for a free board)",
      namaPengguna: "Enter your {platform} username",
      daftarPartai: "List games",
      analisa: "Analyze",
      hint: "PGN may contain comments, bracketed variations, and clock settings. A FEN is a single line.",
      contohPgn: "Example: 1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 1-0",
      contohFen: "Example: rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
    },
    format: { chessCom: "Chess.com", lichessOrg: "Lichess.org", pgn: "PGN", fen: "FEN" },
    muat: {
      menganalisa: "Analyzing",
      menganalisaPartai: "Analyzing game",
      menyiapkanEngine: "Preparing engine",
      membatalkan: "Canceling",
      dibatalkan: "Analysis canceled",
      batal: "Cancel",
    },
    pemutar: {
      awal: "Go to first move",
      mundur: "One move back",
      maju: "One move forward",
      akhir: "Go to last move",
      putar: "Play automatically",
      jeda: "Pause",
    },
    papan: { balik: "Flip board", pengaturan: "Settings", promosi: "Choose promotion piece" },
    nav: {
      pengaturan: "Settings",
      kodeSumber: "Source Code",
      atribusi: "Attributions",
    },
    pemain: { putih: "White", hitam: "Black", anonim: "Unknown" },
    waktu: { jam: "{n} hours", menit: "{n} min", hari: "{n} days" },
    langkah: {
      palingBaik: "is best",
      tanpaLangkah: "No moves analyzed yet.",
      buku: "in the opening book",
      kosong: "Paste a PGN or play moves on the board to start analyzing.",
      jumlah: "{n} moves analyzed",
    },
    ringkasan: {
      judul: "Game summary",
      pemain: "Players",
      akurasi: "Accuracy",
      pembukaan: "Opening",
      menengah: "Middlegame",
      akhir: "Endgame",
      penilaian: "Rating breakdown",
      grafik: "Evaluation chart",
      tidakAda: "No summary yet — run an analysis first.",
      material: "Material advantage",
      cukupLangkah: "Not enough moves to evaluate this phase.",
      akurasiFase: "{fase}: accuracy {angka}%",
      ratingPartai: "Game rating",

    },
    grafik: {
      judul: "White advantage across the game",
      sumbu: "eval",
      petunjuk: "Click a section of the chart to jump to that move.",
      buku: "Book move",
    },
    hasil: { menangPutih: "White wins", menangHitam: "Black wins", seri: "Draw", berjalan: "Ongoing" },
    penilaian: {
      brilliant: "Brilliant",
      great: "Great",
      best: "Best",
      excellent: "Excellent",
      good: "Good",
      book: "Book",
      inaccuracy: "Inaccuracy",
      mistake: "Mistake",
      miss: "Miss",
      blunder: "Blunder",
      forced: "Forced",
      label: "Label",
      semua: "All",
      hanyaLabel: "Highlight by rating",
    },
    komentar: {
      brilliant: [
        "You found a brilliant way to sacrifice a piece.",
        "This sacrifice showcases a deep understanding of the position.",
        "A bold and exceptional sacrifice to gain a strategic edge.",
      ],
      great: [
        "You capitalized on your opponent's mistake effectively.",
        "This move takes full advantage of your opponent's error.",
        "A strong response to punish your opponent's oversight.",
      ],
      best: [
        "This has been the best move in this position.",
        "This was the most optimal move you could play here.",
        "The most precise and effective move for this scenario.",
      ],
      excellent: [
        "This was not the absolute best move, but it is just as strong.",
        "An excellent move that fits the demands of the position perfectly. It is not the best though.",
        "A top-tier choice, even if not the single best move.",
      ],
      good: [
        "This is not among the best moves, but it is still acceptable.",
        "An acceptable move, but there were better options.",
        "This move works, but it misses stronger alternatives.",
      ],
      inaccuracy: [
        "This move causes you to lose some advantage.",
        "This move weakens your overall position.",
        "An avoidable slip that leads to a worse situation.",
      ],
      blunder: [
        "This move loses significant advantage.",
        "This move significantly worsens your position.",
        "This move severely harms your position.",
      ],
      mate: [
        "Delivering checkmate is always a satisfying move.",
        "Checkmating your opponent is the ultimate goal.",
        "A decisive and final move to end the game.",
      ],
      mateIn: [
        "This is the right move to force an eventual checkmate.",
        "A precise move that guarantees a checkmate in the near future.",
        "This move sets up an unstoppable sequence to deliver checkmate.",
      ],
      delayMate: [
        "This move delays a checkmate, but your opponent is still being checkmated.",
        "You slowed down the checkmate sequence, but it is still guaranteed.",
        "A move that postpones the unavoidable checkmate you are delivering.",
      ],
      advanceMate: [
        "This decision shortens the path to your opponent's victory.",
        "You hastened the process of being checkmated with this move.",
        "This move brings your opponent closer to delivering checkmate.",
      ],
      loseAdvantage: [
        "This move causes you to lose the advantage you had.",
        "A costly error that sacrifices your winning edge.",
        "This move shifts the position from advantageous to equal or worse.",
      ],
      giveAdvantage: [
        "This move turns an equal position into a losing one.",
        "A mistake that hands the advantage to your opponent.",
        "This move creates a clear advantage for your opponent.",
      ],
      gettingMated: [
        "This move leads to an eventual forced checkmate by your opponent.",
        "A fatal error that guarantees your opponent will checkmate you.",
        "This move sets up an inevitable checkmate against you.",
      ],
      missMate: [
        "You missed an opportunity to force a checkmate, allowing your opponent to escape.",
        "A chance to secure a decisive checkmate was overlooked with this move.",
        "This move lets your opponent avoid a checkmate you could have forced.",
      ],
      missAdvantage: [
        "You missed an opportunity to gain an advantage.",
        "A key chance to improve your position was lost.",
        "This move overlooks a way to strengthen your position.",
      ],
      forced: [
        "There were no alternatives; this was the only possible move.",
        "You had no choice but to play this move.",
        "The situation left you with just one legal option, and this was it.",
      ],
    },
    komentarPartai: {
      menang: [
        "{menang} claimed victory after a well-fought game. Let's analyze {kalah}'s key mistakes and {menang}'s critical moves.",
        "A strong performance by {menang} secured the win. Let's explore how {kalah} could have defended better.",
        "{menang} emerged victorious, showcasing strategic play. Let's review the moments that defined {kalah}'s downfall.",
        "{menang} capitalized on key opportunities to claim victory. Let's analyze how {kalah} could have countered.",
      ],
      seri: [
        "Neither {menang} nor {kalah} managed to break through, resulting in a draw. Let's explore missed opportunities on both sides.",
        "The game stabilized into a draw after intense play from both {menang} and {kalah}. Let's revisit the critical decisions.",
        "An exciting battle between {menang} and {kalah} ended in a draw. Let's analyze what each side could have done differently.",
        "After a dynamic game, neither {menang} nor {kalah} could secure the win. Let's review the critical phases.",
      ],
      netral: [
        "An intense game between {menang} and {kalah}. Let's analyze the key moments that shaped the outcome.",
        "A well-fought battle between {menang} and {kalah}. Let's break down the critical moves and decisions.",
        "A complex and engaging game took place. Let's dive into the strategies employed by {menang} and {kalah}.",
        "Both players showcased their skills in an engaging match. Let's take a closer look at their key moves.",
      ],
    },
    formatLabel: {
      adalahLangkahA: "is a {label} move",
      adalahLangkahAn: "is an {label} move",
      adalah: "{label}",
    },
    partai: {
      judul: "{platform} games",
      memuat: "Fetching game list",
      batal: "Cancel",
      tidakAda: "No games found in this month.",
      mengambilApi: "Fetching data from the server",
      pemain: "Players",
      hasil: "Result",
      tanggal: "Date",
      hari: "Day",
      kelas: {
        bullet: "Bullet",
        blitz: "Blitz",
        rapid: "Rapid",
        classical: "Classical",
        unknown: "Untimed",
      },
      jumlahLangkah: "Moves",
      kontrolWaktu: "Time control",
      bulan: "Month",
      tahun: "Year",
      pilihPartai: "Pick a game to analyze it.",
      rated: "rated",
      kasual: "casual",
      ambilLagi: "Reload",
      kembali: "Back to the form",
      galatJaringan: "Could not fetch the game list",
      galatJaringanIsi: "Check your internet connection and try again.",
      galatPengguna: "User not found",
      galatPenggunaIsi: "Check the spelling of the username or your internet connection.",
      galatBatas: "The server may be limiting excessive requests",
      galatBatasIsi: "Slow down your request rate or wait before trying again.",
      analisisGagal: "Analysis failed",
    },
    galat: {
      pgnJudul: "Error reading PGN",
      pgnIsi: "Please provide a valid PGN (example: 1. e4 e5 2. Nf3 1-0).",
      fenJudul: "Error reading FEN",
      fenIsi: "A FEN needs all eight ranks, e.g. rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1.",
      engineJudul: "The engine failed to load",
      engineIsi: "The local engine file could not be downloaded. Reload the page, or pick another engine in settings.",
      analisisJudul: "Analysis stopped",
    },
    pengaturan: {
      judul: "Board settings",
      temaPapan: "Board theme",
      langkah: "Moves",
      penilaian: "Ratings",
      langkahTerbaik: "Best moves",
      tampilPanah: "Show arrows",
      panahSetelahLangkah: "Arrow after opponent's move",
      langkahLegal: "Show legal moves",
      animasi: "Animate moves",
      suara: "Board sounds",
      sorotLabel: "Highlight by rating",
      petunjuk: "These settings are stored in your browser only, not synced to an account.",
      tutup: "Close settings",
    },
    tema: {
      hijau: "Green",
      cokelat: "Brown",
      biru: "Blue",
      abu: "Gray",
      merah: "Red",
      ungu: "Purple",
      oranye: "Orange",
    },
    atribusi: {
      judul: "Attributions & license",
      pendahuluan:
        "The layout and rating logic of this page were ported from Brilliant-Chess (MIT, © 2025 Delo). The chess engine, worker loading, and all UCI communication use this site's own implementation.",
      bidak: "Chess pieces",
      bidakOleh: "Created by Cburnett, licensed CC-BY-SA-3.0.",
      pembukaan: "Opening book",
      pembukaanOleh: "Data derived from lichess-org/chess-openings, licensed CC0.",
      engine: "Stockfish",
      engineOleh: "stockfish.js distribution (GPL-3.0) — served from this site's /engines folder.",
      kode: "Ported source",
      kodeOleh: "MIT — source: github.com/wdeloo/Brilliant-Chess.",
      tutup: "Close",
    },
  },

};
