/**
 * Kamus Inggris (EN) · kelompok analisa — halaman Analisa (analisis langkah, komentar partai, panel engine).
 * Kunci dalam berkas: analisa.
 */

export const analisa = {
    remah: "Breadcrumb",
    judul: "Game Analysis",
    tagline: "Break down every move of your games with a local Stockfish",
    deskripsi:
      "Paste a PGN from Chess.com or Lichess, pull your game list by username, or start from a single FEN. Every move is labelled — brilliant, best, good, inaccuracy, blunder — with the engine's suggestion, an evaluation chart, and an accuracy summary for both players.",
    privasi: "All analysis runs in your browser — your games are never sent to a server.",
    basisDataJudul: "Chess Openings Database",
    basisDataIsi:
      "Enter an opening move on the board below to see its name and get statistics from human Grandmaster games for every move. Our database contains about 26 million moves from the latest chess Grandmaster games, giving you an idea of anything strong human chess players have played.",
    petunjuk:
      "Board shortcuts: left/right steps through the game, up/down jump to the first and last move, space plays automatically, Tab switches panel.",
    metaJudul: "Free Chess Game Analysis",
    metaDeskripsi:
      "Free PGN and FEN analysis with a local Stockfish engine: per-move labels, evaluation chart, player accuracy, and a practice board. Your games are never uploaded.",
    bukaAplikasi: "Open the analyzer",
    status: {
      judul: "Engine",
      mati: "Engine not loaded yet",
      memuat: "Downloading Stockfish (about 7 MB, only once)…",
      siap: "Stockfish is ready",
      gagal: "Engine failed to load",
      muat: "Load the engine now",
      cobaLagi: "Try again",
      tanpaWasm: "This browser has no WebAssembly support, so analysis cannot run.",
      peringatanWasm: "WebAssembly not supported",
      peringatanWasmIsi: "Engine analysis cannot run. Please update your browser.",
      peringatanLama: "The engine is taking a long time to load",
      peringatanLamaIsi: "If the app looks stuck, reload this page.",
    },
    kedalaman: {
      judul: "Analysis depth",
      cepat: "Quick",
      sedang: "Standard",
      dalam: "Deep",
      maksimal: "Maximum",
      petunjuk:
        "The engine on this site runs on a single thread, so high depth costs minutes on long games.",
    },
    mesin: {
      judul: "Game Review",
      petunjuk: "Engines are served from this site's own files and run entirely on your device.",
    },
    tab: {
      analisa: "Analyze game",
      analisaBaru: "Analyze a new game",
      pilihPartai: "Choose game",
      ringkasan: "Summary",
      langkah: "Moves",
    },
    form: {
      judul: "Game format",
      tipe: "Analysis type",
      tempelPgn: "Paste your game PGN here",
      tempelFen: "Paste a FEN position here (leave empty for a free board)",
      namaPengguna: "Enter your {platform} username",
      daftarPartai: "List games",
      analisa: "Analyze",
      hint: "PGN may contain comments, bracketed variations, and clock settings. A FEN is a single line.",
      contohPgn: "Example: 1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 1-0",
      contohFen: "Example: rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",

      dariAkun: "From account",
      dariAkunIsi: "Load every game from Chess.com or Lichess using a username.",
      situs: "Website",
      namaPenggunaLabel: "Username",
      wajibNama: "A username is required.",
      hintAkun: "Public name without spaces. Once selected, all game archives load into a single table.",
      hintPgn: "Paste the PGN notation; comments and variations in parentheses are allowed.",
      hintFen: "One line only. Leave empty to start from an empty board.",
    },
    format: { chessCom: "Chess.com", lichessOrg: "Lichess.org", pgn: "PGN", fen: "FEN" },

    panel: {
      kosongJudul: "No games loaded yet",
      kosongIsi: "Use the Accounts button on the left bar to load every game from Chess.com/Lichess, or import a game from PGN, FEN, or a game link.",
      atau: "or",
    },
    akun: {
      judul: "Add account",
      isi: "Pick a website and type a username. All of their game archives will load into a single table.",
      situs: "Website",
      nama: "Username",
      wajib: "A username is required.",
      tambah: "Add",
      batal: "Cancel",
      riwayat: "Previously used names",
    },
    basisData: {
      judul: "Game Database",
      subjudul: "Manage, search, and analyze all locally stored games without having to re-fetch from the API.",
      semuaKoleksi: "All Collections",
      semuaPlatform: "All Platforms",
      koleksi: "Collection / Account",
      jumlahPartai: "{jumlah} games stored",
      totalStatistik: "{total} games stored in database ({menang} wins, {kalah} losses, {seri} draws)",
      tersimpanLokal: "Stored in Database ({jumlah} games)",
      dimuatDariDb: "Instantly loaded from local Database ({jumlah} games)",
      tarikBaru: "Fetch latest from {platform}",
      tarikUlang: "Re-fetch from API",
      eksporPgn: "Export PGN",
      eksporPgnSukses: "PGN file successfully downloaded!",
      salinPgn: "Copy PGN",
      pgnTidakAda: "The PGN for this game could not be read.",
      pgnDisalin: "PGN successfully copied to clipboard!",
      hapusKoleksi: "Delete Collection",
      hapusPartai: "Delete Game",
      konfirmasiHapusKoleksi: "Delete collection {koleksi} ({jumlah} games) from database?",
      konfirmasiHapusPartai: "Delete this game from database?",
      konfirmasiHapusSemua: "Clear all game data from local database?",
      hapusSemua: "Clear Database",
      sinkronkan: "Sync",
      menyinkronkan: "Fetching latest data...",
      imporPgn: "Import PGN",
      imporPgnJudul: "Paste PGN to save into Database",
      imporPgnBatal: "Cancel",
      imporPgnSimpan: "Save to Database",
      imporSukses: "{jumlah} games successfully added to Database!",
      kosongJudul: "No Games in Database Yet",
      kosongIsi: "Games fetched from Chess.com or Lichess will be automatically stored here so you can open and analyze them anytime without waiting for the API.",
      bukaAkun: "Fetch from Chess.com / Lichess",
      analisaSekarang: "Analyze",
      filterHasil: "Result",
      filterWaktu: "Time Control",
      semuaHasil: "All Results",
      menang: "Win",
      kalah: "Loss",
      seri: "Draw",
      semuaWaktu: "All Speeds",
      cariPlaceholder: "Search player name, event, or PGN…",
      detail: "Game Details",
      tanggal: "Date",
      langkah: "Moves",
      pemain: "Players",
      hasilTabel: "Result",
      aksi: "Action",
      sebelumnya: "Previous",
      berikutnya: "Next",
      halaman: "Page {aktif} of {total}",
      tersimpanOtomatis: "Automatically saved to local Database",
      sumberDatabase: "Local Database",
      sumberApi: "Live API",
    },
    impor: {
      judul: "Import game",
      tipe: "Import type",
      pgn: "Paste PGN",
      fen: "Paste FEN",
      online: "Online",
      onlineLabel: "Game link",
      onlinePlaceholder: "https://www.chess.com/game/live/…  or  https://lichess.org/…",
      onlineBantu: "Paste a Chess.com or Lichess game link; its PGN is fetched and analyzed automatically.",
      ambil: "Fetch & analyze",
      analisa: "Analyze",
      memuat: "Fetching PGN…",
      galatTautan: "Unrecognized link. Use a Chess.com or Lichess game link.",
      galatAmbil: "Could not fetch the PGN from that link. Check your connection or paste the PGN directly.",
    },    muat: {
      menganalisa: "Analyzing",
      menganalisaPartai: "Analyzing game",
      menyiapkanEngine: "Preparing engine",
      membatalkan: "Canceling",
      dibatalkan: "Analysis canceled",
      batal: "Cancel",
    },
    pemutar: {
      awal: "Go to first move",
      mundur: "One move back",
      maju: "One move forward",
      akhir: "Go to last move",
      putar: "Play automatically",
      jeda: "Pause",
    },
    papan: { balik: "Flip board", pengaturan: "Settings", promosi: "Choose promotion piece" },
    nav: {
      pengaturan: "Settings",
      play: "Play",
      playKeterangan: "Back to the analysis board",
      baru: "New",
      baruKeterangan: "Start a new analysis — clears the board",
      baruKonfirmasi: "Sure? Press again",
      akun: "Accounts",
      database: "Database",
      impor: "Import game",
      kodeSumber: "Source Code",
      atribusi: "Attributions",
    },
    pemain: { putih: "White", hitam: "Black", anonim: "Unknown" },
    waktu: { jam: "{n} hours", menit: "{n} min", hari: "{n} days" },
    langkah: {
      palingBaik: "is best",
      tanpaLangkah: "No moves analyzed yet.",
      buku: "in the opening book",
      kosong: "Paste a PGN or play moves on the board to start analyzing.",
      jumlah: "{n} moves analyzed",
    },
    ringkasan: {
      judul: "Game summary",
      pemain: "Players",
      akurasi: "Accuracy",
      pembukaan: "Opening",
      menengah: "Middlegame",
      akhir: "Endgame",
      penilaian: "Rating breakdown",
      grafik: "Evaluation chart",
      tidakAda: "No summary yet — run an analysis first.",
      material: "Material advantage",
      cukupLangkah: "Not enough moves to evaluate this phase.",
      akurasiFase: "{fase}: accuracy {angka}%",
      ratingPartai: "Game rating",

    },
    grafik: {
      judul: "White advantage across the game",
      sumbu: "eval",
      petunjuk: "Click a section of the chart to jump to that move.",
      buku: "Book move",
    },
    hasil: { menangPutih: "White wins", menangHitam: "Black wins", seri: "Draw", berjalan: "Ongoing" },
    penilaian: {
      brilliant: "Brilliant",
      great: "Great",
      best: "Best",
      excellent: "Excellent",
      good: "Good",
      book: "Book",
      inaccuracy: "Inaccuracy",
      mistake: "Mistake",
      miss: "Miss",
      blunder: "Blunder",
      forced: "Forced",
      label: "Label",
      semua: "All",
      hanyaLabel: "Highlight by rating",
    },
    komentar: {
      brilliant: [
        "You found a brilliant way to sacrifice a piece.",
        "This sacrifice showcases a deep understanding of the position.",
        "A bold and exceptional sacrifice to gain a strategic edge.",
      ],
      great: [
        "You capitalized on your opponent's mistake effectively.",
        "This move takes full advantage of your opponent's error.",
        "A strong response to punish your opponent's oversight.",
      ],
      best: [
        "This has been the best move in this position.",
        "This was the most optimal move you could play here.",
        "The most precise and effective move for this scenario.",
      ],
      excellent: [
        "This was not the absolute best move, but it is just as strong.",
        "An excellent move that fits the demands of the position perfectly. It is not the best though.",
        "A top-tier choice, even if not the single best move.",
      ],
      good: [
        "This is not among the best moves, but it is still acceptable.",
        "An acceptable move, but there were better options.",
        "This move works, but it misses stronger alternatives.",
      ],
      inaccuracy: [
        "This move causes you to lose some advantage.",
        "This move weakens your overall position.",
        "An avoidable slip that leads to a worse situation.",
      ],
      blunder: [
        "This move loses significant advantage.",
        "This move significantly worsens your position.",
        "This move severely harms your position.",
      ],
      mate: [
        "Delivering checkmate is always a satisfying move.",
        "Checkmating your opponent is the ultimate goal.",
        "A decisive and final move to end the game.",
      ],
      mateIn: [
        "This is the right move to force an eventual checkmate.",
        "A precise move that guarantees a checkmate in the near future.",
        "This move sets up an unstoppable sequence to deliver checkmate.",
      ],
      delayMate: [
        "This move delays a checkmate, but your opponent is still being checkmated.",
        "You slowed down the checkmate sequence, but it is still guaranteed.",
        "A move that postpones the unavoidable checkmate you are delivering.",
      ],
      advanceMate: [
        "This decision shortens the path to your opponent's victory.",
        "You hastened the process of being checkmated with this move.",
        "This move brings your opponent closer to delivering checkmate.",
      ],
      loseAdvantage: [
        "This move causes you to lose the advantage you had.",
        "A costly error that sacrifices your winning edge.",
        "This move shifts the position from advantageous to equal or worse.",
      ],
      giveAdvantage: [
        "This move turns an equal position into a losing one.",
        "A mistake that hands the advantage to your opponent.",
        "This move creates a clear advantage for your opponent.",
      ],
      gettingMated: [
        "This move leads to an eventual forced checkmate by your opponent.",
        "A fatal error that guarantees your opponent will checkmate you.",
        "This move sets up an inevitable checkmate against you.",
      ],
      missMate: [
        "You missed an opportunity to force a checkmate, allowing your opponent to escape.",
        "A chance to secure a decisive checkmate was overlooked with this move.",
        "This move lets your opponent avoid a checkmate you could have forced.",
      ],
      missAdvantage: [
        "You missed an opportunity to gain an advantage.",
        "A key chance to improve your position was lost.",
        "This move overlooks a way to strengthen your position.",
      ],
      forced: [
        "There were no alternatives; this was the only possible move.",
        "You had no choice but to play this move.",
        "The situation left you with just one legal option, and this was it.",
      ],
    },
    komentarPartai: {
      menang: [
        "{menang} claimed victory after a well-fought game. Let's analyze {kalah}'s key mistakes and {menang}'s critical moves.",
        "A strong performance by {menang} secured the win. Let's explore how {kalah} could have defended better.",
        "{menang} emerged victorious, showcasing strategic play. Let's review the moments that defined {kalah}'s downfall.",
        "{menang} capitalized on key opportunities to claim victory. Let's analyze how {kalah} could have countered.",
      ],
      seri: [
        "Neither {menang} nor {kalah} managed to break through, resulting in a draw. Let's explore missed opportunities on both sides.",
        "The game stabilized into a draw after intense play from both {menang} and {kalah}. Let's revisit the critical decisions.",
        "An exciting battle between {menang} and {kalah} ended in a draw. Let's analyze what each side could have done differently.",
        "After a dynamic game, neither {menang} nor {kalah} could secure the win. Let's review the critical phases.",
      ],
      netral: [
        "An intense game between {menang} and {kalah}. Let's analyze the key moments that shaped the outcome.",
        "A well-fought battle between {menang} and {kalah}. Let's break down the critical moves and decisions.",
        "A complex and engaging game took place. Let's dive into the strategies employed by {menang} and {kalah}.",
        "Both players showcased their skills in an engaging match. Let's take a closer look at their key moves.",
      ],
    },
    formatLabel: {
      adalahLangkahA: "is a {label} move",
      adalahLangkahAn: "is an {label} move",
      adalah: "{label}",
    },
    partai: {
      judul: "{platform} games",
      memuat: "Fetching game list",
      batal: "Cancel",
      tidakAda: "No games found.",
      mengambilApi: "Fetching data from the server",
      pemain: "Players",
      hasil: "Result",
      tanggal: "Date",
      hari: "Day",
      cari: "Search players…",
      tidakCocok: "No games match your search.",
      legenda: "Result is relative to {pemain}.",
      jumlahPartai: "{jumlah} games",
      halaman: "Page {aktif} of {total}",
      sebelumnya: "Previous",
      berikutnya: "Next",
      memuatArsip: "Fetching {bulan} archive",
      arsipGagal: "{jumlah} archives could not be loaded. Some games might be missing.",
      kelas: {
        bullet: "Bullet",
        blitz: "Blitz",
        rapid: "Rapid",
        classical: "Classical",
        unknown: "Untimed",
      },
      jumlahLangkah: "Moves",
      kontrolWaktu: "Time control",
      bulan: "Month",
      tahun: "Year",
      pilihPartai: "Pick a game to analyze it.",
      rated: "rated",
      kasual: "casual",
      ambilLagi: "Reload",
      kembali: "Back to the form",
      galatJaringan: "Could not fetch the game list",
      galatJaringanIsi: "Check your internet connection and try again.",
      galatPengguna: "User not found",
      galatPenggunaIsi: "Check the spelling of the username or your internet connection.",
      galatBatas: "The server may be limiting excessive requests",
      galatBatasIsi: "Slow down your request rate or wait before trying again.",
      analisisGagal: "Analysis failed",
    },
    galat: {
      pgnJudul: "Error reading PGN",
      pgnIsi: "Please provide a valid PGN (example: 1. e4 e5 2. Nf3 1-0).",
      fenJudul: "Error reading FEN",
      fenIsi: "A FEN needs all eight ranks, e.g. rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1.",
      engineJudul: "The engine failed to load",
      engineIsi: "The local engine file could not be downloaded. Reload the page, or pick another engine in settings.",
      analisisJudul: "Analysis stopped",
    },
    pengaturan: {
      judul: "Board settings",
      temaPapan: "Board theme",
      langkah: "Moves",
      penilaian: "Ratings",
      langkahTerbaik: "Best moves",
      tampilPanah: "Show arrows",
      panahSetelahLangkah: "Arrow after opponent's move",
      langkahLegal: "Show legal moves",
      animasi: "Animate moves",
      suara: "Board sounds",
      sorotLabel: "Highlight by rating",
      mesin: "Engine",
      petunjuk: "These settings are stored in your browser only, not synced to an account.",
      tutup: "Close settings",
    },
    tema: {
      hijau: "Green",
      cokelat: "Brown",
      biru: "Blue",
      abu: "Gray",
      merah: "Red",
      ungu: "Purple",
      oranye: "Orange",
    },
    atribusi: {
      judul: "Attributions & license",
      pendahuluan:
        "The layout and rating logic of this page were ported from Brilliant-Chess (MIT, © 2025 Delo). The chess engine, worker loading, and all UCI communication use this site's own implementation.",
      judulDaftar: "Attributions and License",
      bidak: "Chess pieces",
      bidakOleh: "Created by Cburnett, licensed CC-BY-SA-3.0.",
      pembukaan: "Opening book",
      pembukaanOleh: "Data derived from lichess-org/chess-openings, licensed CC0.",
      engine: "Stockfish",
      engineOleh: "stockfish.js distribution (GPL-3.0) — served from this site's /engines folder.",
      kode: "Ported source",
      kodeOleh: "MIT — source: github.com/wdeloo/Brilliant-Chess.",
      desain: "Page layout",
      desainOleh:
        "The Program Kami layout pattern (large heading + card grid) follows prompt.md from this repository, licensed MIT.",
      suara: "Board sounds",
      suaraOleh:
        "The MP3 files under /SoundChess come from the Chess.com, LLC board sound set. Copyright remains with its owner; they are used as-is for community practice, unmodified and with no claim of ownership.",
      logo: "Site logos",
      logoOleh:
        "Trademarks of their respective owners (Chess.com, LLC and lichess.org); used here only to identify accounts via links to the official sites.",
      sosialJudul: "Copyright infringement",
      sosialDeskripsi:
        "We respect the intellectual property rights of others. If you believe your work has been used on our site without permission, please contact our team via the links below. Include proof of ownership and links to the content in question.",
      tutup: "Close",
    },
  }
