/**
 * Kamus Inggris (EN) · kelompok papan — halaman Papan Interaktif (papan bebas, explorer pembukaan, komentator).
 * Kunci dalam berkas: papan.
 */

import { komentatorPapan } from "./komentator.js";

export const papan = {
    judul: "Chess Opening Explorer",
    remah: "Opening",
    penjelajah: "Opening Explorer",
    penjelajahDeskripsi:
      "Explore opening variations move by move and see the statistics for each continuation.",
    deskripsi:
      "A free chess board for analyzing and studying openings. Play moves and the opening name with its ECO code appears automatically.",
    memuat: "Loading opening book…",
    gagalMuat:
      "Failed to load the opening data. Check your internet connection, then reload this page.",
    suara: "Board sounds",
    suaraNyala: "Sound on — click to mute",
    suaraMati: "Sound off — click to unmute",
    setBidak: "Piece Set",
    flip: "Flip",
    undo: "Undo",
    reset: "Reset",
    salinPgn: "Copy PGN",
    tersalin: "PGN copied!",
    pembukaan: "Opening",
    variasi: "variations",
    petunjukAwal: "Start playing — the opening name appears once the position is known.",
    belumAdaNama: "No named opening for this position.",
    diLuarBuku: "Out of opening book",
    langkahBerikutnya: "Next moves",
    katalog: "Opening Catalog",
    pilihPembukaan: "Choose an opening…",
    cariPembukaan: "Search name or ECO code…",
    statistik: "Statistics",
    artikelJudul: "About This Opening",
    artikelMemuat: "Loading Wikibooks summary…",
    artikelKosong: "No Wikibooks summary for this opening yet.",
    artikelSelengkapnya: "Show more",
    artikelRingkas: "Show less",
    artikelBaca: "Read on Wikibooks",
    artikelOtomatis: "auto-translated",
    partai: "games",
    ratingRata: "avg rating",
    menangPutih: "White wins",
    menangHitam: "Black wins",
    seri: "Draws",
    tidakAdaHasil: "No openings found for “{q}”.",
    menampilkan: "Showing {n} of {total}",
    riwayat: "Move History",
    kosong: "No moves yet.",
    keAwal: "To start",
    mundur: "Back",
    maju: "Forward",
    keAkhir: "To end",
    pengaturan: "Settings",
    resetPapan: "Reset board",
    pengaturanPapan: "Board Settings",
    warnaPapan: "Board color",
    posisiFen: "FEN Position",
    daftarLangkahPgn: "Move List (PGN)",
    posisiAwal: "Starting position",
    salin: "Copy",
    tersalinSingkat: "Copied",
    tutup: "Close",
    daftarLangkah: "Moves List",
    basisData: "Opening Explorer Database",
    kolomLangkah: "Next Move",
    kolomJumlah: "# of Games",
    kolomPersen: "Winning percentage",
    kolomPutihSeriHitam: "White / Draw / Black",
    warnaBiru: "Blue",
    warnaCokelat: "Brown",
    warnaOranye: "Orange",
    warnaHijau: "Green",
    warnaAbu: "Grey",
    warnaBiruMuda: "Light blue",
    warnaBiruTua: "Dark blue",
    warnaKayu: "Wood",
    warnaMarmerCokelat: "Marble brown",
    warnaMarmerHijau: "Marble green",
    engine: "Engine Analysis",
    engineDeskripsi:
      "Turn on Stockfish — it runs entirely in your browser (one-time ~7 MB download) — to evaluate the position and see its best line.",
    engineNyalakan: "Turn on",
    engineMatikan: "Turn off",
    engineMemuat: "Loading engine… (one-time, ~7 MB)",
    engineMenganalisis: "Analyzing…",
    engineGagal: "Failed to load the engine. Check your internet connection, then try again.",
    engineCobaLagi: "Try again",
    engineCepat: "Fast",
    engineSeimbang: "Balanced",
    engineDalam: "Deep",
    engineKedalaman: "Analysis duration",
    engineKedalamanN: "Depth {n}",
    engineSkor: "Evaluation:",
    engineMate: "mate detected",
    engineBarisan: "Best line",
    engineMainkan: "Play",
    engineSelesai: "The game is over (checkmate/draw) — nothing left to analyze.",
    enginePanah: "The blue arrow on the board is the engine's suggestion.",
    enginePanahToggle: "Show engine suggestion arrow",
    warnaMetal: "Metal",
    komentator: komentatorPapan,
    sumber:
      'Opening data taken from lichess-org/chess-openings (CC0, public domain), work by <a href="https://delta-polder-indonesia.github.io/BintangToba/index.html" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:text-blue-800 underline">Bintang Toba (2025)</a>.',
  }
