/**
 * Kamus Inggris (EN) · kelompok tekaTeki — halaman Teka-Teki (soal skakmat + komentator teka-teki).
 * Kunci dalam berkas: tekaTeki.
 */

import { komentatorTekaTeki } from "./komentator.js";

export const tekaTeki = {
    judul: "Chess Puzzles",
    deskripsi:
      "Train your tactical instinct with 5,486 checkmate puzzles from real games in the Lichess puzzle database. Find checkmate in 1, 2, or 3 moves — hints are available when you get stuck.",
    memuat: "Loading puzzles…",
    gagalMuat:
      "Failed to load the puzzle data. Check your internet connection, then reload this page.",
    caraMain:
      "Click or drag one of your pieces to a destination square. Find the move that leads to checkmate — the opponent will reply automatically with its best defense.",
    caraTanda:
      "Analysis marks: right-click a square to mark it yellow; hold right-click and drag to draw an orange arrow; right-click a marked square (or left-click once on an empty square) to clear all marks. Hold Shift/Ctrl/Alt while marking for red/green/blue.",
    hapusSemuaTanda: "Clear All Marks",
    soal: "Puzzle #{n} of {total}",
    skakmat1: "Mate in One",
    skakmat2: "Mate in Two",
    skakmat3: "Mate in Three",
    mudah: "Easy",
    menengah: "Intermediate",
    sulit: "Hard",
    giliranPutih: "White to move",
    giliranHitam: "Black to move",
    promosiJudul: "Pawn Promotion",
    promosiPutih: "White promotes to…",
    promosiHitam: "Black promotes to…",
    promosiMenteri: "Queen",
    promosiBenteng: "Rook",
    promosiGajah: "Bishop",
    promosiKuda: "Knight",
    promosiBatal: "Cancel",
    petunjuk: "Hint",
    lewati: "Skip",
    selanjutnya: "Next",
    acak: "Random",
    sebelumnya: "Previous",
    berikutnya: "Next",
    salah: "Not quite — try again!",
    benar: "Nice! Correct move.",
    terpecahkan: "Checkmate.",
    sudahTerpecahkan: "Already solved",
    komentator: komentatorTekaTeki,
    totalTerpecahkan: "Solved: {n}",
    langsungKe: "Jump to Puzzle",
    buka: "Open",
    rentangNomor: "Numbers 1 through {total}",
    nomorTidakValid: "Enter a number between 1 and {total}.",
    pengaturan: "Settings",
    tidakAdaSoal:
      "No puzzles match the current Level, Moves, Theme, and Side combination. Loosen one of the filters in Settings.",
    lanjutOtomatis: "Auto-advance",
    otomatisNyalakan: "Enable auto-advance",
    otomatisMatikan: "Disable auto-advance",
    labelSoal: "Puzzle",
    labelLevel: "Level",
    labelLangkah: "Moves",
    labelTema: "Theme",
    labelGiliran: "Side to move",
    labelBidak: "Pieces",
    semuaLevel: "All",
    sangatMudah: "Very easy",
    normal: "Medium",
    sangatSulit: "Very hard",
    semua: "All",
    langkahSatu: "1 move",
    langkahDua: "2 moves",
    langkahTiga: "3 moves",
    semuaTema: "All",
    temaGrupSkakmat: "Checkmate Patterns",
    temaGrupTaktik: "Tactical Motifs",
    temaGrupKarakteristik: "Characteristics",
    tema: {
      backRankMate: "Back-rank mate",
      smotheredMate: "Smothered mate",
      promotion: "Promotion",
      sacrifice: "Sacrifice",
      attraction: "Attraction (decoy)",
      deflection: "Deflection",
      pin: "Pin",
      fork: "Fork",
      discoveredAttack: "Discovered attack",
      doubleCheck: "Double check",
      hangingPiece: "Hanging piece",
      exposedKing: "Exposed king",
      endgame: "Endgame",
      middlegame: "Middlegame",
      opening: "Opening",
      master: "Master games",
      kingsideAttack: "Kingside attack",
      queensideAttack: "Queenside attack",
    },
    semuaGiliran: "All",
    hanyaPutih: "White only",
    hanyaHitam: "Black only",
    lanjutOtomatis: "Automatically load the next puzzle after each attempt",
    syzygyJudul: "Syzygy Tablebase",
    syzygyDidukung: "Powered by Lichess",
    engineDeskripsi:
      "Heads-up: turning on Stockfish reveals the evaluation and the best move for this position — it may spoil the puzzle. Best used to dissect the position after you've tried it yourself.",
    syzygyGagal:
      "This position cannot be analyzed by the tablebase (maximum 7 pieces).",
    syzygyMenganalisis: "Analyzing position…",
    syzygyDetail: "Details on Lichess ↗",
    syzygyCatatan: "Optimal result for the side to move.",
    syzygyKat: {
      win: "Win",
      "cursed-win": "Cursed win",
      draw: "Draw",
      "blessed-loss": "Blessed loss",
      loss: "Loss",
      unknown: "Unknown",
    },
    warnaPutih: "white",
    warnaHitam: "black",
    namaBidak: {
      p: "pawn",
      n: "knight",
      b: "bishop",
      r: "rook",
      q: "queen",
      k: "king",
    },
    ariaPetakKosong: "square {sq}, empty",
    ariaPetakBidak: "square {sq}, {warna} {bidak}",
    ingatPosisi:
      "Remember my last position — resume here when I return",
    posisiTersimpan: "Saved position: puzzle #{n}",
    ingatNonaktif: "Position is not being saved.",
    sumber:
      'Puzzles come from the Lichess puzzle database (real games, CC0 public domain), curated by <a href="https://delta-polder-indonesia.github.io/BintangToba/index.html" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:text-blue-800 underline">Bintang Toba (2026)</a>.',
    selanjutnyaJudul: "Explore E-Books & Guides",
  }
