/**
 * Data E-Book & Panduan — dipakai bersama oleh halaman Beranda
 * (EbookPanduan) dan ringkasan perpustakaan di Landing.
 *
 * - DAFTAR_EBOOK: berkas PDF yang ada di /public/ebooks/
 * - COVER: id buku -> sampul di /public/images/E-Books/
 * - KATEGORI_URUTAN: urutan barisan kategori pada filter Beranda
 */

export const DAFTAR_EBOOK = [
  {
    id: "101-prinsip-dasar-bermain-catur",
    judul: "101 Prinsip Dasar Bermain Catur",
    deskripsi: "Materi dasar-dasar bermain catur untuk pemula.",
    file: "/ebooks/101%20Prinsip%20Dasar%20Bermain%20Catur.pdf",
    kategori: "Dasar",
    ukuran: "2,0 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "basic-italian-a-grammar-and",
    judul: "BASIC ITALIAN A GRAMMAR AND",
    deskripsi: "Materi dasar-dasar bermain catur untuk pemula.",
    file: "/ebooks/BASIC%20ITALIAN%20A%20GRAMMAR%20AND.pdf",
    kategori: "Dasar",
    ukuran: "4,4 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "carokann-gambit-system-eng",
    judul: "carokann gambit system (eng)",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/carokann%20gambit%20system%20%28eng%29.pdf",
    kategori: "Opening",
    ukuran: "34,6 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "chess-opening-fundamentals-igor-smirnov-650",
    judul: "chess-opening-fundamentals-igor-smirnov-650",
    deskripsi: "Materi dasar-dasar bermain catur untuk pemula.",
    file: "/ebooks/chess-opening-fundamentals-igor-smirnov-650.pdf",
    kategori: "Opening",
    ukuran: "1,6 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "chess-tactics-for-students-id",
    judul: "chess-tactics-for-students (id)",
    deskripsi: "Latihan taktik, kombinasi, dan penyelesaian catur.",
    file: "/ebooks/chess-tactics-for-students%20%28id%29.pdf",
    kategori: "Taktik",
    ukuran: "19,2 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "dokumen-dari-syahrialm-indo",
    judul: "Dokumen dari SyahrialM (Indo)",
    deskripsi: "Dokumen panduan catur.",
    file: "/ebooks/Dokumen%20dari%20SyahrialM%20%28Indo%29.pdf",
    kategori: "Umum",
    ukuran: "19,8 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "gp-thinking-inside-the-box-indonesia",
    judul: "GP Thinking Inside the Box (Indonesia)",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/GP%20Thinking%20Inside%20the%20Box%20%28Indonesia%29.pdf",
    kategori: "Strategi",
    ukuran: "40,4 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "jeremy-silman-silmans-complete-endgame-course_-from-beginner-to-master-siles",
    judul: "Jeremy Silman - Silman's Complete Endgame Course_ From Beginner To Master-Siles",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/Jeremy%20Silman%20-%20Silman%27s%20Complete%20Endgame%20Course_%20From%20Beginner%20To%20Master-Siles.pdf",
    kategori: "Endgame",
    ukuran: "39,9 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "learning-chess-step-1",
    judul: "Learning chess Step 1",
    deskripsi: "Materi dasar-dasar bermain catur untuk pemula.",
    file: "/ebooks/Learning%20chess%20Step%201.pdf",
    kategori: "Dasar",
    ukuran: "3,3 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "learning-chess-step-2",
    judul: "Learning chess Step 2",
    deskripsi: "Materi dasar-dasar bermain catur untuk pemula.",
    file: "/ebooks/Learning%20chess%20Step%202.pdf",
    kategori: "Dasar",
    ukuran: "5,1 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "learning-chess-step-3",
    judul: "Learning chess Step 3",
    deskripsi: "Materi dasar-dasar bermain catur untuk pemula.",
    file: "/ebooks/Learning%20chess%20Step%203.pdf",
    kategori: "Dasar",
    ukuran: "11,5 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "learning-chess-step-4",
    judul: "Learning chess Step 4",
    deskripsi: "Materi dasar-dasar bermain catur untuk pemula.",
    file: "/ebooks/Learning%20chess%20Step%204.pdf",
    kategori: "Dasar",
    ukuran: "5,0 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "learning-chess-step-5",
    judul: "Learning chess Step 5",
    deskripsi: "Materi dasar-dasar bermain catur untuk pemula.",
    file: "/ebooks/Learning%20chess%20Step%205.pdf",
    kategori: "Dasar",
    ukuran: "15,6 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "mastering-chess-middl-game",
    judul: "Mastering Chess middl game",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/Mastering%20Chess%20middl%20game.pdf",
    kategori: "Strategi",
    ukuran: "7,7 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "mastering-middle-game-indo",
    judul: "Mastering middle game (indo)",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/Mastering%20middle%20game%20%28indo%29.pdf",
    kategori: "Strategi",
    ukuran: "13,7 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "mengapa-anda-kalah-dalam-bermain-catur",
    judul: "mengapa anda kalah dalam bermain catur",
    deskripsi: "Dokumen panduan catur.",
    file: "/ebooks/mengapa%20anda%20kalah%20dalam%20bermain%20catur.pdf",
    kategori: "Umum",
    ukuran: "8,5 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "pembukaan-gambit-menteri",
    judul: "Pembukaan Gambit Menteri",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/Pembukaan%20Gambit%20Menteri.pdf",
    kategori: "Opening",
    ukuran: "7,2 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "play-the-london-system-cyrus-lakdawala",
    judul: "Play the London System (Cyrus Lakdawala)",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/Play%20the%20London%20System%20%28Cyrus%20Lakdawala%29.pdf",
    kategori: "Opening",
    ukuran: "30,5 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "practical-chess-exercises-600-lessos",
    judul: "Practical Chess Exercises 600 Lessos",
    deskripsi: "Latihan taktik, kombinasi, dan penyelesaian catur.",
    file: "/ebooks/Practical%20Chess%20Exercises%20600%20Lessos.pdf",
    kategori: "Taktik",
    ukuran: "6,2 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "problem-catur-288",
    judul: "Problem Catur 288",
    deskripsi: "Latihan taktik, kombinasi, dan penyelesaian catur.",
    file: "/ebooks/Problem%20Catur%20288.pdf",
    kategori: "Taktik",
    ukuran: "12,1 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "ruy-lopez_anti-berlin-id",
    judul: "Ruy Lopez_Anti Berlin (id)",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/Ruy%20Lopez_Anti%20Berlin%20%28id%29.pdf",
    kategori: "Opening",
    ukuran: "71,7 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "sicilian-defense",
    judul: "Sicilian Defense",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/Sicilian%20Defense.pdf",
    kategori: "Opening",
    ukuran: "7,7 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "the-caro-kann-defense-eng",
    judul: "the-caro-kann-defense (eng)",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/the-caro-kann-defense%20%28eng%29.pdf",
    kategori: "Opening",
    ukuran: "10,5 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
  {
    id: "win-with-the-london-system",
    judul: "Win with the London System",
    deskripsi: "Materi strategi, pembukaan, dan rencana permainan catur.",
    file: "/ebooks/Win%20with%20the%20London%20System.pdf",
    kategori: "Opening",
    ukuran: "15,0 MB",
    halaman: "-",
    tahun: "-",
    tersedia: true,
  },
];

// Pemetaan sampul -> buku. Key = id entri di DAFTAR_EBOOK,
// value = path gambar di /public/images/E-Books/.
export const COVER = {
  "101-prinsip-dasar-bermain-catur": "/images/E-Books/cover-101-prinsip-dasar.webp",
  "basic-italian-a-grammar-and": "/images/E-Books/cover_6a78f8cfbde21.webp",
  "carokann-gambit-system-eng": "/images/E-Books/cover_6a7908e29c7a3.webp",
  "chess-opening-fundamentals-igor-smirnov-650": "/images/E-Books/cover_6a7909a91d321.webp",
  "chess-tactics-for-students-id": "/images/E-Books/cover_6a790acc54608.webp",
  "dokumen-dari-syahrialm-indo": "/images/E-Books/cover_6a790b84c8bda.webp",
  "gp-thinking-inside-the-box-indonesia": "/images/E-Books/cover_6a790c0eeb69b.webp",
  "jeremy-silman-silmans-complete-endgame-course_-from-beginner-to-master-siles": "/images/E-Books/cover_6a790cdddb621.webp",
  "learning-chess-step-1": "/images/E-Books/cover_6a790d7c40863.webp",
  "learning-chess-step-2": "/images/E-Books/cover_6a790e7531e8e.webp",
  "learning-chess-step-3": "/images/E-Books/cover_6a790f2db969a.webp",
  "learning-chess-step-4": "/images/E-Books/cover_6a790fc6c60d4.webp",
  "learning-chess-step-5": "/images/E-Books/cover_6a79105f61ca2.webp",
  "mastering-chess-middl-game": "/images/E-Books/cover-mastering-chess-middle-game.webp",
  "mastering-middle-game-indo": "/images/E-Books/cover_6a7a782fd243f.webp",
  "mengapa-anda-kalah-dalam-bermain-catur": "/images/E-Books/cover_6a7a78bc6909e.webp",
  "pembukaan-gambit-menteri": "/images/E-Books/cover_6a7a79edab10c.webp",
  "play-the-london-system-cyrus-lakdawala": "/images/E-Books/cover_6a7a7a8e4c93f.webp",
  "practical-chess-exercises-600-lessos": "/images/E-Books/cover-practical-chess-exercises.webp",
  "problem-catur-288": "/images/E-Books/cover-problem-catur-288.webp",
  "ruy-lopez_anti-berlin-id": "/images/E-Books/cover-ruy-lopez-anti-berlin.webp",
  "sicilian-defense": "/images/E-Books/cover-sicilian-defense.webp",
  "the-caro-kann-defense-eng": "/images/E-Books/cover-caro-kann-defense.webp",
  "win-with-the-london-system": "/images/E-Books/cover-win-london-system.webp",
};

// Urutan barisan kategori pada filter Beranda.
export const KATEGORI_URUTAN = ["Dasar", "Opening", "Strategi", "Taktik", "Endgame", "Umum"];

// Daftar kategori yang muncul pada filter, mengikuti KATEGORI_URUTAN lalu
// menyusul kategori lain (bila ada) sesuai urutan kemunculannya pada data.
export function kategoriDariDaftar(list = DAFTAR_EBOOK) {
  const ada = new Set(list.map((b) => b.kategori));
  const ikut = KATEGORI_URUTAN.filter((k) => ada.has(k));
  const sisa = Array.from(ada).filter((k) => !KATEGORI_URUTAN.includes(k));
  return [...ikut, ...sisa];
}