/**
 * Kamus Indonesia (ID) · kelompok analisa — halaman Analisa (analisis langkah, komentar partai, panel engine).
 * Kunci dalam berkas: analisa.
 */

export const analisa = {
    remah: "Remah navigasi",
    judul: "Analisis Permainan",
    tagline: "Bedah setiap langkah permainan Anda dengan Stockfish lokal",
    deskripsi:
      "Tempel PGN dari Chess.com atau Lichess, ambil daftar permainan lewat nama pengguna, atau mulai dari satu posisi FEN. Setiap langkah diberi label — brilian, terbaik, layak, keliru, blunder — disertai saran engine, grafik evaluasi, dan ringkasan akurasi kedua pemain.",
    privasi: "Seluruh analisis berjalan di peramban Anda — permainan tidak dikirim ke server mana pun.",
    basisDataJudul: "Basis Data Pembukaan Catur",
    basisDataIsi:
      "Masukkan langkah pembukaan pada papan catur di bawah ini untuk melihat nama pembukaan catur tersebut dan mendapatkan statistik dari permainan Grandmaster manusia untuk setiap langkah. Basis data kami berisi sekitar 26 juta langkah dari permainan Grandmaster catur terbaru dan memberi Anda gambaran tentang apa pun yang telah dimainkan oleh pemain catur manusia yang kuat.",
    petunjuk:
      "Pintasan papan: kiri/kanan untuk mundur/maju, atas/bawah ke langkah pertama/terakhir, spasi untuk memutar otomatis, Tab untuk berpindah panel.",
    metaJudul: "Analisis Permainan Catur Gratis",
    metaDeskripsi:
      "Analisis PGN dan FEN gratis dengan engine Stockfish lokal: label per langkah, grafik evaluasi, akurasi pemain, dan papan latihan. Permainan Anda tidak pernah diunggah.",
    bukaAplikasi: "Buka alat analisis",
    status: {
      judul: "Engine",
      mati: "Engine belum dimuat",
      memuat: "Mengunduh Stockfish (sekitar 7 MB, sekali saja)…",
      siap: "Stockfish siap dipakai",
      gagal: "Engine gagal dimuat",
      muat: "Muat engine sekarang",
      cobaLagi: "Coba lagi",
      tanpaWasm: "Peramban ini tidak mendukung WebAssembly, jadi analisis tidak dapat dijalankan.",
      peringatanWasm: "WebAssembly tidak tersedia",
      peringatanWasmIsi: "Analisis engine tidak dapat berjalan. Perbarui peramban Anda.",
      peringatanLama: "Engine lama sekali dimuat",
      peringatanLamaIsi: "Bila aplikasi tampak macet, muat ulang halaman ini.",
    },
    kedalaman: {
      judul: "Kedalaman analisis",
      cepat: "Cepat",
      sedang: "Sedang",
      dalam: "Dalam",
      maksimal: "Maksimal",
      petunjuk:
        "Engine pada situs ini berjalan pada satu utas, jadi kedalaman tinggi memakan waktu menit untuk permainan panjang.",
    },
    mesin: {
      judul: "Ulasan Game",
      petunjuk: "Engine diambil dari berkas lokal situs dan berjalan sepenuhnya di perangkat Anda.",
    },
    tab: {
      analisa: "Analisis permainan",
      analisaBaru: "Analisis permainan baru",
      pilihPartai: "Pilih permainan",
      ringkasan: "Ringkasan",
      langkah: "Langkah",
    },
    form: {
      judul: "Format permainan",
      tipe: "Tipe analisis",
      tempelPgn: "Tempel kode PGN permainan Anda di sini",
      tempelFen: "Tempel posisi FEN di sini (kosongkan untuk papan bebas)",
      namaPengguna: "Masukkan nama pengguna {platform} Anda",
      daftarPartai: "Daftar permainan",
      analisa: "Analisis",
      hint:
        "PGN boleh mengandung komentar, variasi dalam tanda kurung, dan kontrol waktu. FEN cukup satu baris.",
      contohPgn: "Contoh: 1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 1-0",
      contohFen: "Contoh: rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",

      dariAkun: "Dari akun",
      dariAkunIsi: "Muat semua permainan dari Chess.com atau Lichess lewat nama pengguna.",
      situs: "Situs",
      namaPenggunaLabel: "Nama pengguna",
      wajibNama: "Nama pengguna wajib diisi.",
      hintAkun: "Nama publik tanpa spasi. Setelah dipilih, seluruh arsip partai akan dimuat dalam satu tabel.",
      hintPgn: "Tempel notasi PGN; komentar dan variasi dalam tanda kurung diperbolehkan.",
      hintFen: "Cukup satu baris. Kosongkan untuk memulai dari papan kosong.",
    },
    format: { chessCom: "Chess.com", lichessOrg: "Lichess.org", pgn: "PGN", fen: "FEN" },

    panel: {
      kosongJudul: "Belum ada data permainan",
      kosongIsi: "Gunakan tombol Akun di bilah kiri untuk memuat seluruh partai dari Chess.com/Lichess, atau Impor permainan dari PGN, FEN, maupun tautan partai.",
      atau: "atau",
    },
    akun: {
      judul: "Tambah akun",
      isi: "Pilih situs lalu masukkan nama pengguna. Seluruh arsip partainya akan dimuat dalam satu tabel.",
      situs: "Situs",
      nama: "Nama pengguna",
      wajib: "Nama pengguna wajib diisi.",
      tambah: "Tambahkan",
      batal: "Batal",
      riwayat: "Nama yang pernah dipakai",
    },
    basisData: {
      judul: "Basis Data Permainan",
      subjudul: "Kelola, cari, dan analisa semua partai yang tersimpan lokal tanpa perlu mengambil ulang dari API.",
      semuaKoleksi: "Semua Koleksi",
      semuaPlatform: "Semua Platform",
      koleksi: "Koleksi / Akun",
      jumlahPartai: "{jumlah} partai tersimpan",
      totalStatistik: "{total} partai tersimpan di basis data ({menang} menang, {kalah} kalah, {seri} seri)",
      tersimpanLokal: "Tersimpan di Basis Data ({jumlah} partai)",
      dimuatDariDb: "Dimuat instan dari Basis Data lokal ({jumlah} partai)",
      tarikBaru: "Tarik terbaru dari {platform}",
      tarikUlang: "Tarik ulang dari API",
      eksporPgn: "Ekspor PGN",
      eksporPgnSukses: "Berkas PGN berhasil diunduh!",
      salinPgn: "Salin PGN",
      pgnTidakAda: "PGN partai ini tidak dapat dibaca.",
      pgnDisalin: "PGN berhasil disalin ke papan klip!",
      hapusKoleksi: "Hapus Koleksi",
      hapusPartai: "Hapus Partai",
      konfirmasiHapusKoleksi: "Hapus koleksi {koleksi} ({jumlah} partai) dari basis data?",
      konfirmasiHapusPartai: "Hapus partai ini dari basis data?",
      konfirmasiHapusSemua: "Hapus semua data partai dari basis data lokal?",
      hapusSemua: "Kosongkan Basis Data",
      sinkronkan: "Sinkronkan",
      menyinkronkan: "Mengambil data terbaru...",
      imporPgn: "Impor PGN",
      imporPgnJudul: "Tempel PGN untuk disimpan ke Basis Data",
      imporPgnBatal: "Batal",
      imporPgnSimpan: "Simpan ke Database",
      imporSukses: "{jumlah} partai berhasil ditambahkan ke Basis Data!",
      kosongJudul: "Belum Ada Partai di Basis Data",
      kosongIsi: "Partai yang ditarik dari Chess.com atau Lichess akan otomatis tersimpan di sini agar dapat dibuka dan dianalisa kapan saja tanpa menunggu API.",
      bukaAkun: "Tarik dari Chess.com / Lichess",
      analisaSekarang: "Analisa",
      filterHasil: "Hasil",
      filterWaktu: "Waktu",
      semuaHasil: "Semua Hasil",
      menang: "Menang",
      kalah: "Kalah",
      seri: "Seri",
      semuaWaktu: "Semua Waktu",
      cariPlaceholder: "Cari nama pemain, event, atau PGN…",
      detail: "Detail Partai",
      tanggal: "Tanggal",
      langkah: "Langkah",
      pemain: "Pemain",
      hasilTabel: "Hasil",
      aksi: "Aksi",
      sebelumnya: "Sebelumnya",
      berikutnya: "Berikutnya",
      halaman: "Halaman {aktif} dari {total}",
      tersimpanOtomatis: "Tersimpan otomatis ke Database lokal",
      sumberDatabase: "Basis Data Lokal",
      sumberApi: "API Langsung",
    },
    impor: {
      judul: "Impor permainan",
      tipe: "Tipe impor",
      pgn: "Tempel PGN",
      fen: "Tempel FEN",
      online: "Online",
      onlineLabel: "Tautan permainan",
      onlinePlaceholder: "https://www.chess.com/game/live/…  atau  https://lichess.org/…",
      onlineBantu: "Tempel tautan partai Chess.com atau Lichess; PGN-nya diambil otomatis lalu dianalisis.",
      ambil: "Ambil & analisis",
      analisa: "Analisis",
      memuat: "Mengambil PGN…",
      galatTautan: "Tautan tidak dikenali. Gunakan tautan partai Chess.com atau Lichess.",
      galatAmbil: "Gagal mengambil PGN dari tautan itu. Periksa koneksi atau salin PGN-nya langsung.",
    },    muat: {
      menganalisa: "Menganalisis",
      menganalisaPartai: "Menganalisis permainan",
      menyiapkanEngine: "Menyiapkan engine",
      membatalkan: "Membatalkan",
      dibatalkan: "Analisis dibatalkan",
      batal: "Batal",
    },
    pemutar: {
      awal: "Ke langkah pertama",
      mundur: "Satu langkah mundur",
      maju: "Satu langkah maju",
      akhir: "Ke langkah terakhir",
      putar: "Putar otomatis",
      jeda: "Jeda",
    },
    papan: { balik: "Balik papan", pengaturan: "Pengaturan", promosi: "Pilih bidak promosi" },
    nav: {
      pengaturan: "Pengaturan",
      play: "Bermain",
      playKeterangan: "Kembali ke papan analisis",
      baru: "Baru",
      baruKeterangan: "Mulai analisis baru — papan dikosongkan",
      baruKonfirmasi: "Yakin? Tekan lagi",
      akun: "Akun",
      database: "Database",
      impor: "Impor permainan",
      kodeSumber: "Kode Sumber",
      atribusi: "Atribusi",
    },
    pemain: { putih: "Putih", hitam: "Hitam", anonim: "Tanpa nama" },
    waktu: { jam: "{n} jam", menit: "{n} menit", hari: "{n} hari" },
    langkah: {
      palingBaik: "adalah langkah terbaik",
      tanpaLangkah: "Belum ada langkah yang dianalisis.",
      buku: "dalam buku pembukaan",
      kosong: "Tempel PGN atau mainkan langkah di papan untuk mulai menganalisis.",
      jumlah: "{n} langkah dianalisis",
    },
    ringkasan: {
      judul: "Ringkasan permainan",
      pemain: "Pemain",
      akurasi: "Akurasi",
      pembukaan: "Pembukaan",
      menengah: "Menengah",
      akhir: "Akhir",
      penilaian: "Perincian penilaian",
      grafik: "Grafik evaluasi",
      tidakAda: "Belum ada ringkasan — jalankan analisis terlebih dahulu.",
      material: "Keunggulan material",
      cukupLangkah: "Belum cukup langkah untuk menilai fase ini.",
      akurasiFase: "{fase}: akurasi {angka}%",
      ratingPartai: "Rating permainan",

    },
    grafik: {
      judul: "Keunggulan Putih sepanjang permainan",
      sumbu: "eval",
      petunjuk: "Klik bagian grafik untuk melompat ke langkah tersebut.",
      buku: "Langkah buku",
    },
    hasil: { menangPutih: "Putih menang", menangHitam: "Hitam menang", seri: "Seri", berjalan: "Belum selesai" },
    penilaian: {
      brilliant: "Brilian",
      great: "Sangat baik",
      best: "Terbaik",
      excellent: "Unggul",
      good: "Layak",
      book: "Buku",
      inaccuracy: "Keliru",
      mistake: "Kesalahan",
      miss: "Kelewat",
      blunder: "Blunder",
      forced: "Paksa",
      label: "Label",
      semua: "Semua",
      hanyaLabel: "Sorot berdasarkan label",
    },
    komentar: {
      brilliant: [
        "Anda menemukan pengorbanan yang brilian.",
        "Pengorbanan ini menunjukkan pemahaman posisi yang dalam.",
        "Pengorbanan berani untuk merebut keunggulan strategis.",
      ],
      great: [
        "Anda memanfaatkan kesalahan lawan dengan tepat.",
        "Langkah ini menghukum kekhilafan lawan secara maksimal.",
        "Tanggapan kuat atas kekeliruan lawan.",
      ],
      best: [
        "Ini langkah terbaik pada posisi ini.",
        "Inilah langkah paling tepat yang bisa Anda mainkan.",
        "Pilihan paling presisi untuk situasi ini.",
      ],
      excellent: [
        "Bukan langkah terbaik, tetapi kekuatannya setara.",
        "Langkah unggul yang sesuai dengan tuntutan posisi.",
        "Pilihan sekelas langkah terbaik, meski bukan yang nomor satu.",
      ],
      good: [
        "Tidak termasuk langkah terbaik, tetapi masih dapat diterima.",
        "Layak dimainkan, walau ada pilihan yang lebih kuat.",
        "Langkah ini bekerja, namun melewatkan alternatif yang lebih baik.",
      ],
      inaccuracy: [
        "Langkah ini mengikis keunggulan Anda.",
        "Posisi Anda melemah akibat langkah ini.",
        "Kekhilafan kecil yang membuat keadaan kurang menguntungkan.",
      ],
      blunder: [
        "Langkah ini membuang keunggulan secara besar-besaran.",
        "Posisi Anda memburuk tajam setelah langkah ini.",
        "Kesalahan serius yang merusak pertahanan Anda.",
      ],
      mate: ["Skakmat — selalu menyenangkan.", "Skakmat adalah tujuan akhir setiap permainan.", "Langkah penutup yang menentukan."],
      mateIn: [
        "Langkah yang memaksa skakmat segera tiba.",
        "Presisi yang menjamin skakmat dalam waktu dekat.",
        "Langkah ini menyiapkan rangkaian skakmat tak terbendung.",
      ],
      delayMate: [
        "Anda menunda skakmat, tetapi lawan tetap termat.",
        "Rangkaian skakmat diperlambat, meski hasilnya tetap sama.",
        "Skakmat ditunda selangkah, tetapi tak terelakkan.",
      ],
      advanceMate: [
        "Keputusan ini memperpendek jalan menuju kekalahan Anda.",
        "Anda mempercepat skakmat yang seharusnya bisa ditahan.",
        "Langkah ini membuat lawan semakin dekat dengan skakmat.",
      ],
      loseAdvantage: [
        "Keunggulan yang sudah di tangan hilang oleh langkah ini.",
        "Kesalahan mahal yang membuang kesempatan menang.",
        "Posisi berubah dari unggul menjadi seimbang atau lebih buruk.",
      ],
      giveAdvantage: [
        "Posisi seimbang berubah menjadi berat sebelah untuk lawan.",
        "Kesalahan yang menyerahkan keunggulan kepada lawan.",
        "Lawan kini punya keuntungan yang nyata.",
      ],
      gettingMated: [
        "Langkah ini berujung skakmat yang tidak bisa dihindari.",
        "Kesalahan fatal yang menjamin skakmat bagi lawan.",
        "Anda menyiapkan skakmat untuk diri sendiri.",
      ],
      missMate: [
        "Kesempatan skakmat terlewat dan lawan lolos.",
        "Skakmat yang bisa dipaksa justru ditinggalkan.",
        "Langkah ini membiarkan lawan menghindari skakmat.",
      ],
      missAdvantage: [
        "Kesempatan untuk memperoleh keunggulan terlewat.",
        "Peluang memperkuat posisi terbuang pada langkah ini.",
        "Ada cara yang lebih kuat di posisi ini.",
      ],
      forced: [
        "Tidak ada pilihan lain; hanya langkah ini yang legal.",
        "Posisi memaksa Anda memainkan langkah ini.",
        "Hanya satu langkah legal yang tersedia, dan itu langkah ini.",
      ],
    },
    komentarPartai: {
      menang: [
        "{menang} mengklaim kemenangan setelah permainan yang ketat. Mari kita bedah kekhilafan {kalah} dan langkah penentu {menang}.",
        "Performa solid {menang} mengamankan kemenangan. Kita lihat bagaimana {kalah} seharusnya bertahan.",
        "{menang} unggul lewat permainan strategis. Mari tinjau momen yang menentukan jalannya permainan bagi {kalah}.",
        "{menang} memanfaatkan kesempatan penting untuk menang. Kita analisis di mana {kalah} bisa bermain lebih baik.",
      ],
      seri: [
        "Tidak ada pihak yang berhasil menembus, dan permainan berakhir seri. Mari kita cari kesempatan yang terlewat di kedua sisi.",
        "Permainan mengendur menjadi seri setelah saling tekan. Mari tinjau keputusan-keputusan pentingnya.",
        "Pertarungan {menang} melawan {kalah} berakhir seri. Kita analisis apa yang bisa dilakukan berbeda.",
        "Seri setelah pertarungan dinamis dengan peluang bagi kedua pihak. Mari break down momen kuncinya.",
      ],
      netral: [
        "Permainan ketat antara {menang} dan {kalah}. Mari analisis momen-momen yang menentukan hasilnya.",
        "Permainan seimbang penuh perhitungan antara {menang} dan {kalah}. Kita bedah langkah dan keputusannya.",
        "Permainan yang kompleks dan menarik. Mari telaah rencana yang dijalankan {menang} dan {kalah}.",
        "Kedua pemain menampilkan permainan kuat. Mari tinjau titik balik yang menentukan permainan ini.",
      ],
    },
    formatLabel: {
      adalahLangkahA: "adalah langkah {label}",
      adalahLangkahAn: "adalah langkah {label}",
      adalah: "{label}",
    },
    partai: {
      judul: "Permainan {platform}",
      memuat: "Mengambil daftar permainan",
      batal: "Batal",
      tidakAda: "Tidak ada permainan.",
      mengambilApi: "Mengambil data dari server",
      pemain: "Pemain",
      hasil: "Hasil",
      tanggal: "Tanggal",
      hari: "Tgl",
      cari: "Cari pemain…",
      tidakCocok: "Tidak ada permainan yang cocok dengan pencarian.",
      legenda: "Hasil dihitung dari sisi {pemain}.",
      jumlahPartai: "{jumlah} partai",
      halaman: "Halaman {aktif} dari {total}",
      sebelumnya: "Sebelumnya",
      berikutnya: "Berikutnya",
      memuatArsip: "Mengambil arsip {bulan}",
      arsipGagal: "{jumlah} arsip gagal dimuat. Beberapa partai mungkin tidak tampil.",
      kelas: {
        bullet: "Bullet",
        blitz: "Blitz",
        rapid: "Cepat",
        classical: "Klasik",
        unknown: "Tanpa batas waktu",
      },
      jumlahLangkah: "Langkah",
      kontrolWaktu: "Kontrol waktu",
      bulan: "Bulan",
      tahun: "Tahun",
      pilihPartai: "Pilih salah satu permainan untuk dianalisis.",
      rated: "bersaing",
      kasual: "santai",
      ambilLagi: "Muat ulang",
      kembali: "Kembali ke formulir",
      galatJaringan: "Gagal mengambil daftar permainan",
      galatJaringanIsi: "Periksa koneksi internet Anda lalu coba lagi.",
      galatPengguna: "Pengguna tidak ditemukan",
      galatPenggunaIsi: "Periksa ejaan nama pengguna atau koneksi internet Anda.",
      galatBatas: "Server mungkin membatasi permintaan berlebih",
      galatBatasIsi: "Perlambat laju permintaan atau tunggu sebentar lalu coba lagi.",
      analisisGagal: "Analisis gagal",
    },
    galat: {
      pgnJudul: "PGN tidak terbaca",
      pgnIsi: "Pastikan isinya adalah PGN yang valid (contoh: 1. e4 e5 2. Nf3 1-0).",
      fenJudul: "FEN tidak terbaca",
      fenIsi: "FEN harus memuat delapan baris posisi, misalnya rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1.",
      engineJudul: "Engine gagal dimuat",
      engineIsi: "Berkas engine lokal tidak dapat diunduh. Muat ulang halaman, atau pilih engine lain di pengaturan.",
      analisisJudul: "Analisis terhenti",
    },
    pengaturan: {
      judul: "Pengaturan papan",
      temaPapan: "Tema papan",
      langkah: "Langkah",
      penilaian: "Label",
      langkahTerbaik: "Langkah terbaik",
      tampilPanah: "Tampilkan panah saran",
      panahSetelahLangkah: "Panah muncul setelah langkah lawan",
      langkahLegal: "Tunjukkan langkah legal",
      animasi: "Animasi langkah",
      suara: "Suara papan",
      sorotLabel: "Sorot kotak sesuai label",
      mesin: "Mesin",
      petunjuk: "Pengaturan ini disimpan di peramban Anda, tidak disinkronkan ke akun.",
      tutup: "Tutup pengaturan",
    },
    tema: {
      hijau: "Hijau",
      cokelat: "Cokelat",
      biru: "Biru",
      abu: "Abu-abu",
      merah: "Merah",
      ungu: "Ungu",
      oranye: "Oranye",
    },
    atribusi: {
      judul: "Atribusi & lisensi",
      pendahuluan:
        "Tampilan dan logika penilaian halaman ini dipindah dari Brilliant-Chess (MIT, © 2025 Delo). Engine catur, muat worker, dan seluruh komunikasi UCI memakai implementasi lokal situs ini.",
      judulDaftar: "Atribusi dan Lisensi",
      bidak: "Gambar bidak",
      bidakOleh: "Dibuat oleh Cburnett, lisensi CC-BY-SA-3.0.",
      pembukaan: "Buku pembukaan",
      pembukaanOleh: "Data olahan lichess-org/chess-openings, lisensi CC0.",
      engine: "Stockfish",
      engineOleh: "Distribusi stockfish.js (GPL-3.0) — berkas dijalankan dari folder /engines situs ini.",
      kode: "Berkas yang dipindah",
      kodeOleh: "MIT — sumber: github.com/wdeloo/Brilliant-Chess.",
      desain: "Tata letak halaman",
      desainOleh:
        "Pola layout Program Kami (judul besar + kartu grid) mengikuti prompt.md pada repositori ini, lisensi MIT.",
      suara: "Suara papan",
      suaraOleh:
        "Berkas MP3 di /SoundChess berasal dari set suara papan Chess.com, LLC. Hak cipta tetap pada pemiliknya; dipakai apa adanya untuk kebutuhan latihan komunitas, tanpa modifikasi dan tanpa klaim kepemilikan.",
      logo: "Logo situs",
      logoOleh:
        "Merek dagang milik pemiliknya (Chess.com, LLC dan lichess.org); dipakai hanya untuk identifikasi lewat tautan situs resmi.",
      sosialJudul: "Pelanggaran hak cipta",
      sosialDeskripsi:
        "Kami menghormati hak kekayaan intelektual orang lain. Jika Anda merasa karya Anda digunakan di situs kami tanpa izin, silakan hubungi tim kami melalui tautan di bawah ini. Sertakan bukti kepemilikan dan tautan konten yang bermasalah.",
      tutup: "Tutup",
    },
  }
