/**
 * Kamus Indonesia (ID) · kelompok papan — halaman Papan Interaktif (papan bebas, explorer pembukaan, komentator).
 * Kunci dalam berkas: papan.
 */

import { komentatorPapan } from "./komentator.js";

export const papan = {
    judul: "Penjelajah Pembukaan Catur",
    remah: "Pembukaan",
    penjelajah: "Penjelajah Pembukaan",
    penjelajahDeskripsi:
      "Telusuri variasi pembukaan langkah demi langkah dan lihat statistik setiap kelanjutan.",
    deskripsi:
      "Papan catur bebas untuk menganalisis dan mempelajari pembukaan. Mainkan langkah, dan nama pembukaan beserta kode ECO-nya muncul otomatis.",
    memuat: "Memuat buku pembukaan…",
    gagalMuat:
      "Gagal memuat data pembukaan. Periksa koneksi internet Anda, lalu muat ulang halaman ini.",
    suara: "Suara papan",
    suaraNyala: "Suara aktif — klik untuk mematikan",
    suaraMati: "Suara mati — klik untuk menghidupkan",
    setBidak: "Set Bidak",
    flip: "Balik",
    undo: "Undo",
    reset: "Reset",
    salinPgn: "Salin PGN",
    tersalin: "PGN tersalin!",
    pembukaan: "Pembukaan",
    variasi: "variasi",
    petunjukAwal:
      "Mulai bermain — nama pembukaan muncul saat posisinya dikenali.",
    belumAdaNama: "Belum ada nama pembukaan untuk posisi ini.",
    diLuarBuku: "Di luar buku pembukaan",
    langkahBerikutnya: "Langkah berikutnya",
    katalog: "Katalog Pembukaan",
    pilihPembukaan: "Pilih pembukaan…",
    cariPembukaan: "Cari nama atau kode ECO…",
    statistik: "Statistik",
    artikelJudul: "Tentang Pembukaan Ini",
    artikelMemuat: "Memuat ringkasan Wikibooks…",
    artikelKosong: "Ringkasan Wikibooks untuk pembukaan ini belum tersedia.",
    artikelSelengkapnya: "Tampilkan selengkapnya",
    artikelRingkas: "Tampilkan ringkas",
    artikelBaca: "Baca di Wikibooks",
    artikelOtomatis: "terjemahan otomatis",
    partai: "partai",
    ratingRata: "rating rata-rata",
    menangPutih: "Putih menang",
    menangHitam: "Hitam menang",
    seri: "Seri",
    tidakAdaHasil: "Tidak ditemukan pembukaan untuk “{q}”.",
    menampilkan: "Menampilkan {n} dari {total}",
    riwayat: "Riwayat Langkah",
    kosong: "Belum ada langkah.",
    keAwal: "Ke awal",
    mundur: "Mundur",
    maju: "Maju",
    keAkhir: "Ke akhir",
    pengaturan: "Pengaturan",
    resetPapan: "Reset papan",
    pengaturanPapan: "Pengaturan Papan",
    warnaPapan: "Warna papan",
    posisiFen: "Posisi FEN",
    daftarLangkahPgn: "Daftar Langkah (PGN)",
    posisiAwal: "Posisi awal",
    salin: "Salin",
    tersalinSingkat: "Tersalin",
    tutup: "Tutup",
    daftarLangkah: "Daftar Langkah",
    basisData: "Basis Data Penjelajah Pembukaan",
    kolomLangkah: "Langkah Berikutnya",
    kolomJumlah: "Jumlah Partai",
    kolomPersen: "Persentase Kemenangan",
    kolomPutihSeriHitam: "Putih / Seri / Hitam",
    warnaBiru: "Biru",
    warnaCokelat: "Cokelat",
    warnaOranye: "Oranye",
    warnaHijau: "Hijau",
    warnaAbu: "Abu-abu",
    warnaBiruMuda: "Biru muda",
    warnaBiruTua: "Biru tua",
    warnaKayu: "Kayu",
    warnaMarmerCokelat: "Marmer cokelat",
    warnaMarmerHijau: "Marmer hijau",
    engine: "Analisis Engine",
    engineDeskripsi:
      "Nyalakan Stockfish — berjalan penuh di peramban Anda (unduhan sekali ±7 MB) — untuk menilai posisi dan melihat barisan langkah terbaiknya.",
    engineNyalakan: "Nyalakan",
    engineMatikan: "Matikan",
    engineMemuat: "Memuat engine… (sekali saja, ±7 MB)",
    engineMenganalisis: "Menganalisis…",
    engineGagal: "Gagal memuat engine. Periksa koneksi internet, lalu coba lagi.",
    engineCobaLagi: "Coba lagi",
    engineCepat: "Cepat",
    engineSeimbang: "Seimbang",
    engineDalam: "Dalam",
    engineKedalaman: "Durasi analisis",
    engineKedalamanN: "Kedalaman {n}",
    engineSkor: "Evaluasi:",
    engineMate: "skakmat terdeteksi",
    engineBarisan: "Barisan langkah terbaik",
    engineMainkan: "Mainkan",
    engineSelesai: "Posisi sudah selesai (skakmat/seri) — tidak ada yang perlu dianalisis.",
    enginePanah: "Panah biru di papan = saran langkah engine.",
    enginePanahToggle: "Tampilkan panah saran engine",
    warnaMetal: "Metal",
    komentator: komentatorPapan,
    sumber:
      'Data pembukaan diambil dari lichess-org/chess-openings (lisensi CC0, domain publik), hasil karya <a href="https://delta-polder-indonesia.github.io/BintangToba/index.html" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:text-blue-800 underline">Bintang Toba (2025)</a>.',
  }
