/**
 * Kamus Indonesia (ID) · kelompok tekaTeki — halaman Teka-Teki (soal skakmat + komentator teka-teki).
 * Kunci dalam berkas: tekaTeki.
 */

import { komentatorTekaTeki } from "./komentator.js";

export const tekaTeki = {
    judul: "Teka-teki Catur",
    deskripsi:
      "Latih naluri taktismu dengan 5.486 soal skakmat dari partai nyata di basis data puzzle Lichess. Temukan skakmat dalam 1, 2, atau 3 langkah — ada petunjuk bila kamu buntu.",
    memuat: "Memuat teka-teki…",
    gagalMuat:
      "Gagal memuat data teka-teki. Periksa koneksi internet Anda, lalu muat ulang halaman ini.",
    caraMain:
      "Klik atau seret bidak milikmu ke petak tujuan. Cari langkah yang berujung skakmat — lawan akan membalas otomatis sesuai pertahanan terbaiknya.",
    caraTanda:
      "Tanda bantu analisis: klik kanan petak untuk menandainya dengan warna kuning; tahan klik kanan lalu seret untuk menggambar panah oranye; klik kanan pada petak yang sudah bertanda (atau klik kiri satu kali pada petak kosong) untuk menghapus semua tanda. Tahan Shift/Ctrl/Alt saat menandai untuk warna merah/hijau/biru.",
    hapusSemuaTanda: "Hapus Semua Tanda",
    soal: "Soal #{n} dari {total}",
    skakmat1: "Skakmat dalam 1 Langkah",
    skakmat2: "Skakmat dalam 2 Langkah",
    skakmat3: "Skakmat dalam 3 Langkah",
    mudah: "Mudah",
    menengah: "Menengah",
    sulit: "Sulit",
    giliranPutih: "Putih melangkah",
    giliranHitam: "Hitam melangkah",
    promosiJudul: "Promosi Bidak",
    promosiPutih: "Putih promosi ke…",
    promosiHitam: "Hitam promosi ke…",
    promosiMenteri: "Menteri (Ratu)",
    promosiBenteng: "Benteng",
    promosiGajah: "Gajah",
    promosiKuda: "Kuda",
    promosiBatal: "Batal",
    petunjuk: "Petunjuk",
    lewati: "Lewati",
    selanjutnya: "Selanjutnya",
    acak: "Acak",
    sebelumnya: "Sebelumnya",
    berikutnya: "Berikutnya",
    salah: "Belum tepat, coba lagi!",
    benar: "Bagus! Langkah tepat.",
    terpecahkan: "Checkmate.",
    sudahTerpecahkan: "Sudah pernah kamu pecahkan",
    komentator: komentatorTekaTeki,
    totalTerpecahkan: "Terpecahkan: {n}",
    langsungKe: "Langsung ke Soal",
    buka: "Buka",
    rentangNomor: "Nomor 1 sampai {total}",
    nomorTidakValid: "Masukkan nomor antara 1 dan {total}.",
    pengaturan: "Pengaturan",
    tidakAdaSoal:
      "Tidak ada soal yang cocok dengan kombinasi Level, Langkah, Tema, dan Giliran saat ini. Longgarkan salah satu saringan di Pengaturan.",
    lanjutOtomatis: "Lanjut otomatis",
    otomatisNyalakan: "Aktifkan lanjut otomatis",
    otomatisMatikan: "Nonaktifkan lanjut otomatis",
    labelSoal: "Soal",
    labelLevel: "Level",
    labelLangkah: "Langkah",
    labelTema: "Tema",
    labelGiliran: "Giliran",
    labelBidak: "Bidak",
    semuaLevel: "Semua",
    sangatMudah: "Sangat mudah",
    normal: "Normal",
    sangatSulit: "Sangat sulit",
    semua: "Semua",
    langkahSatu: "1 langkah",
    langkahDua: "2 langkah",
    langkahTiga: "3 langkah",
    semuaTema: "Semua",
    temaGrupSkakmat: "Pola Skakmat",
    temaGrupTaktik: "Motif Taktik",
    temaGrupKarakteristik: "Karakteristik",
    tema: {
      backRankMate: "Skakmat punggung",
      smotheredMate: "Skakmat sempit",
      promotion: "Promosi",
      sacrifice: "Pengorbanan",
      attraction: "Attraksi (umpan)",
      deflection: "Defleksi",
      pin: "Pengikat (pin)",
      fork: "Tusukan (fork)",
      discoveredAttack: "Serangan terbuka",
      doubleCheck: "Skak ganda",
      hangingPiece: "Bidak menggantung",
      exposedKing: "Raja terekspos",
      endgame: "Endgame",
      middlegame: "Middlegame",
      opening: "Pembukaan",
      master: "Partai master",
      kingsideAttack: "Serangan sayap raja",
      queensideAttack: "Serangan sayap menteri",
    },
    semuaGiliran: "Semua",
    hanyaPutih: "Hanya putih",
    hanyaHitam: "Hanya hitam",
    lanjutOtomatis: "Muat teka-teki berikutnya secara otomatis setelah setiap percobaan",
    syzygyJudul: "Tablebase Syzygy",
    syzygyDidukung: "Didukung oleh Lichess",
    engineDeskripsi:
      "Perhatian: menyalakan Stockfish menampilkan evaluasi dan langkah terbaik posisi ini — bisa membocorkan jawaban teka-teki. Paling pas untuk membedah posisi setelah Anda mencoba sendiri.",
    syzygyGagal:
      "Posisi ini tidak bisa dianalisis tablebase (maksimal 7 bidak).",
    syzygyMenganalisis: "Menganalisis posisi…",
    syzygyDetail: "Detail di Lichess ↗",
    syzygyCatatan: "Hasil optimal dari sisi yang giliran sekarang.",
    syzygyKat: {
      win: "Menang",
      "cursed-win": "Menang terkutuk",
      draw: "Seri",
      "blessed-loss": "Kalah berkat",
      loss: "Kalah",
      unknown: "Tidak diketahui",
    },
    warnaPutih: "putih",
    warnaHitam: "hitam",
    namaBidak: {
      p: "bidak",
      n: "kuda",
      b: "gajah",
      r: "benteng",
      q: "menteri",
      k: "raja",
    },
    ariaPetakKosong: "petak {sq}, kosong",
    ariaPetakBidak: "petak {sq}, {bidak} {warna}",
    ingatPosisi:
      "Ingat posisi terakhir saya — lanjutkan dari sini saat saya kembali",
    posisiTersimpan: "Posisi tersimpan: soal #{n}",
    ingatNonaktif: "Posisi tidak disimpan.",
    sumber:
      'Soal diambil dari basis data puzzle Lichess (partai nyata, lisensi CC0 domain publik), hasil karya <a href="https://delta-polder-indonesia.github.io/BintangToba/index.html" target="_blank" rel="noopener noreferrer" class="text-blue-600 hover:text-blue-800 underline">Bintang Toba (2026)</a>.',
    selanjutnyaJudul: "Jelajahi E-Book & Panduan",
  }
